### ISSUE TITLE
 Error writing result to store for query, Cannot read property 'add_image_to_verification' of undefined

### ISSUE THREAD

**Issue by LRstudentHU** [jaydenseric/apollo-upload-client#101]
Hi, I'm trying to upload a file from inside a Vue component using this package. When I try to upload the file, I keep getting this error:
```
Uncaught Error: Error writing result to store for query:
 mutation addImage($id: Int!, $field: String!, $file: Upload!) {
  add_image_to_verification(id: $id, field: $field, file: $file) {
    id
    __typename
  }
}
Cannot read property 'add_image_to_verification' of undefined
```
This is the mutation I am using:
```
 mutation addImage($id: Int!, $field: String!, $file: Upload!) {
    add_image_to_verification(id: $id, field: $field, file: $file) {
        id
    }
}
```

The code that calls the mutation. `File` is a File instance and is set, id is a number that signifies an id (the model this image will be attached to) and is also set.
```js
this.$apollo.mutate({
    mutation: AddImage,
        variables: {
            id: id,
            field: 'passport',
            file: file
        },
});
```

I initialize Vue and Apollo and Apollo upload client as follows:
```js
import { ApolloClient } from 'apollo-client';
import { buildAxiosFetch } from 'axios-fetch';
import { createUploadLink } from 'apollo-upload-client';
import { InMemoryCache } from 'apollo-cache-inmemory';
import VueApollo from 'vue-apollo';

import './bootstrap';
import Components from './components';

const link = createUploadLink({
    uri: document.location.origin + '/graphql',
    fetch: buildAxiosFetch(window.axios)
});

// Create the apollo client
const apolloClient = new ApolloClient({
    link,
    cache: new InMemoryCache(),
    connectToDevTools: true,
});

const apolloProvider = new VueApollo({
    defaultClient: apolloClient
});

const App = new window.Vue({
    el: "#app",
    components: Components,
    provide: apolloProvider.provide(),
    apollo: {}
});
```

On the server I am using Laravel with the `https://github.com/rebing/graphql-laravel` package. The error occurs before a request to the server is made, so the server is not the problem here. 

Do you know why I am getting this error?

**Comment by jaydenseric** [comment]
I don't use Vue, and I have not seen a similar error before. Do you still get the error if you use an alternative fetch polyfill, like cross-fetch? Also, try removing `connectToDevTools` and see what happens.

Other ideas:

- Is your browser [supported](https://github.com/jaydenseric/apollo-upload-client#support)?
- Is Apollo, and `apollo-upload-client` up to date?

**Comment by LRstudentHU** [comment]
Thanks for your response, it seems the fetch polyfill for Axios was causing problems. With cross-fetch, the error is gone and a request to the server is made and I will continue using cross-fetch.

What doesn't work is sending the csrf token in a header. When using the following code the `X-CSRF-TOKEN` header is not set:
```js
let token = document.head.querySelector("meta[name=\"csrf-token\"]").content;

let fetchOptions = {
    credentials: 'same-origin',
    mode: 'same-origin',
    headers: {
        'X-CSRF-TOKEN': token
    }
};

const link = createUploadLink({
    uri: document.location.origin + '/graphql',
    fetch,
    fetchOptions
});
```

 Is it possible that `createUploadLink` is not correctly setting the fetchOptions object? Things I have already tried:

- Settings the credentials to `include`
- Setting the mode to `cors`
- Using the native browser fetch (I am developing in the latest version of Chrome)
- Using the Headers constructor and appending in the header keys and values

None of the above worked. Do you have any ideas?

**Comment by jaydenseric** [comment]
By not working, do you mean the headers do not appear on the outgoing request when viewed in the Chrome dev tools network tab?

Does it work if you try to set headers [in the example app](https://github.com/jaydenseric/apollo-upload-examples/blob/master/app/providers/with-data.js#L18)?

**Comment by LRstudentHU** [comment]
Indeed, the `X-CSRF-TOKEN` header is not present in the Request Headers in Chrome dev tools.
Following the example in the link:
```js
// Create the apollo client
const apolloClient = new ApolloClient({
    link: createUploadLink({
        uri: document.location.origin + '/graphql',
    }),
    cache: new InMemoryCache(),
    connectToDevTools: true,
});
```
The above doesn't work; I also tried to include the `fetch` and `fetchOptions` like in the original question, but that doesn't change it unfortunately.

I have also tried removing `connectToDevTools` and `cache`; this doesn't affect it either.

I want to add that the server has `Access-Control-Allow-Headers: X-CSRF-TOKEN` as a default response header, so that should not be the problem.

**Comment by jaydenseric** [comment]
Hmm, I just reproduced it using apollo-upload-examples.

**Comment by jaydenseric** [comment]
Actually, would you like to raise a separate issue regarding the headers not being applied via the `createUploadLink` option `fetchOptions.headers`? I'll look into it.

**Comment by pennyandsean** [comment]
I have had this error after recent schema changes on the server where I needed to ensure my schemas built using merge-graphql-schemas were rebuilt.  Hope this helps.
