### ISSUE TITLE
Headers defined in fetchOptions not being sent 

### ISSUE THREAD

**Issue by LRstudentHU** [jaydenseric/apollo-upload-client#102]
Continuing from #101 

Using cross-fetch as the fetch driver, but the issue is reproducible using browser native fetch.

Setting headers in fetchOptions doesn't work. When using the following code the `X-CSRF-TOKEN` header is not set (it doesn't show up in the Chrome dev tools under Request Headers):
```js
let token = document.head.querySelector("meta[name=\"csrf-token\"]").content;

let fetchOptions = {
    credentials: 'same-origin',
    mode: 'same-origin',
    headers: {
        'X-CSRF-TOKEN': token
    }
};

const link = createUploadLink({
    uri: document.location.origin + '/graphql',
    fetch,
    fetchOptions
});
```

Creating the link as show in the example ([link](https://github.com/jaydenseric/apollo-upload-examples/blob/master/app/providers/with-data.js#L18)) also doesn't work:
```js
// Create the apollo client
const apolloClient = new ApolloClient({
    link: createUploadLink({
        uri: document.location.origin + '/graphql',
    }),
    cache: new InMemoryCache(),
    connectToDevTools: true,
});
```

The server does sent `Access-Control-Allow-Headers: X-CSRF-TOKEN`; so that can't be the issue.
Other things that have been tried:
- Settings the credentials to include
- Setting the mode to cors
- Using the native browser fetch (I am developing in the latest version of Chrome)
- Using the Headers constructor and appending in the header keys and values
- Removing `connectToDevTools` from the ApolloClient options
- Removing `cache` from the ApolloClient options

**Comment by jaydenseric** [comment]
In experimentation using apollo-upload-examples, this works:

```js
const link = createUploadLink({
  uri: process.env.API_URI,
  headers: {
    'X-Custom-Header': 'foo'
  }
})
```

While this does not:

```js
const link = createUploadLink({
  uri: process.env.API_URI,
  fetchOptions: {
    headers: {
      'X-Custom-Header': 'foo'
    }
  }
})
```

**Comment by zbyte64** [comment]
If I understand this correctly, this is preventing the `credentials` option from taking effect?

**Comment by drymph** [comment]
Any updates on this issue or an effective workaround for the `credentials` option?  I don't think the `headers` option lets you set the cookie header since it's controlled by credentials (or it's supposed to be at least),

**Comment by jaydenseric** [comment]
So, this is a bug in `apollo-link-http` too, which means it is almost certainly a bug in the `selectHttpOptionsAndBody` API of the `apollo-link-http-common` package.

This needs to be fixed on Apollo's end, then we just need to update to the fixed dependency version here.

**Comment by jaydenseric** [comment]
Closing because this is a bug in an Apollo dependency; once they patch it this will be fixed for `apollo-upload-client` consumers.
