### ISSUE TITLE
on mutation send the [Upload] with [File] array is not passed correctly and every File is NULL

### ISSUE THREAD

**Issue by dohomi** [jaydenseric/apollo-upload-client#104]
Hello

I push `File`-objects from an input type="file" into a javascript array. I defined the `[Upload]` in the graphql schema and resolver. The issue is: on submitting the form the `File` is not passed but turned into `NULL`
```gql
Mutation{
    sendMail(message:SendMailMessageInput, attachments:[Upload!]) : SendMailPayload
}
```
```js
{"0":["variables.attachments.0"]}
------WebKitFormBoundaryDpNwanpdAYnETJcZ
Content-Disposition: form-data; name="0"; filename="example.png"
Content-Type: image/png
```
Any idea what can cause this issue? I am using apollo-server v2. Is it because I send not only Upload but also additional information in my mutation?

**Comment by jaydenseric** [comment]
> Is it because I send not only Upload but also additional information in my mutation?

No, you should be able to use `Upload` types anywhere in mutation arguments.

If you are sure that apollo-upload-client is sending a spec-compliant multipart request, is this not a server issue?

**Comment by giautm** [comment]
It's must be a `FileList` instance, instead of a Javascript Array.

**Comment by jaydenseric** [comment]
@giautm both should work ok.

**Comment by dohomi** [comment]
@jaydenseric thanks for your heads up. I am using multiple input fields to merge each `FileList` to individual `File` types:
```js
 onAttachmentFilesChange ($event) {
        Array.from($event).forEach(file => {
          this.fileAttachmentsInfo.push({
            name: file.name,
            type: file.type,
            size: file.size
          })
          this.fileAttachments.push(file)
        })
      },
     onSubmit(){
        this.$apollo.mutate({
           mutation:GQL,
           variables:{attachments:this.files}
        })
     }
```
Its strange that while pushing the `File` objects into an Array somehow on submit the `File` information is gone. I'm not sure if this repo is currently responsible for it - the weird thing is that it worked sometimes - especially if I would place a debugger statement in the code. Do you have any experience in how to persist the `File` array reliable in a component before its finally getting sent out?

**Comment by dohomi** [comment]
<img width="195" alt="screen shot 2018-07-26 at 20 13 56" src="https://user-images.githubusercontent.com/489221/43261788-83068a56-9110-11e8-88c2-8999d52f7e85.png">

**Comment by dohomi** [comment]
Ok I finally found the issue: its basically just NULL on the client but the files are correctly passed to the server. I was looking into the wrong direction for a while.. Thanks for your response

**Comment by Yahyawi73** [comment]
I'm using apollo-server 
I get  input.file as Promis array of object unstead of Blob in the console is undefined could you help

**Comment by mateusmx** [comment]
> It's must be a `FileList` instance, instead of a Javascript Array.

Hi @giautm why it has to be a FileList ? I'm trying to implement Dropzone UI as part of my application, and I'm having issues uploading multiple files. 

When I make a <input type="file" multiple> I get the FileList and this is accepted ... But I've tried with an array of Files (returned from Dropzone) and this doesn't work.

Is there a way to turn around ? (attaching a picture)
![Captura de Pantalla 2022-01-16 a la(s) 15 52 38](https://user-images.githubusercontent.com/14305038/149679964-219dff34-e52d-4066-92d6-8dc9c27e5b73.png)



Regards !
