### ISSUE TITLE
Question: how to custom params with upload?

### ISSUE THREAD

**Issue by muei** [jaydenseric/apollo-upload-client#106]
If I wan't to upload with some params, I do like this, the server can get the file, but can't get the params selfParams:
```
const { data } = await apollo.mutate({
      mutation,
      variables: {
        file,
        selfParams: {...}
      },
    })
```

**Comment by mrdulin** [comment]
I made an example for this case: 

https://github.com/mrdulin/angular-apollo-starter/blob/master/src/app/core/file-upload.service.ts#L46

**Comment by jaydenseric** [comment]
I find the question a little confusing; mutation variables should work as normal. You can call them whatever you like, and you can use uploads anywhere in them.
