### ISSUE TITLE
How to write testings with mocha for graphql file upload server?

### ISSUE THREAD

**Issue by mrdulin** [jaydenseric/apollo-upload-client#107]
I have a graphql file upload server built with `apollo-upload-server`.

How can I mock file upload mutation to test my  graphql file upload server in nodejs environment? 

So as a nodejs back-end developer, I can test file upload feature without doing front-end stuff.

**Comment by jaydenseric** [comment]
You can see plenty of examples in the [`apollo-upload-server` tests](https://github.com/jaydenseric/apollo-upload-server/blob/master/src/test.mjs#L73).
