### ISSUE TITLE
Can't use Apollo Persisted Queries and apollo-upload-client together

### ISSUE THREAD

**Issue by lunks** [jaydenseric/apollo-upload-client#110]
I've cloned the github example from Apollo and just replaced HttpLink with CreateUploadLink. Doing this makes the app error out with:

```
Network error: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.
```

You can try it at: https://github.com/lunks/GitHunt-React/commit/becfa29e136691f4cfb06e705885f367e5619cf2

**Comment by jaydenseric** [comment]
Hmm. From that error it sounds like one of the links is setting a GET method for the request for some reason, then the upload link is setting a body for the multipart request.

Persisted queries have been troublesome in the past, maybe it relates to that: https://github.com/jaydenseric/apollo-upload-client/issues/61.

**Comment by jaydenseric** [comment]
I've published [`apollo-upload-client@10`](https://github.com/jaydenseric/apollo-upload-client/releases/tag/v10.0.0), which no longer mutates the operation when it includes files.

Does it help with this issue?

**Comment by jaydenseric** [comment]
@lunks I cloned your reproduction, and updated the `apollo-upload-client` dependency to v10 and it worked.

The GitHunt project has been deprecated and archived by Apollo, so it's very out of date and buggy, but I couldn't reproduce the error reported in this issue.

**Comment by raymondsze** [comment]
Please reopen this. 
The issue happen if we pass `useGETForHashedQueries: true` to createPersistedQueryLink.

The cause is `apollo-upload-client` assume the graphql query must be using http POST method.

I have submitted a pull request to simply fix this.
https://github.com/jaydenseric/apollo-upload-client/pull/146

**Comment by laukaichung** [comment]
Same problem. I cannot use this library because of this issue. I need to enable `useGETForHashedQueries` for cdn caching.
https://github.com/jaydenseric/apollo-upload-client/issues/151

**Comment by laukaichung** [comment]
Any updates on this?

**Comment by mike-marcacci** [comment]
@laukaichung there isn't, but you're welcome to submit a PR. This project is not part of Apollo, and is just maintained by people (mostly @jaydenseric) who needed to use uploads. As far as I know, most of the people who wrote this have moved away from Apollo to less bloated GraphQL libraries, and just maintain this as a courtesy. It looks like PR #146 might solve this problem, but its tests are failing. Getting those to pass might be a way to land this feature.
