### ISSUE TITLE
can't upload with angular

### ISSUE THREAD

**Issue by athemb** [jaydenseric/apollo-upload-client#111]
Hi
Can you help me please ^^' i need to upload with angular but, i don't find any example.
And wen i try, my payload is empty.

example :

https://gyazo.com/b724252cee58ac9dda43735ceb43657f
https://gyazo.com/023e5377273a89a56c3167a427676fed

thanks

**Comment by jaydenseric** [comment]
Does the past issue help? https://github.com/jaydenseric/apollo-upload-client/issues/44

**Comment by athemb** [comment]
thank you ^^
