### ISSUE TITLE
Can you make a example to extend upload files with progress percentage?

### ISSUE THREAD

**Issue by vietnd87** [jaydenseric/apollo-upload-client#112]
Hi,

As my entry, Progress bar is popular for upload script. It is wonderful if we can implement it with apollo upload client. 

Hope any one help this for me. Thanks!

**Comment by jaydenseric** [comment]
The closes thing you will get to an example is https://github.com/jaydenseric/apollo-upload-client/issues/88#issuecomment-384166141. My advice is not to bother with upload progress; substituting the native `fetch` API is a bit of a hack.

I don't intend to work on the problem, but if you do want to chat about it with others you could try the `#uploads` chanel of the Apollo Slack team 😌

**Comment by vietnd87** [comment]
Thank you for your inform, I tried your example from #88 but it is sort function some variables I can not to know how to import it: 

const xhr = new XMLHttpRequest()

fetch: typeof window === 'undefined' ? global.fetch : customFetch

They are: XMLHttpRequest, global, window

Sorry, I have no more experience in this. So, real happy if you share full code about this. :)
