### ISSUE TITLE
Apollo Upload client does not compile in create-react-app v2

### ISSUE THREAD

**Issue by karensg** [jaydenseric/apollo-upload-client#116]
Hi,

The new version of create-react-app v2 just got released and it crashes during compilation:
![image](https://user-images.githubusercontent.com/359682/46105583-1345a800-c1df-11e8-8fa4-8c627ad55036.png)
I think that this error should be solved with `extract-files` update which you already implemented and a new release should solve the problem.

K

**Comment by jaydenseric** [comment]
I just published [v9.0.0](https://github.com/jaydenseric/apollo-upload-client/releases/tag/v9.0.0), let me know there are any issues 🙏

**Comment by karensg** [comment]
That issue is solved, but after that a new one arises. Not sure whether this is because there is no .mjs support in the new version. Because in v1 it worked well.
![image](https://user-images.githubusercontent.com/359682/46132286-4f602380-c246-11e8-9bf4-b37448a50d7c.png)

**Comment by kulakowka** [comment]
<img width="586" alt="screen shot 2018-09-27 at 1 15 33 pm" src="https://user-images.githubusercontent.com/557190/46139531-770bb780-c257-11e8-9e23-229feaeb2866.png">

I have same problem.

```json
"react-scripts": "^2.0.0",
"apollo-upload-client": "^9.0.0",
```

**Comment by jaydenseric** [comment]
@karensg @kulakowka see https://github.com/jaydenseric/apollo-upload-client/issues/118#issuecomment-425424061

**Comment by jeffal** [comment]
@jaydenseric I receive the following error after upgrading from `8.1.0` to `9.0.0`:
<img width="728" alt="screenshot 2018-10-16 15 16 40" src="https://user-images.githubusercontent.com/2325629/47044733-957a1a00-d156-11e8-8b90-cea1f07d26b5.png">

**Comment by mabualwafa** [comment]
@jeffal , so you solved the issue by downgrading back to 8.1.0?

**Comment by jeffal** [comment]
Yes, the root of my issue ended up being more so related to usage of this [formdata-polyfill](https://www.npmjs.com/package/formdata-polyfill). I was able to workaround not upgrading for now.

**Comment by Knowledge91** [comment]
Why is this closed? The problem still exists:

```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/apollo-upload-client/lib/index.js:3

Read more here: http://bit.ly/2tRViJ9
```

**Comment by Knowledge91** [comment]
Ok. I needed to update `react-scripts` to version 2.0.5 my bad 😊
