### ISSUE TITLE
Doesn't include "extract-files" module when install.

### ISSUE THREAD

**Issue by heygema** [jaydenseric/apollo-upload-client#120]
I had a problem, when I installed apollo-upload-client on my project.
It doesn't include "extract-files" module. so it then got me error like
```
extractFiles is not a function
```
as it is undefined, so I had to hardcoded it. 
__I use :__ 
- yarn to install apollo-upload-client.
- MacOSX 10.13.3 High Sierra.

I'm not sure if this problem also happened to anybody else.
just want to inform this.
thanks before 🙂

**Comment by jaydenseric** [comment]
It's not clear what you mean by "doesn't include". Is it not installed in your `node_modules`?

I suppose you mean to say that Webpack is not resolving the `extractFiles` named import correctly? Make sure that Webpack is not misconfigured; it should resolve `.mjs` files before `.js`. See https://github.com/jaydenseric/apollo-upload-client/issues/118 and https://github.com/jaydenseric/apollo-upload-client/issues/117.

**Comment by heygema** [comment]
I think in when I looked into lib/index.js

it tries to import extractFiles from module "extract-files"
```
const {extractFiles, ReactNativeFile} = require("extract-files");
```
but the "extract-files" doesn't seem to be anywhere.

**Comment by heygema** [comment]
Oh, is it the bug from my CRA ?

**Comment by jaydenseric** [comment]
Extract files is definitely a dependency, so it it's not in your `node_modules` anywhere (search your `package-lock.json`) you have some sort of npm/yarn install bug:

https://github.com/jaydenseric/apollo-upload-client/blob/f61c49eafbf800b968d06b081abdfb45878989b2/package.json#L38

**Comment by heygema** [comment]
Found the problem,
Forgot to mention that I use reason-scripts,
I think the problem related to #118 and it was then fixed in CRA latest release.
So possibly I will look into [reason-scripts](https://github.com/reasonml-old/reason-scripts) to open an issue for this.

thanks ! @jaydenseric
