### ISSUE TITLE
Error creating build using uglifyjs-webpack-plugin (react)

### ISSUE THREAD

**Issue by stcrash** [jaydenseric/apollo-upload-client#121]
Hello

I get an error when generating a build using webpack settings:

```
optimization: {
	minimizer: [
		new UglifyJsPlugin({
			cache: true,
			parallel: true,
			sourceMap: true
		})
	]
},
```

Dependencies in package.json:
```
"react": "^16.5.2",
"react-dom": "^16.5.2",
"uglifyjs-webpack-plugin": "^2.0.1",
"webpack": "^4.22.0",
"webpack-cli": "^3.1.2",
"webpack-dev-server": "^3.1.10"

"apollo-upload-client": "^9.0.0",
"graphql": "^14.0.2",
"graphql-tag": "^2.10.0",
"graphql-tools": "^4.0.2"
```
Error:
```
ERROR in main.js from UglifyJs
Unexpected token: keyword (const) [./node_modules/apollo-upload-client/lib/index.js:3,0][main.js:1049,0]
```

**Comment by jaydenseric** [comment]
Your chosen tools stumble on ES `const` syntax. Here is the modern Webpack way to minify: https://webpack.js.org/guides/production/#minification

**Comment by jaydenseric** [comment]
See also: https://github.com/webpack-contrib/terser-webpack-plugin

It handles ES6 better, it's what Next.js uses: https://github.com/zeit/next.js/blob/v7.0.2-canary.9/packages/next/package.json#L95

**Comment by stcrash** [comment]
Jayden Seric, thanks!

You're right. By default, with the production option in the webpack config, my bundle is minimized successfully. I will definitely try your recommendations for using other minifiers.
