### ISSUE TITLE
Failed to compile. I can't generate a production build.

### ISSUE THREAD

**Issue by olchyk98** [jaydenseric/apollo-upload-client#125]
Hi. I have a project that uses apollo-upload-client. I have tried to compile my project (build), but iv got that error.

> Creating an optimized production build...
> Failed to compile.
> 
> Failed to minify the code from this file:
> 
>         ./node_modules/apollo-upload-client/lib/index.js:3
> 
> Read more here: http://bit.ly/2tRViJ9
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! client@0.1.0 build: `react-scripts build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the client@0.1.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/olesodynets/.npm/_logs/2018-10-31T20_30_08_712Z-debug.log

What's the problem?

**Comment by jaydenseric** [comment]
Are you using `apollo-upload-client` v9.1.0?

**Comment by olchyk98** [comment]
I have updated to @9.1.0 and now it compiles good. Thanks! :)
