### ISSUE TITLE
Allow headers to be set via function or object?

### ISSUE THREAD

**Issue by ggoforth** [jaydenseric/apollo-upload-client#127]
In my angular application, I'm using `createUploadLink` to create my graphql link.  
The headers are set at the time that the app module is instantiated, like so:

```
  constructor(apollo: Apollo, ls: LocalStorageService) {
    const token = ls.get('token'),
      headers = {};

    if (token) {
      headers['Authorization'] = `Bearer ${token}`;
    }

    apollo.create({
      link: createUploadLink({
        uri: `${environment.API}/graphql`,
        headers
      }),
      cache: new InMemoryCache()
    });
  }
```

In most cases, this is fine.  However the issue I'm having is that when a user logs in, this code runs before any other code, so there is no token to be found.  Then they login, the token is set, however this code has already run, so it requires a refresh of the browser to actually get my queries to include the auth header.  If `headers` could be set as a function then the header could be set late (after the above code runs) and still pick up the users token after login.  

@jaydenseric  would you be open to a PR for such functionality or should I be approaching this a different way?

**Comment by ggoforth** [comment]
It looks like all it would take is in the `createUploadLink` something like:

```
  if (typeof headers === 'function') {
    headers = headers();
  }
```

right before the `linkConfig` is set.

**Comment by jaydenseric** [comment]
The right way to do this is to use an Apollo Link that will set the right headers per request. You can see an example of this [in the official docs](https://www.apollographql.com/docs/react/recipes/authentication.html#Header).

Does this work for you? I don't have experience with the Angular implementation but I assume it allows concatenating Apollo Links.

**Comment by ggoforth** [comment]
Ah, I see.  I'll give this a shot!  This does look like what I'm interested in accomplishing.  Thanks for the response.  I'll close this issue but will respond back to confirm that works.  Thanks again!

**Comment by ggoforth** [comment]
@jaydenseric Just to confirm, I thought I needed the `createUploadLink` because the normal Apollo link didn't allow for mutlipart uploads?  So from the example in the docs, I would replace `createHttpLink` with the `createUploadLink` and then use `setContext` to implement proper headers?

**Comment by jaydenseric** [comment]
Yep!

**Comment by ggoforth** [comment]
My man!  Thanks for all the pointers, much appreciated!

**Comment by ggoforth** [comment]
Confirmed, this is exactly what I needed.  Thanks again!
