### ISSUE TITLE
CORS error only with file attachment

### ISSUE THREAD

**Issue by rosskevin** [jaydenseric/apollo-upload-client#131]
I've got a strange one.  I have CORS setup, which I'm about to show the evidence of below.  The app is working fine for all our GET/POST etc everywhere in the app, _except_ when using apollo-upload-client _with_ an attachment.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://api.advisorintake.com.0.0.0.0.nip.io/graphql. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)
```

As I read the message, I can show that it is definitively not true, we provide `Access-Control-Allow-Origin: *`

For CORS, we allow:
- `*` origins
- `HEAD, GET, POST, OPTIONS` methods
- any headers (though strangely the response only states `authorization`)

Below you'll see the OPTIONS:
![options](https://user-images.githubusercontent.com/136564/48808102-59058500-ece5-11e8-9d2a-f812342b34d1.png)

Now the POST:
![post](https://user-images.githubusercontent.com/136564/48808149-83574280-ece5-11e8-8eba-e7caae7ba5f6.png)

This attachment is on a ContactEditMutation.  This mutation works fine as long as I do not add the attachment, which makes me think that I'm not insane...

Am I missing something with the config of the apollo-upload-client?

**Comment by jaydenseric** [comment]
What does your Apollo Client / apollo-upload-client config look like?

**Comment by rosskevin** [comment]
`createApolloClient.ts` for our `ui` project:

```ts
import createApolloClientBase from '@alienfast/common/apollo/createApolloClient'
import Logger from '@alienfast/common/Logger'
import JwtStore from './auth/JwtStore'
import host, { resolveSubdomain } from './host'

const log = Logger.get('createApolloClient')

// ------------------------------
// cache these on page load to avoid any per-request cost
// determine uri as api + base domain + path e.g. api.archetype.com/graphql
const uri = host.createUrl({ subdomain: 'api', path: '/graphql' })
// ------------------------------

function getJwtFromStore() {
  const jwtToken = JwtStore.getJwtToken()
  if (jwtToken) {
    return jwtToken.token
  } else {
    return null
  }
}

export default function createApolloClient(introspectionQueryResultData: object) {
  const getOptions = () => {
    return {
      jwt: getJwtFromStore(), // dynamic/per network request
      subdomain: resolveSubdomain(),
      uri,
    }
  }

  return createApolloClientBase(introspectionQueryResultData, getOptions)
}
```

`createApolloClientBase.ts` (reused):

```ts
import { InMemoryCache, IntrospectionFragmentMatcher } from 'apollo-cache-inmemory'
import { IntrospectionResultData } from 'apollo-cache-inmemory/lib/types'
import { ApolloClient } from 'apollo-client'
import { ApolloLink } from 'apollo-link'
import { setContext } from 'apollo-link-context'
import { onError } from 'apollo-link-error'
import apolloLogger from 'apollo-link-logger'
import { createUploadLink } from 'apollo-upload-client'
import fetch from 'cross-fetch'
import Logger from '../Logger'
import createOmitTypenameLink from './createOmitTypenameLink'

const log = Logger.get('createApolloClient')

export interface Options {
  jwt?: string | null | undefined
  subdomain?: string | null | undefined
  uri?: string
}

export type GetOptions = () => Options

const omitTypenameLink = createOmitTypenameLink()

// https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-http#errors
const errorLink = onError(({ graphQLErrors, networkError }) => {
  if (graphQLErrors) {
    if (Array.isArray(graphQLErrors)) {
      graphQLErrors.map(graphQLError => {
        // problems are a non-standard error response (I think) that we are getting back
        const problems = (graphQLError as any).problems
          ? (graphQLError as any).problems.map((problem: any) => problem.explanation)
          : []
        log.error(`[GraphQL]: ${graphQLError.message}: ${problems.join(', ')}`)
      })
    } else {
      log.error(`[GraphQL]: `, graphQLErrors)
    }
  }
  if (networkError) {
    log.error(`[Network]: `, networkError)
  }
})

function createAuthLink(getOptions: GetOptions) {
  const authLink = setContext((_, { headers }) => {
    // get the token and subdomain - this is done per request
    const { jwt, subdomain } = {
      ...{ jwt: null, subdomain: null },
      ...getOptions(),
    }
    log.debug('Using subdomain', subdomain)

    const result = {
      headers: {
        ...headers,
      },
    }
    if (jwt) {
      // only add the authorization header if a token is present
      result.headers.authorization = `Bearer ${jwt}`
    }

    if (subdomain) {
      result.headers['X-Subdomain'] = subdomain
    }

    // return the headers to the context so httpLink can read them
    return result
  })
  return authLink
}

export default function createApolloClient(
  introspectionQueryResultData: object,
  getOptions: GetOptions,
) {
  // Only get uri at this point, this is done at page load.
  const { uri } = {
    ...{ uri: '/graphql' },
    ...getOptions(),
  }
  log.debug('Using uri:', uri)

  const httpLinkOptions = {
    fetch,
    uri,
  }

  const httpLink = createUploadLink(httpLinkOptions)

  let links = [createAuthLink(getOptions), errorLink, omitTypenameLink, httpLink]
  // if (log.isDebugEnabled()) {
  if (process.env.NODE_ENV === 'development') {
    links = [apolloLogger].concat(links)
  }
  const link = ApolloLink.from(links)

  return new ApolloClient({
    cache: new InMemoryCache({
      fragmentMatcher: new IntrospectionFragmentMatcher({
        introspectionQueryResultData: introspectionQueryResultData as IntrospectionResultData,
      }),
    }),
    link,
  })
}
```

**Comment by jaydenseric** [comment]
Ooof, that is a lot to absorb! It might be a good idea to check this upstream bug is not involved: https://github.com/jaydenseric/apollo-upload-client/issues/102.

**Comment by rosskevin** [comment]
Doesn't seem like it, this is the apollo-upload-client setup:

```
  const httpLinkOptions = {
    fetch,
    uri,
  }

  const httpLink = createUploadLink(httpLinkOptions)
```

**Comment by rosskevin** [comment]
I cross-checked chrome vs firefox, just to ensure I wasn't bumping into a browser bug.  Definitely a problem with my code or somewhere upstream.

**Comment by rosskevin** [comment]
Differences

|type| good | bad |
|----|-------|-----|
|OPTIONS|Access-Control-Request-Headers: authorization,content-type |Access-Control-Request-Headers: authorization|
|POST|content-type: application/json|Content-Type: multipart/form-data; boundary=---------------------------1606|

**Comment by rosskevin** [comment]
Looking at default content-type restrictions in my setup now...

**Comment by jaydenseric** [comment]
Although they should not be according to the HTTP spec, some systems are case sensitive about the header key capitalization. Your "good" is `content-type` and the "bad" is `Content-Type`.

**Comment by rosskevin** [comment]
I'm not an expert with CORS, but to me this seems to be the problem:


|type| good | bad |
|----|-------|-----|
|OPTIONS|Access-Control-Request-Headers: authorization,content-type |Access-Control-Request-Headers: authorization|

The **bad** follow up POST via upload client sends the `content-type` header, which isn't pre-flighted in the initial OPTIONS request.  Therefore it seems correct for the browser to raise the CORS exception.

Isn't that correct or am I misunderstanding?

**Comment by jaydenseric** [comment]
What fetch polyfill are you using?

**Comment by rosskevin** [comment]
`cross-fetch`

**Comment by jaydenseric** [comment]
If you try using native fetch in Chrome, does it work?

**Comment by rosskevin** [comment]
LOL I have never used native fetch.  By that I assume using it means

```ts
// import fetch from 'cross-fetch'
```

If so, I tried and reproduced the error.

**Comment by jaydenseric** [comment]
Cool, so that rules that out.

**Comment by rosskevin** [comment]
I'm definitely not setting it.

**Comment by jaydenseric** [comment]
You might not be, but that is one difference to note between a regular HTTP link POST request and a multipart request for a file upload.

**Comment by jaydenseric** [comment]
See: https://github.com/jaydenseric/apollo-upload-client/blob/v9.1.0/src/index.js#L129

**Comment by rosskevin** [comment]
Thanks for all the help @jaydenseric!  I have to go - holiday for me and won't be back for many days.

I just encountered a different error when digging around at the POST `Response`, `Request Entity Too Large`.

So the console is:

![console](https://user-images.githubusercontent.com/136564/48811522-ce785200-ecf3-11e8-989f-5642b3ef5741.png)


While the actual response is:

![response](https://user-images.githubusercontent.com/136564/48811564-0089b400-ecf4-11e8-8603-10fb40837aab.png)

**The console message is a red herring!**

It's something in my server stack rejecting the uploaded image.  Good to know that we can't count on CORS errors in both chrome and firefox!

It is actually at least noticeable in chrome - I was trying firefox lately but perhaps I need to go back. 
![chrome](https://user-images.githubusercontent.com/136564/48811736-b05f2180-ecf4-11e8-81c6-ac38b9dc2636.png)


This was a big waste of time!  Thank you very much for helping me troubleshoot.

**Comment by jaydenseric** [comment]
No worries, enjoy your trip :)

**Comment by rosskevin** [comment]
For the karma gods regarding nginx setup:
https://stackoverflow.com/a/28476755/2363935

> The default value for client_max_body_size directive is 1 MiB.

**Comment by jaydenseric** [comment]
It's also a good idea to keep such ngink/server limits in sync with [`graphql-upload` config](https://github.com/jaydenseric/graphql-upload#type-uploadoptions), for much better error handling.

**Comment by IgorDePaula** [comment]
I have this same problem, but I upload meny files, but with in particular not, this file have more than 200kb, the others not. How fix?

**Comment by pankajvaghela** [comment]
My setup was working perfectly fine until suddenly i get this error. ;-;
