### ISSUE TITLE
QUESTION: can it replace the HttpLink?

### ISSUE THREAD

**Issue by jaimesangcap** [jaydenseric/apollo-upload-client#133]
First of all, I would like to thank you for creating these set of packages. I already got `graphql-upload` and `apollo-upload-client` working very easily (thanks for the examples).

I replaced my web app's `ApolloClient` link
FROM: `HttpLink`  
TO:  `createUploadLink` from `apollo-upload-client`  (which upon looking at the code, it uses `ApolloLink`). 

The question is, is it ok to replace the whole app to use `link` created from `createUploadLink`, OR should I only use `createUploadLink` on mutations that requires uploads? 
Then other query/mutation should still use the `HttpLink`?

**Comment by jaydenseric** [comment]
You are supposed to replace the normal HTTP link with the one created by `createUploadLink()`. It can handle normal requests as well as mutations with file uploads :)

**Comment by jaimesangcap** [comment]
that is awesome! thank you for responding
