### ISSUE TITLE
request sent as application/json not multipart/form-data

### ISSUE THREAD

**Issue by faycelbouamoud** [jaydenseric/apollo-upload-client#136]
Hello guys, I am facing a problem with apollo-upload-client, whene I upload a photo from my device it send the request as application/json instead of 'mutlipart/form-data' like this:
`{
    input: {
        image: {
            uri: 'file:///some_file_in_my_device',
            name: 'image',
            type: 'image/jpeg'
        }
   }
}`
and on my server i get an error (calling pipe on undefined; cause no stream sent).
I am using :
React native 0.57.8
React 16.6.3
Apollo client 2.4.7
Apollo Upload client 9.0.0 (I did upgrade it to 10.0.0 but nothing change)
react-apollo 2.1.4

**Comment by jaydenseric** [comment]
Perhaps you forgot to use the [`ReactNativeFile`](https://github.com/jaydenseric/apollo-upload-client#class-reactnativefile) class?

**Comment by faycelbouamoud** [comment]
I used ReactNativeFile imported from 'apollo-upload-client' !

**Comment by jaydenseric** [comment]
Be aware that having the Chrome dev tools network inspector open can interfere with the React Native `FormData` implementation, causing network errors.

**Comment by faycelbouamoud** [comment]
I have react native debugger and I have the possibility to disable the network inspector and I did but the problem persist.

**Comment by faycelbouamoud** [comment]
yes, link is correctly wrapped in createUploadLink().
the problem happened when I upgraded react native version. but before that it worked perfectly!

**Comment by truonglh2372** [comment]
@faycelbouamoud I got the same problem and I've been messing around for 3 days then change my client file to
`import { InMemoryCache } from 'apollo-cache-inmemory';
import { ApolloClient } from 'apollo-client';
import { createUploadLink } from 'apollo-upload-client';

const client = new ApolloClient({
  link: createUploadLink('http://localhost:3000/graphql'),
  cache: new InMemoryCache()
});

export default client;
`
turned out it works.
hope it help

**Comment by jaydenseric** [comment]
@truonglh2372 what were you trying before?

**Comment by truonglh2372** [comment]
@jaydenseric my config was like this
```
import store from '../redux/store';
import Config from '../services/Config';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { ApolloClient } from 'apollo-client';
import { ApolloLink } from 'apollo-link';
import { BatchHttpLink } from 'apollo-link-batch-http';
import { createUploadLink } from 'apollo-upload-client';

const getToken = async () => {
  const token = await store.getState().auth.token;
  return token
}
const token = getToken();

const options = {
  uri: `http://localhost:3000/graphql`,
  headers: {
    authorization: token ? `Bearer ${token}` : null
  },
  credentials: 'include'
};

const httpLink = ApolloLink.split(
  operation => operation.getContext().hasUpload,
  createUploadLink(options),
  new BatchHttpLink(options)
);

const client = new ApolloClient({
  link: httpLink,
  cache: new InMemoryCache()
});

export default client;

```

**Comment by jaydenseric** [comment]
@truonglh2372 there are a few problems with that code.

Firstly, should `const token = getToken()` be `const token = await getToken()`?

Secondly, you want to get the token per request, not once at app startup in case the status of the token changes (e.g. user logs out) after the app has been running for a while in the browser tab.

**Comment by jaydenseric** [comment]
It's been a few weeks and no one has been able to narrow down a bug or provide a reproduction. If anyone manages to do either of those things we can reopen 🙏

**Comment by nafisholeh** [comment]
I faced with the same symptoms posted by @faycelbouamoud 

**Environment:**
"react-native": "^0.59.5",
"apollo-upload-client": "^10.0.1",
"react-native-image-crop-picker": "^0.24.1", => utilise `path` to upload the picked photo 

**My hypothesis**
I think this bug happens, only when the photo picker is not on the same page as the upload.

**Explanation**
I have two forms in my app:
(1) User registration (multiple pages)
(2) Inventory registration (only one page)

On (1), I am able to upload the photo and inside the request headers I found `content-type: multipart/form-data`
But on (2), I am seeing that the request headers I found `content-type: application/json`, and the server failed to read the photo.
fyi, I use the same code to process the picked photo using `ReactNativeFile` and also the Mutation  config for (1) and (2)
Thus I can safely assume that my hypothesis is correct


Hope this help @jaydenseric 
And if I have time, I would love to submit PR to fix this issue
