### ISSUE TITLE
Accessing the uploaded files

### ISSUE THREAD

**Issue by aylabyuk** [jaydenseric/apollo-upload-client#14]
This is more of a question. 

I can successfully upload files to a directory in the server but I do not know how to retrieve it. What is the proper way to do it? Is there an implementation for accessing files through graphql queries or do I have to create another endpoint for accessing files or images? 

I have tried running Filereader on the client code after accessing the static files but no luck.. the file is not in a jpg format.

**Comment by jaydenseric** [comment]
This depends a little on the API you want in regards to auth, thumbnailing, etc.

I my current app, the uploaded file gets uploaded to MongoDB GridFS in the cloud. I have a seperate `/files/:fileId` route on the API server that is responsible for serving requested files. In my GraphQL schema, files belonging to types (invoices in my case) have a `path`, or `uri` property for the client to use.

In my previous app, I built a thumbnailing GraphQL API. You can read the discussion about it [here](https://github.com/jaydenseric/apollo-upload-server/issues/1#issuecomment-287502933).

**Comment by jaydenseric** [comment]
Feel free to ask further questions 🙂
