### ISSUE TITLE
Working along with http link

### ISSUE THREAD

**Issue by wtrocki** [jaydenseric/apollo-upload-client#145]
All examples show using upload-client as terminating link. 
Is working with http link supported?

**Comment by jaydenseric** [comment]
Easy question to answer: No. Both can't work at once; the upload link is a direct replacement for the standard HTTP link. It is intended to do everything the HTTP link does, plus uploads. Much of the internals of both packages are shared in a third package, `apollo-link-http-common`.

**Comment by MrToph** [comment]
had the same question, would be good to mention that in the docs imo
