### ISSUE TITLE
Angular 6 compatibility

### ISSUE THREAD

**Issue by Kr4meur** [jaydenseric/apollo-upload-client#148]
Hi, I spent a lot of time in here to find an exemple of how to make this work with angular 6 ( #44 didn't really help ), do someone have any idea ?

My current working code for simple request is :  
```
import {HttpClientModule} from '@angular/common/http';
import {NgModule} from '@angular/core';

import {Common} from './common';

import {InMemoryCache} from 'apollo-cache-inmemory';
import {Apollo, ApolloModule} from 'apollo-angular';
import {HttpLink, HttpLinkModule} from 'apollo-angular-link-http';
import {IntrospectionFragmentMatcher} from 'apollo-cache-inmemory';

import {FragmentTypes} from '@scheduler/typing';

@NgModule({
    imports: [
        ApolloModule,
        HttpLinkModule
    ],
    exports: [
        HttpClientModule,
        ApolloModule,
        HttpLinkModule
    ],
})
export class GraphQLModule {
    constructor(private apollo: Apollo, private httpLink: HttpLink) {
        const uri = Common.BACKEND_URL;
        const http = httpLink.create({uri});

        const introspectionQueryResultData = FragmentTypes.FRAGMENT_TYPES.data;
        const fragmentMatcher = new IntrospectionFragmentMatcher({introspectionQueryResultData});
        const cache = new InMemoryCache({fragmentMatcher});

        apollo.create({
            link: http,
            cache: cache,
        });
    }
}
```

I know that I have to change the **httpLink.create** and use the **createUploadLink** but this is simply not working, I don't know why.

Thank's for the help.

**Comment by piyushbeli** [comment]
I also need an example with Angular 6. Can somebody please help?

**Comment by Kr4meur** [comment]
Hey @piyushbeli we finally managed to make it work with angular 6 !

```
let uri = Common.BACKEND_URL;
let http = this.httpLink.create({uri});
const multipartMutations = ['createChannel''];
const uploadLink = createUploadLink({uri, headers: {Authorization: token}});
const networkLink = split(
                    ({ query }) => {
                        const operationName = getOperationName(
                            query
                        );
                        return multipartMutations.includes(operationName);
                    },
                    uploadLink,
                    http
                );

this.apollo.create({
     link: networkLink,
     cache: cache,
});

```

The constant **multipartMutations** is where you'll define all the mutation for wich you'll use the **apolloUpload way to work**, for all the others, it will be the simple **apollo way** that will be used.

Note: for the const **uploadLink** we had to had a headers with authorization, I didn't show the code because it's specific for us but **token** is of course a variable that we created, you should create your own.

**Comment by piyushbeli** [comment]
@Kr4meur Thanks for the update. Is it possible to provide a complete example file? I am very new to Angular 6 so need more guidance.

**Comment by jaydenseric** [comment]
There is an official [`apollo-angular-link-http`](https://www.npmjs.com/package/apollo-angular-link-http) package for Angular users, seperate to this one.

I'm not very familiar with Angular, so I can't speak to the design or quality, but it supports file uploads:

https://www.npmjs.com/package/apollo-angular-link-http#file-upload
