### ISSUE TITLE
Unable to get filestream on server

### ISSUE THREAD

**Issue by markolech** [jaydenseric/apollo-upload-client#155]
Here's our component

```
export const SINGLE_FILE_UPLOAD = gql`
  mutation singleFileUpload($file: Upload!) {
    singleFileUpload(file: $file) {
      filename
      mimetype
    }
  }
`;

export function UploadOneFile(props) {
  const uploadMutation = useMutation(SINGLE_FILE_UPLOAD);
  const onDrop = useCallback(acceptedFiles => {
    console.log('acceptedFiles: ', acceptedFiles)
    uploadMutation({variables: { file: acceptedFiles}});
  }, [])
  const {getRootProps, getInputProps, isDragActive} = useDropzone({onDrop})

  return (
    <div {...getRootProps()}>
      <input {...getInputProps()} />
      {
        isDragActive ?
          <p>Drop the files here ...</p> :
          <p>Drag 'n' drop some files here, or click to select files</p>
      }
    </div>
  )
}
```

Our schema

```
scalar Upload

type Mutation {
    singleFileUpload(file: Upload!): File
}

```

We've tried the apollo-upload-client as a terminating link.

We're not getting a filestream on the back on the resolver and are instead getting the path.

Is there anything else we need to add on the client side?

**Comment by jaydenseric** [comment]
First thing to do it use the chrome network activity inspector to see if the client is sending a valid [GraphQL multipart request](https://github.com/jaydenseric/graphql-multipart-request-spec). If it is not, it means something is wrong on the client.

If the links are set up correctly, the most likely explanation is that the `file` variable is not an instance of `window.File`. I'm not sure what your dropzone component/hook provides as a "file", but maybe start buy checking that.

**Comment by jaydenseric** [comment]
As no bug has been identified there is nothing actionable on this end. Over 2 weeks has passed so hopefully you managed to get unstuck :)
