### ISSUE TITLE
required type "Upload!" was not provided

### ISSUE THREAD

**Issue by khirodAsurion** [jaydenseric/apollo-upload-client#156]
I Have React Side GQL Mutation Setup as below 
```
mutation singleUpload($file: Upload!) {
  SingleUpload(file: $file) {
    id
    path
    filename
    mimetype
  }
}
```

I am calling the mutation via Apollo Client providing file Object as `{Variable :file }` . 
I get error while calling graphql as 

```
{"errors":[{"message":"Variable \"$file\" of required type \"Upload!\" was not provided.","locations":[{"line":1,"column":23}],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["GraphQLError: Variable \"$file\" of required type \"Upload!\" was not provided.","   
```

**Comment by jaydenseric** [comment]
> providing file Object as `{Variable :file }`

Is that not the problem? Should it not be `{ file: file }`?

**Comment by khirodAsurion** [comment]
@jaydenseric Thank you for the reply..
My apologies for not providing the full code ..which would have made the question more clear 
I get instance of  Apolloclient as below 

`let uri = (envvariable.ALPHA_GRAPHQL_ENDPOINT || '') + envvariable.ALPHA_GRAPHQL_PATH;
const httpLink = new HttpLink({ uri: uri });
const graphQLApolloClient = new ApolloClient({
  cache: new InMemoryCache({ addTypename: false }),
  link: ApolloLink.from([authLink, httpLink, createUploadLink({ uri: uri })]),
  defaultOptions
});
export default graphQLApolloClient;`


then in my React App, I have created a generic Mutation Operation as below ( which takes the mutation ( which I have written in a file) and argument 
**---Mutation def-------------**
`mutation singleUpload($file: Upload!) {
  SingleUpload(file: $file) {
    id
    path
    filename
    mimetype
  }
}
`
my generic **GraphQLMutationService** that i call for any mutation 

`export const GraphQLMutationService = {
  mutationOperation: async (query, input) => {
    const mutationName = query.definitions[0].name.value;
    const user = await Auth.currentAuthenticatedUser();
    const token = user.signInUserSession.idToken.jwtToken;
    return await GraphQLApolloClient.mutate({
      mutation: query,
      **variables: { ...input },**
      fetchPolicy: 'no-cache',
      errorPolicy: 'all',
      context: {
        headers: buildContextHeaders(token)
      }
    })`

at the end, I call the mutation as below (file is the input that I got from HTML input and singleUpload is the Mutation ref that i have passed  to mutation )

`uploadFile: file => {
   
    return GraphQLMutationService.mutationOperation(singleUpload, file);
  }`

2 thingsI can think of  -
1> variables: { ...input } in the generic mutation defined above handles all other mutation that I have and  I was using that to handle file upload as well
2> I was reading one more issue for Upload I see that we should not use both HttpLink & UploadLink at the same time . if that is the case should i use UploadLink only  and that will also take care of non Upload related Mutation ?

**Comment by jaydenseric** [comment]
Can you please tidy up your post and comment with edits? With proper paragraphs, punctuation, and tidy code blocks I might be able to understand what's going on better to help.

**Comment by khirodAsurion** [comment]
@jaydenseric  hope this helps now .. 
 ..Please let me know if I need to provide any more details .Thank you for helping out here .

**Comment by jaydenseric** [comment]
Thanks for the tidy! As a tip, you can allow syntax highlighting of you code block by doing ` ```js `.

The problem (or the at least one problem) is that you have the `httpLink` in there, conflicting with `createUploadLink`:

```js
  link: ApolloLink.from([authLink, httpLink, createUploadLink({ uri: uri })]),
```

There can only be one "terminating" link; see the [setup instructions](https://github.com/jaydenseric/apollo-upload-client#setup):

<img width="924" alt="Screen Shot 2019-05-21 at 1 19 36 pm" src="https://user-images.githubusercontent.com/1754873/58066077-363c2680-7bcb-11e9-8ef5-0cf3fe261fad.png">
