### ISSUE TITLE
Cant send file from client to server using apollo-upload-client

### ISSUE THREAD

**Issue by diegotomasperez** [jaydenseric/apollo-upload-client#157]
I think my confing in the client is incorrect. can someone help me please?

```
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import {RootSession} from './App';
import * as serviceWorker from './serviceWorker';
import ApolloClient, { InMemoryCache } from 'apollo-boost'; 
import { ApolloProvider } from 'react-apollo';
const { createUploadLink } = require('apollo-upload-client')

const client = new ApolloClient({
    uri: "http://localhost:4000/graphql",
    //enviar token al servidor
    fetchOptions: {
      credentials: 'include'
    },
    request: operation => {
      const token = localStorage.getItem('token');
      operation.setContext({
        headers: {
          authorization : token
        }
      })
    },
    cache: new InMemoryCache({
      addTypename: false
    }),
    link: createUploadLink(),
    onError: ({networkError, graphQLErrors}) => {
      console.log('graphQLErrors', graphQLErrors);
      console.log('networkLErrors', networkError);
    }
  });


ReactDOM.render(

    <ApolloProvider client={client}>
        <RootSession />
    </ApolloProvider>,
    document.getElementById('root')
);

serviceWorker.unregister();
```

**Comment by jaydenseric** [comment]
If you read the setup instructions, you will see that you can’t use Apollo Boost. Hope that helps :)

**Comment by diegotomasperez** [comment]
I have changed it for apollo-client but i think my problem is inside of ApolloClient{}
How can i correct it? Thanks!

`import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import {RootSession} from './App';
import * as serviceWorker from './serviceWorker';
import ApolloClient from 'apollo-client'; //TIENE LA CONFIGURACION
import { ApolloProvider } from 'react-apollo'; //RODEA TODA LA APLICACION PARA ESPECIFICAR QUE USAMOS APOLLO
const { createUploadLink } = require('apollo-upload-client');
const { InMemoryCache } = require('apollo-cache-inmemory')

const client = new ApolloClient({
    uri: "http://localhost:4000/graphql",
    //enviar token al servidor
    fetchOptions: {
      credentials: 'include'
    },
    request: operation => {
      const token = localStorage.getItem('token');
      operation.setContext({
        headers: {
          authorization : token
        }
      })
    },
    cache: new InMemoryCache({
      addTypename: false
    }),
    link: createUploadLink(),
    onError: ({networkError, graphQLErrors}) => {
      console.log('graphQLErrors', graphQLErrors);
      console.log('networkLErrors', networkError);
    }
});


ReactDOM.render(

    <ApolloProvider client={client}>
        <RootSession />
    </ApolloProvider>,
    document.getElementById('root')
);

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();`

**Comment by charlesinwald** [comment]
Not sure if this is the problem, but the readme recommends using the migration guide to go from boost to a manually configured Apollo Client, I personally found it easy to use their config and modified it as I went along where necessary.  
One difference I noticed from my configuration is that I have the URI in a HTTPLink:
```
const client = new ApolloClient({
    link: ApolloLink.from([
        onError(({ graphQLErrors, networkError }) => {
            if (graphQLErrors)
                graphQLErrors.map(({ message, locations, path }) =>
                    console.log(
                        `[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`,
                    ),
                );
            if (networkError) console.log(`[Network error]: ${networkError}`);
        }),
        new HttpLink({
            uri: 'http://localhost:4000/graphql',
            credentials: 'same-origin'
        })
    ]),
    cache: new InMemoryCache()
});
```
