### ISSUE TITLE
How to use an HTTP interceptor with this?

### ISSUE THREAD

**Issue by digeomel** [jaydenseric/apollo-upload-client#159]
Hello, I've been using the following module which adds an HTTP interceptor to automatically show/hide a loader/spinner every time there's an ongoing GraphQL call:

https://github.com/mpalourdio/ng-http-loader

This worked fine when I was using `HttpLink`, but is broken now that I've replaced it with the apollo-upload-client `createUploadLink` method. Which I guess makes sense since `HttpLink` is using `HttpClientModule` internally, and the spinner depends on that for the interceptor.

So, the question is, is there a way to modify the interceptor or create my own, using the upload-client link?

**Comment by jaydenseric** [comment]
There is an official Angular link that supports file uploads (see [this comment](https://github.com/jaydenseric/apollo-upload-client/issues/148#issuecomment-484337524)), so I think you might have better luck working with that?

It sounds like this is more of a usage question than a bug report, and I don't use Angular, so I can't really help brainstorming ideas 😅

**Comment by digeomel** [comment]
@jaydenseric I was already using this link, but it did not support file uploading when I last checked.
It seems to work fine now, and without any major changes to the code!
Thanks for the heads-up! 👍 😄

**Comment by ChristianAlamoDuro** [comment]
@digeomel how did you implement this? I use the same library and i can´t get it to use the interceptors

**Comment by digeomel** [comment]
@ChristianAlamoDuro you cannot use the interceptors with **this** library, that was what my original question was about. But, you can get GraphQL file uploading to work with the apollo-angular-link-http library, as suggested above, so you don't need this library anymore.

**Comment by ChristianAlamoDuro** [comment]
> @ChristianAlamoDuro you cannot use the interceptors with **this** library, that was what my original question was about. But, you can get GraphQL file uploading to work with the apollo-angular-link-http library, as suggested above, so you don't need this library anymore.

okey, the problem is that with this apollo-angular-link-http i get the token, but in my app i have interceptors and when we call other queries, these pass through grapqhl interceptors and the app interceptor, do you have the same problem? or you delete directly the app interceptors

**Comment by digeomel** [comment]
@ChristianAlamoDuro I am sorry but I don't understand your question, and anyway, it seems to be related more to apollo-angular-link-http than this library here, so maybe you should post it there.

**Comment by gsolecki** [comment]
For everyone using this library with Angular for uploading files please stop using it and use https://github.com/apollographql/apollo-angular/tree/master/packages/apollo-angular-link-http instead.
Have a look at the section "File upload"

**Comment by unix17** [comment]
works solution,  example  using Angular 17 

// app.config.ts

  export const apolloConfig = () => ([
  {
        provide: APOLLO_OPTIONS,
        useFactory: apolloFactory,
        deps: [ HttpLink ]
  }
]);


export const apolloFactory = (httpLink: HttpLink) => {

  const http =  httpLink.create({ uri: environment.apiUrl });
  const upload = createUploadLink({ uri: environment.apiUrl, credentials: 'include' });

  const customLink = new ApolloLink((operation) => {
    const isUpload = operation.getContext()['isUpload'] || false; // using createUploadLink only if needed  
    if (isUpload) {
      return upload.request(operation,);
    } else {
      return http.request(operation);
    }
  });

  return {
    link: ApolloLink.from([ customLink ]),
    cache,
  };
};


export const appConfig: ApplicationConfig = {
   ...apolloConfig(),
   provideHttpClient(withInterceptors([ authInterceptor ])),
}


// some.service.ts

 public uploadFile(file: File, signal: AbortSignal): Observable<MutationResult<uploudResult>> {
    return this.graphqlService.postMutation<Record<string, any>>({
      mutation: MUTATION_CONSTANT,
      variables: { file },
      context: {
        headers: { 'apollo-require-preflight': true },
        fetchOptions: { signal },
        fetchPolicy: 'no-cache',
        notifyOnNetworkStatusChange: true,
        isUpload: true // pass isUpload true  parameter for mutation  or query 
      }
    })
  }
