### ISSUE TITLE
How to abort file upload in apollo-upload-client?

### ISSUE THREAD

**Issue by swomack** [jaydenseric/apollo-upload-client#162]
I was looking into the code of apollo-upload-client and i came across the following code -

```
var _createSignalIfSuppor = createSignalIfSupported(),
controller = _createSignalIfSuppor.controller,
signal = _createSignalIfSuppor.signal

if (controller) options.signal = signal
```

It seems to override the signal object passed with query/mutation's fetchOption and replace with another signal object.

Given this, can you please tell me how should i abort the file upload as i dont have access to this `AbortController` object.

**Comment by veeramarni** [comment]
Interesting, how can we abort the upload when the user wants to cancel the upload and provide options on when to clean up?

**Comment by jaydenseric** [comment]
Related: https://github.com/apollographql/apollo-link/pull/584

@veeramarni something to consider: https://github.com/apollographql/apollo-link/pull/584#issuecomment-487407061
