### ISSUE TITLE
Node.js support

### ISSUE THREAD

**Issue by safead** [jaydenseric/apollo-upload-client#164]
I need apollo-upload-client to act from Node.js side (Express server as the client in this case). All apollo parts works perfect, queries and subscriptions are working well and no problems except the file upload part. The problem is that Node.js do not support any of apollo-upload-client supported data formats (FileList, File, Blob). And I have no idea how to construct the data passed to Upload as $files variable. Can you please add ArrayBuffer support or any other custom object format to transfer as Upload data type? May be simple:

{
  buffer: ArrayBuffer,
  name: 'filename.txt',
  size: 12345
}

object can be supported?

**Comment by safead** [comment]
The problem was solved by customizing 2 files:

extractFiles.js (extract-files lib):
...
  if (
    (typeof File !== 'undefined' && value instanceof File) ||
    (typeof Blob !== 'undefined' && value instanceof Blob) ||
    value instanceof _ReactNativeFile.ReactNativeFile ||
    value instanceof ArrayBuffer // for Node.js
  ) {
    clone = null
    addFile([path], value)
...

index.js (apollo-upload-client lib):
...
      files.forEach((paths, file) => {
        if (file instanceof ArrayBuffer) {
          form.append(++i, Buffer.from(file), file.name); // for Node.js
        } else {
          form.append(++i, file, file.name);
        }
      });

...

important!!!

You should install "request" lib and add the import in index.js (apollo-upload-client lib):

import FormData from 'form-data';

=================
Simple solution, but will be better to support this "from the box"

**Comment by ahmadalfy** [comment]
Can you elaborate? I've different problem with node as well regarding this part:

https://github.com/jaydenseric/apollo-upload-client/blob/master/src/index.js#L97

`ReferenceError: fetch is not defined`.

**Comment by ahmadalfy** [comment]
I was able  to fix my issue by suppling polyfill for `fetch` using the `fetch` option

**Comment by Arun-KumarH** [comment]
@ahmadalfy  how did you provide the input for the file ?

**Comment by Arun-KumarH** [comment]
We are not able to provide either buffer or stream as input when using `apollo-upload-client` to act from Nodejs side ?
(Any other solutions apart from using `fetch` and `formdata` libs ?)

**Comment by jaydenseric** [comment]
This issue duplicates https://github.com/jaydenseric/apollo-upload-client/issues/134 and https://github.com/jaydenseric/apollo-upload-client/issues/129.
