### ISSUE TITLE
BadRequestError when upload file with cookies

### ISSUE THREAD

**Issue by JMoldes** [jaydenseric/apollo-upload-client#165]
When I use `apollo-upload-client` with express and redis with cookie session, I can't upload files.

The message error is:

```
BadRequestError: Missing multipart field ‘operations’ (https://github.com/jaydenseric/graphql-multipart-request-spec).
```

I have created a fork of the example project to simulate the problem, you can see it in:

[https://github.com/JMoldes/apollo-upload-examples/tree/error-with-express-redis](https://github.com/JMoldes/apollo-upload-examples/tree/error-with-express-redis)

The changes that I have made are:

* Install the modules `express`, `apollo-server-express`, `connect-redis-sessions`  and `cookie-parser`
* Modify `server.mjs` to use express, and use the middleware connect-redis-sessions, and create a test session when upload the first file
* Modify `_app.js` for add `credentials: 'include' `  to **createUploadlink**

When I execute `npm run dev' for api and app, (previously I have to install redis ...), the first file I upload is ok, because I have not sent any cookies yet,

But after the first file is sent, te api sent a cookie to client, and when I upload the sencod file the Api show the next message:

```
BadRequestError: Missing multipart field ‘operations’ (https://github.com/jaydenseric/graphql-multipart-request-spec).
```

If I comment the line 22: `app.use(fnCRS)`  the file upload ok.

![image](https://user-images.githubusercontent.com/4438532/61524099-ff8d5b80-aa15-11e9-856a-e00197a05b49.png)

Why can not I upload files with express and redis using session cookies

**Comment by jaydenseric** [comment]
What makes you think the issue is with this package? If you inspect the outgoing network request body, is the `operations` field present? If so, then you know the issue is on the GraphQL server side.

**Comment by JMoldes** [comment]
`operations` is present. The server works fine for all other cases in my app, 
that's why I thought it was something related to this package.

I will open an issue in apollo-server-express and in connect-redis-sessions.

Thank you


![image](https://user-images.githubusercontent.com/4438532/61611959-81bb9100-ac5d-11e9-96f8-71586020d401.png)

**Comment by jaydenseric** [comment]
> I will open an issue in apollo-server-express and in connect-redis-sessions.

Maybe work out what the exact issue is first; package maintainers are not really in a good position to debug your application code.
