### ISSUE TITLE
Bug: `fetch` is not defined when running on the server

### ISSUE THREAD

**Issue by ahmadalfy** [jaydenseric/apollo-upload-client#166]
I am using this as a part of Angular Universal application. While working in the browser, it's working perfectly. When I build a server version (SSR) it breaks with the following error:

```
ReferenceError: fetch is not defined
    at z2dT.exports.createUploadLink (
```

```javascript
exports.createUploadLink = ({
  uri: fetchUri = '/graphql',
  fetch: linkFetch = fetch,
  fetchOptions,
  credentials,
  headers,
  includeExtensions
} = {}) => {
  const linkConfig = {
    http: { includeExtensions },
    options: fetchOptions,
    credentials,
    headers
  }
```

This is because `fetch` does not work on node. This is how I am using it (unnecessary lines removed):

```typescript
import { createUploadLink } from "apollo-upload-client";

export function createApollo(httpLink: HttpLink) {
  const http = httpLink.create({ uri });
  const uploadLink = createUploadLink({ uri });

  const authLink = new ApolloLink((operation, forward) => {
  ...
  });

  const client = new ApolloClient({
    link: from([authLink, uploadLink, http]),
  });

  return client;
}
```

Upon removing the `uploadLink` and the dependency the application is build and work as expected except for the upload of course.

**Comment by mike-marcacci** [comment]
Where `fetch` is not defined globally, you can specify it in the [options of createUploadLink](https://github.com/jaydenseric/apollo-upload-client#function-createuploadlink).

**Comment by ahmadalfy** [comment]
Wow I didn't realize that. Will try and post an update.

**Comment by jun-gh** [comment]
@mike-marcacci Can I see sample on how to specify fetch on createUploadLink? 

Im trying it this way:
const uploadLink = createUploadLink({ uri: `${REACT_APP_GRAPHQL_SERVER_BASE_URL}graphql`, fetch });
It does not work, still showing fetch not defined.

**Comment by jaydenseric** [comment]
@jun-gh perhaps whatever your `fetch` variable is in that scope, is undefined. If you `console.log(typeof fetch)` before setting it in the `createUploadLink` options, is it definitely a function?
