### ISSUE TITLE
Support useGETForQueries 

### ISSUE THREAD

**Issue by mohsen1** [jaydenseric/apollo-upload-client#168]
We need to use GET for queries to optimize our app. Unlike [Apollo Link](https://www.apollographql.com/docs/link/links/http/), this doesn't support using GET for queries.

**Comment by mike-marcacci** [comment]
Hi @mohsen1, are you proposing sending _all_ requests with the GET verb, or only those which _do not_ contain any uploads? Because `Content-Type` only applies to the HTTP request's body, it's impossible to send multipart data via a bodyless GET verb.

**Comment by mohsen1** [comment]
Will Query request ever have have files? Apollo Link itself will never send Mutations with GET. Just Queries because for Query, HTTP caching works as expected when using GET.

**Comment by mike-marcacci** [comment]
While it's less common, queries can definitely have upload types sent as arguments (think, "search by image" scenarios). If you came up with a good PR that could correctly handle all the scenarios, I'm sure Jayden would look at it!

**Comment by jaydenseric** [comment]
This duplicates https://github.com/jaydenseric/apollo-upload-client/issues/151, you can track GET support there.
