### ISSUE TITLE
warning with vue-cli: export 'createUploadLink' was not found in 'apollo-upload-client'

### ISSUE THREAD

**Issue by francoisromain** [jaydenseric/apollo-upload-client#170]
Hello and thanks again for this great module, 

I use it with vue and apollo-client. It's imprted with `import { createUploadLink } from 'apollo-upload-client'`. Every thing works well.

Now, I try to add `apollo-upload-client` to the [transpileDependencies option](https://cli.vuejs.org/config/#transpiledependencies) of vue-cli, but it gives the following error:

```
 WARNING  Compiled with 1 warnings                                                                                   10:44:58
 warning  in ./src/api/_graphql-client.js
"export 'createUploadLink' was not found in 'apollo-upload-client'
```
How is it possible to make this work?

**Comment by jaydenseric** [comment]
Probably because what is published to npm is CJS, but you are attempting a named ESM import.

**Comment by francoisromain** [comment]
ok, I see. 

So in this docs: https://cli.vuejs.org/guide/browser-compatibility.html#usebuiltins-usage , we are in case 2 or 3, right?

So does apollo-upload-client need any polyfills?

**Comment by jaydenseric** [comment]
Here is a general indication of the level of traspilation published and what environments are supported:

https://github.com/jaydenseric/apollo-upload-client#support

You will need to polyfill `fetch`, `FormData`, and maybe `Promise`, but that is really up to what environments you support for your project.

I'm not familiar with Vue tooling or your particular use case, but it seems what you are discussing is more a usage question than a particular bug to report. If you do find a bug, of course we can reopen and look into it :)

**Comment by francoisromain** [comment]
thank you @jaydenseric
