### ISSUE TITLE
Map field names changed since v10

### ISSUE THREAD

**Issue by shinrox** [jaydenseric/apollo-upload-client#171]
Hi, for some reason since v10 file upload changed how files were mapped and sent in Form Data 

Using v9.0.1 and <
<img width="1088" alt="Captura de Tela 2019-11-28 às 12 10 13" src="https://user-images.githubusercontent.com/8506821/69817058-7a426080-11d8-11ea-98c0-c34f8552584c.png">
Set fieldName as 0 `map: {"0":["variables.file"]}`

Using V10.0.0 and >
<img width="1088" alt="Captura de Tela 2019-11-28 às 12 01 15" src="https://user-images.githubusercontent.com/8506821/69817064-7f071480-11d8-11ea-95a3-8c05ab58c2fc.png">

Set fieldName as 1 `map: {"1":["variables.file"]}`

Is there any way to configure this, or at least set it to start at 0?

**Comment by jaydenseric** [comment]
Is there a reason you want them to start at `0`?

I find it more intuitive to see that the first file is called `1`, the second `2`, etc. The data structure is a map, not an array, and the files are preceded by other fields.

According to the GraphQL multipart request spec, the file field names can be anything unique; they don't even have to be numbers:

https://github.com/jaydenseric/graphql-multipart-request-spec#multipart-form-field-structure

> File fields: Each file extracted from the operations object with a **unique, arbitrary field name**.

**Comment by shinrox** [comment]
Hi, @jaydenseric, Well, this is more a doubt than a need

I faced this problem because we had some projects at the company I work for that was expecting "0" (due to some weird definition from the back-end team) as the name of the uploaded file, upgrading to v10 > affected some of our systems, this is not a big deal, but it was annoying to figure out that the problem was just the field name.

But what about my question? Is there any way to customize this? As you said, multipart request defines that field names can be anything unique, so I think it would be nice to be able to define custom values and handle them as we please in server-side.

**Comment by jaydenseric** [comment]
> Is there any way to customize this?

No, not with `apollo-upload-client`. The best thing for everyone is to adhere to the spec, regarding the server implementation. Otherwise some other client (`graphql-react`, manual cURL requests, playgrounds, etc.) will eventually run into the same problem. There are no plans to add an option here to customize the field names, because that would encourage fragmentation in the ecosystem.

**Comment by shinrox** [comment]
Agree, tks for your time 🙂

**Comment by ishwar-kshirsagar** [comment]
This is bit hacky solution but it will work.

`import createUploadLink from 'apollo-upload-client/createUploadLink.mjs'

const uploadLink = createUploadLink({
  uri: (operation) => `<your server url>`,
  formDataAppendFile: (formData: FormData, fieldName, file) => {
    formData.set('map', '{"0":["variables.file"]}') // <-- Manually changing mapping key & index in below line
    formData.set('0', file) // <--
  },
})

const apolloClient = new ApolloClient({
  link: from([uploadLink, httpLink]),
  cache: new InMemoryCache(),
  defaultOptions: { ...},
})
`
We are using "graphql-upload": "^17.0.0" at server side
& "apollo-upload-client": "^18.0.1" at frontend.
Don't know why server is expecting file to be at 0th index & frontend is sending at 1st index. In above solution we are just manipulating payload to match with server.
It will be great if this gets resolved within library itself.
