### ISSUE TITLE
Supporting multiple uploads of type ReactNativeFile 

### ISSUE THREAD

**Issue by yunibaek** [jaydenseric/apollo-upload-client#173]
Hi,

Is there possibility to support handling multiple uploads of type `ReactNativeFile` in this library?

I would like to ideally do this:

```js
  mutation MultipleUploads($files: [Upload!]!) {
    multipleUpload(files: $files)
  }
```

Currently, only single file upload is supported, I was hoping to do something like this:

```js
const files = ReactNativeFile.list([{
   uri,
   name,
   type
}, {
   uri,
   name,
   type
}, ...]);
```

**Comment by jaydenseric** [comment]
Thanks for the suggestion :)

There used to be exactly that API, but it was removed to reduce complexity; a static method on the class increases everyone's bundles, regardless of usage:

- https://github.com/jaydenseric/extract-files/blob/v3.1.0/src/index.mjs#L113
- https://github.com/jaydenseric/extract-files/blob/master/changelog.md#400

There are a variety of simple ways to get the same result:

```js
const files = [a, b, c].map(file => new ReactNativeFile(file))
```

**Comment by yunibaek** [comment]
@jaydenseric I have tried the array method below:
```
const files = [a, b, c].map(file => new ReactNativeFile(file))
```

But it recognises the request as json and not `multipart/form-data` 
I'm correctly making sure that the accepted type is of `[Upload!]`.

Is there any actual working example I could take a look at? Thanks

**Comment by jaydenseric** [comment]
Sounds like maybe there is something wrong with the client setup?

`extract-files` (which `apollo-upload-client` uses) can definitely extract and array of `ReactNativeFile` instances:

https://github.com/jaydenseric/extract-files/blob/v7.0.0/src/test/lib/extractFiles.test.mjs#L150

**Comment by jaydenseric** [comment]
There is an example for uploading a list of files here:

https://github.com/jaydenseric/apollo-upload-examples/blob/master/app/components/UploadFileList.js

It's not using `ReactNativeFile`, but assuming a react native environment, you could switch the `FileList` instance used in variables for a `ReactNativeFile` array.

Someone made a PR for a React Native example, but it didn't make it over the line in the end:

https://github.com/jaydenseric/apollo-upload-examples/pull/2
