### ISSUE TITLE
Can't get upload client to actually send multipart requests

### ISSUE THREAD

**Issue by njg-nf** [jaydenseric/apollo-upload-client#178]
File upload works for me if I use Altair in the browser, so it's not a server issue at least.

[Minimal code example](https://github.com/jaydenseric/apollo-upload-client/files/4205351/testcase.ts.txt)

[Log data with incorrect request (apollo-client) and correct request (Altair)](https://github.com/jaydenseric/apollo-upload-client/files/4205514/logdata.txt)

**Comment by njg-nf** [comment]
This is using apollo-client 2.6.8 and apollo-upload-client 12.1.0. The server is running plain graphql plus graphql-upload 9.0.0.

**Comment by jaydenseric** [comment]
Probably the reason is this:

```js
const Blob = require('cross-blob');
```

For [`extract-files`](https://npm.im/extract-files) (used by `apollo-upload-client`) to detect the file in variables, it must be a global `Blob` instance, see:

https://github.com/jaydenseric/extract-files#function-extractfiles

**Comment by njg-nf** [comment]
It seems I've actually been asking the wrong question. The real problem (and the reason why I added that import) is that Blob, FormData (and of course File) aren't natively available when running on NodeJS, which makes it impossible to use your client for automatic uploads. I'll open a new issue.

**Comment by njg-nf** [comment]
Never mind, I just found #129 #134 #164 which pretty much answer my question.

**Comment by njg-nf** [comment]
Also would be good to mention directly that this doesn't work on Node and suggest a solution using form-data directly like yours from https://github.com/jaydenseric/apollo-upload-client/issues/134#issuecomment-448044472

**Comment by yaacovCR** [comment]
Another approach https://github.com/jaydenseric/apollo-upload-client/issues/172
