### ISSUE TITLE
Internal Server Error with KeystoneJS image upload: Missing multipart field ‘operations’

### ISSUE THREAD

**Issue by ra-external** [jaydenseric/apollo-upload-client#182]
I'm trying to upload an image to KeystoneJS.  The image corresponds to the KeystoneJS list `Image`,  with the following GraphQL schema

    mutation createImage(data: ImageCreateInput): Image
    
    input ImageCreateInput {
      file: Upload
    }

I'm uploading from TinyMCE, which here is a custom field inside the [KeystoneJS AdminUI][1].  Following the following instructions (https://stackoverflow.com/questions/60656730/how-can-one-upload-an-image-to-a-keystonejs-graphql-endpoint/60657015#60657015) I'm using `Apollo-upload-client` to upload the image, which apparently is already installed in the AdminUI as the Apollo Client.  Following the `Apollo-upload-client` [docs][2]  I am uploading the blob from inside the TinyMCE `images_upload_handler`

    const UPLOAD_MUTATION = gql`mutation upload($data: ImageCreateInput!) {
        createImage(data: $data) {
          id
          file {
            path
            filename
          }
        }
      }
    `;
    
    images_upload_handler: function(blobInfo, success, failure) {
    
    			const image = blobInfo.blob();
    			try {
    				log.debug('about to mutate');
    				log.debug(client);
    				client.mutate(
    				{
    				mutation: UPLOAD_MUTATION,
    				variables: { data: { file: image } }
    				}
    				).then(result => {
    				log.debug('result');
    				log.debug(result);
    				success(result);
    				});
    				} catch (e) {
    				log.debug('error', e.toString());
    			failure(e);
    			}
    	}

however KeystoneJS logs the following error, complaining of `Missing multipart field 'operations'`.  

> {"level":50,"time":1584092923059,"pid":29020,"hostname":"somewhere.or.other","name":"graphql","message":"Missing
> multipart field ‘operations’
> (https://github.com/jaydenseric/graphql-multipart-request-spec).","extensions":{"code":"INTERNAL_SERVER_ERROR"},"uid":"ck7q00y3x0000e4rjfevaapo3","stack":"<Original
> stack missing>\n    module.exports
> (node_modules/ensure-error/index.js:28:16)\n    _formatError
> (node_modules/@keystonejs/app-graphql/lib/apolloServer.js:97:44)\n   
> node_modules/apollo-server-errors/dist/index.js:167:34\n    Array.map
> (<anonymous>)\n    Object.formatApolloErrors
> (node_modules/apollo-server-errors/dist/index.js:165:27)\n   
> node_modules/apollo-server-express/dist/ApolloServer.js:47:39\n   
> runMicrotasks (<anonymous>)\n","name":"BadRequestError","v":1}

I'm a relative newbie with GraphQL and the answers I've found regarding this error and `apollo-upload-client` seem addressed to those mounting their own Apollo Servers, whereas I'm working with something already set up.  Any clues or help much appreciated!

  [1]: https://www.keystonejs.com/keystonejs/app-admin-ui/
  [2]: https://github.com/jaydenseric/apollo-upload-client#blob

**Comment by jaydenseric** [comment]
Always the first thing to do when debugging [GraphQL multipart requests](https://github.com/jaydenseric/graphql-multipart-request-spec) is to check if issue on the client, or server. You can use the Chrome inspector network tab to check the request body is a multipart form with the right fields. If so, the problem is most likely on the server.

**Comment by jaydenseric** [comment]
We can reopen this issue if you are able to isolate a reproducible bug in `apollo-upload-client`.

**Comment by ra-external** [comment]
In fact I did that here -- https://stackoverflow.com/questions/60668590/keystonejs-throws-internal-server-error-missing-multipart-field-operations-on -- from what I was told there it seems to be a server issue, so I'd apprciate your re-opening the issue.

**Comment by jaydenseric** [comment]
> from what I was told there it seems to be a server issue, so I'd apprciate your re-opening the issue

As someone [already explained](https://stackoverflow.com/questions/60668590/keystonejs-throws-internal-server-error-missing-multipart-field-operations-on#comment107343359_60668590), it is likely a server issue. `apollo-upload-client` is a ***client*** library, and seems to be doing it's job ok.

**Comment by ra-external** [comment]
I'm sorry. My fault entirely -- attending to early morning emails.   I had raised this on the KeystoneJS forum as well and thought I was responding there.
