### ISSUE TITLE
Client sending query with files as null

### ISSUE THREAD

**Issue by kingkyle** [jaydenseric/apollo-upload-client#185]
I get the Files are replaced with null.
I use React-Dropzone for the files.
The First image shows the data sent.
The Second shows the request Error.
See Images
<img width="1438" alt="Screenshot 2020-03-29 at 02 02 48" src="https://user-images.githubusercontent.com/38464469/77837482-b2938480-7161-11ea-933d-0012d5ee68cd.png">
<img width="1242" alt="Screenshot 2020-03-29 at 02 03 33" src="https://user-images.githubusercontent.com/38464469/77837485-bc1cec80-7161-11ea-9a07-7129a4d91273.png">

**Comment by jaydenseric** [comment]
At first glance, that request looks fine to me. The files are supposed to be replaced with `null` placeholders, see:

https://github.com/jaydenseric/graphql-multipart-request-spec#multipart-form-field-structure

Your problem is probably on the server.

**Comment by kingkyle** [comment]
Yes. Fixed it
Thanks

**Comment by amineoutmal** [comment]
@kingkyle  hey what was the errors ?
