### ISSUE TITLE
Cannot upload image from react native image picker to graphql server

### ISSUE THREAD

**Issue by LyhengTep** [jaydenseric/apollo-upload-client#187]
Hi there, I am trying to upload image from my react native app to graphql by using Apollo client with createUploadLink(). When I am trying to mutate data on my android device by passing a ReactNativeFile as a variable, then it says network request failed. could someone please help me out from this?

Here is my code: 

```js
// Client setup
const client = new ApolloClient({
  link: createUploadLink({ uri: 'http://localhost:4000' }),
  cache: new InMemoryCache(),
});

// Upload image
const [singleUpload, { data }] = useMutation(UPLOAD_IMAGE);

ImagePicker.showImagePicker(options, async (response) => {
  const file = new ReactNativeFile({
    uri: response.uri,
    type: 'image',
    name: response.fileName,
  });

  let res = await singleUpload({
    variables: {
      data: {
        file: file,
      },
    },
  });
});
```

Note: My server set up for upload image is already work for react js.

Environment:

```json
{
  "react": "16.11.0",
  "react-native": "0.62.2",
  "react-native-image-picker": "^2.3.1",
  "apollo-client": "^2.6.8",
  "apollo-upload-client": "^13.0.0"
}
```

**Comment by hanzketup** [comment]
Just ran into the same issue.
`ReactNativeFile` wants a valid MIME type as the `type`, not the type image picker spits out.
In your case, change `image` to `image/jpeg` :
```
const file = new ReactNativeFile({
uri: response.uri,
type: 'image/jpeg',
name: response.fileName,
});
```

**Comment by PiperGuy** [comment]
@LyhengTep I was facing the same issue. i was using the below code to get the network requests sent by my app in the chrome debugger

```
global.XMLHttpRequest =
  global.originalXMLHttpRequest || global.XMLHttpRequest;
global.FormData = global.originalFormData || global.FormData;

if (window.FETCH_SUPPORT) {
  window.FETCH_SUPPORT.blob = false;
} else {
  global.Blob = global.originalBlob || global.Blob;
  global.FileReader = global.originalFileReader || global.FileReader;
}
```

 [apollo-upload-client](https://github.com/jaydenseric/apollo-upload-client) wont send the data in multipart data if you are using chrome debugger u will face network issue.  #82 issue has the answer. or I had not removed apollo-boost and some part of my app was using it that was also a issue. 

thanks.

**Comment by LyhengTep** [comment]
@hanzketup Thank you for your response, I've already added valid mime type but it remained the same.

**Comment by LyhengTep** [comment]
@PiperGuy after I added this code snippet when I upload the image I got the error like below:

TypeError: Failed to execute 'append' on 'FormData': parameter 2 is not of type 'Blob'.
    at formDataAppendFile (index.js:30)
    at index.js:119
    at Map.forEach (<anonymous>)
    at ApolloLink.request (index.js:118)
    at execute (link.js:84)
    at QueryManager.getObservableFromLink (bundle.umd.js:2066)
    at bundle.umd.js:1292
    at tryCallTwo (core.js:45)
    at doResolve (core.js:200)
    at new Promise (core.js:66)

**Comment by PiperGuy** [comment]
No that code was the issue for me! You should not add it

**Comment by LyhengTep** [comment]
@PiperGuy  I see, but in my app, I didnt use apolloboost .

**Comment by PiperGuy** [comment]
Are u using chrome debugger? That might be the issue too

**Comment by LyhengTep** [comment]
@PiperGuy  I use flipper with latest react-native to debug the code

**Comment by PiperGuy** [comment]
Try not using debugger u might find the solution ! I am not sure about flipper.

**Comment by LyhengTep** [comment]
@PiperGuy  anyway it's strange that when I try to upload the image from my ios simulator and the request reaches the server, but it got an error when I await to resolve the file. The error said: File missing in the request.

**Comment by PiperGuy** [comment]
Check the response being sent by ur simulator and is it multipart data?

**Comment by jaydenseric** [comment]
Thanks to everyone helping :)

@LyhengTep I edited your issue to format the code properly so it is readable, please see the “Syntax highlighting” section here:

https://guides.github.com/features/mastering-markdown

Closing because GitHub issues is not really the right place to debug a project, but feel free to continue the discussion here - noting that [20 people watching this repo](https://github.com/jaydenseric/apollo-upload-client/watchers) are alerted by email to each comment, most of us not React Native users. We can reopen this issue if you are able to isolate a *specific* `apollo-upload-client` bug.

Good luck!

**Comment by LyhengTep** [comment]
@PiperGuy it is but I found that the image name from that return image picker is missing so I generated the name for it then it worked, but only on ios. for android cant even reach the server.

**Comment by PiperGuy** [comment]
> @PiperGuy it is but I found that the image name from that return image picker is missing so I generated the name for it then it worked, but only on ios. for android cant even reach the server.
> 
> 

Even i am facing that issue

**Comment by LyhengTep** [comment]
@jaydenseric  Hello I noticed different uri between ios and android. for android it begins with content:// but for ios it begins with file://

**Comment by LyhengTep** [comment]
> > @PiperGuy it is but I found that the image name from that return image picker is missing so I generated the name for it then it worked, but only on ios. for android cant even reach the server.
> 
> Even i am facing that issue

Okay I'll get back to you If I find any solution

**Comment by jaydenseric** [comment]
@LyhengTep please read through https://github.com/jaydenseric/apollo-upload-client/issues/109 .

**Comment by PiperGuy** [comment]
@LyhengTep I have gone though #109 and i didn't find the solution.

**Comment by LyhengTep** [comment]
> @LyhengTep I have gone though #109 and i didn't find the solution.
Same here it doesn't work for me as well

**Comment by laugustol** [comment]
Hello, I changed my client from apollo-boost to apollo-client and I still have an error

Possible Unhandled Promise Rejection (id: 1):
Error: Network error: Network request failed

**Comment by laugustol** [comment]
have you found any solution? @LyhengTep @PiperGuy

**Comment by PiperGuy** [comment]
> have you found any solution? @LyhengTep @PiperGuy 

No its not working

**Comment by laugustol** [comment]
did you solve in any other way?
T_T

**Comment by laugustol** [comment]
did you solve in any other way? @PiperGuy

**Comment by PiperGuy** [comment]
I am sill looking for a solution! If i find anything i will post it here

**Comment by laugustol** [comment]
help me please T_T @PiperGuy

**Comment by jaydenseric** [comment]
Please only comment on GitHub issues if you have information that can help the community; begging for help with your project is bad etiquette.
