### ISSUE TITLE
React Native: Failed to execute 'append' on 'FormData': parameter 2 is not of type 'Blob'. at new ApolloError

### ISSUE THREAD

**Issue by PiperGuy** [jaydenseric/apollo-upload-client#188]
Hi, I am trying to upload images from my react native app to graphql by using Apollo client with createUploadLink(). I am trying to mutate data by passing a ReactNativeFile as a variable, then it says

`network request failed: Failed to execute 'append' on 'FormData': parameter 2 is not of type 'Blob'. at new ApolloError`

This this the mutation which i am trying to use

```
 mutation publishPost(
    $content: String!
    $LocationInput: LocationInput!
    $InputPostAttachment: [InputPostAttachment!]
  ) {
  publishPost(
    content: $content
    location: $LocationInput
    attachments: $InputPostAttachment
  ) { 
      content
     }
  }
```

InputPostAttachment has type

```
type InputPostAttachment {
   type: PostAttachmentType!
   file: Upload!
}
```

Apollo client settings, I am using apollo-upload-client

```
const httpLink = createUploadLink({
  uri: 'http://localhost:8000/graphql',
});

const authLink = setContext(async (headers: any) => {
  const token = await getToken();
  return {
    ...headers,
    headers: {
      authorization: token ? `Bearer ${token}` : null,
    },
  };
});

const link = authLink.concat(httpLink);

// create an inmemory cache instance for caching graphql data
const cache = new InMemoryCache();

// instantiate apollo client with apollo link instance and cache instance
export const client = new ApolloClient({
  link,
  cache,
});
```

File upload Function and i am using react-native-image-crop-picker for multi image selection

```
const [image, setimage] = useState([]);

  const _pickImage = () => {
    ImagePicker.openPicker({
      includeBase64: true,
      multiple: true,
    }).then((images: any) => {
      let imageData: any = [];
      images.map((data: any) => {
        const file = new ReactNativeFile({
          uri: data.path,
          name: data.filename,
          type: data.mime,
        });
        imageData.push({
          type: 'IMAGE',
          file: file,
        });
      });
      setimage(imageData);
      console.log(images);
    });
  };

  const handlePost = async () => {

    const InputPostAttachment: any = [...image];

    const LocationInput = {
      place: place,
      vicinity: vicinity,
      province: province,
    };

    publishPost({variables: {content, LocationInput, InputPostAttachment}})
      .then(({data}) => {
        console.log(data);
        props.navigation.navigate('Home');
      })
      .catch((err) => {
        console.log('err happened');
        console.log(err);
      });
  };
```
Can anyone help me out to resolve this isuue? 

Thanks in advance.

**Comment by PiperGuy** [comment]
My apollo-client was configured using apollo-boost and i was using chrome debugger to intercept the network was causing me this issue. i have closed this issue. thanks.

**Comment by laugustol** [comment]
Hello, I changed my client from apollo-boost to apollo-client and I still have an error

Possible Unhandled Promise Rejection (id: 1):
Error: Network error: Network request failed

**Comment by m-inan** [comment]
> Hello, I changed my client from apollo-boost to apollo-client and I still have an error
> 
> Possible Unhandled Promise Rejection (id: 1):
> Error: Network error: Network request failed

Yes same error and i can't see the status code. and there is not going the back. Flipper output this way.

<img width="1096" alt="Screen Shot 2020-05-02 at 16 45 23" src="https://user-images.githubusercontent.com/25525515/80865836-74bfd980-8c94-11ea-8b2b-d1daa470989e.png">

**Comment by jaydenseric** [comment]
A reminder, just in case it's the issue some of you are experiencing:

https://github.com/jaydenseric/apollo-upload-client#type-reactnativefilesubstitute

> Be aware that inspecting network requests with Chrome dev tools interferes with the React Native `FormData` implementation, causing network errors.

**Comment by laugustol** [comment]
@PiperGuy 
I solved it,
you must tell this

android/app/src/debug/java/com/maxyride/app/drivers/ReactNativeFlipper.java

//builder.addNetworkInterceptor(new FlipperOkhttpInterceptor(networkFlipperPlugin));

comment line 43

its works!!!!!!

**Comment by PiperGuy** [comment]
@laugustol Thanks. it worked. @jaydenseric Since, React Native 0.62+ comes with flipper configuration it's hard to tell its chrome debugger which is intercepting the request. I will create a PR. Can this be informed on the DOCS?

**Comment by jaydenseric** [comment]
@PiperGuy here are the React Native release notes (Mar 27 2020, so fairly recent):

https://github.com/facebook/react-native/releases/tag/v0.62.0

> I will create a PR. Can this be informed on the DOCS?

Sure, we can add more detailed advice here:

https://github.com/jaydenseric/apollo-upload-client/blob/v13.0.0/src/index.js#L22

That JSDoc populates the readme docs here:

https://github.com/jaydenseric/apollo-upload-client/tree/v13.0.0#type-reactnativefilesubstitute

Keep in mind that the best place to fix this (either in code or docs) is really React Native as it's a pretty bad gotcha/bug with how they do things.

**Comment by PiperGuy** [comment]
@jaydenseric thanks. 
> Keep in mind that the best place to fix this (either in code or docs) is really React Native as it's a pretty bad gotcha/bug with how they do things.
I will create an issue there too. thanks
