### ISSUE TITLE
Data Url

### ISSUE THREAD

**Issue by berkaycimsir** [jaydenseric/apollo-upload-client#189]
How can i parse a data url that comes from canvas.toDataUrl(); for apollo-upload-client File format ?

**Comment by jaydenseric** [comment]
Use `HTMLCanvasElement.toBlob()` instead:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob

`Blob` instances can be used in variables for file uploads.

You can [construct a File instance](https://developer.mozilla.org/en-US/docs/Web/API/File/File), but you probably only need a `Blob`.

**Comment by berkaycimsir** [comment]
> Use `HTMLCanvasElement.toBlob()` instead:
> 
> https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob
> 
> `Blob` instances can be used in variables for file uploads.
> 
> You can [construct a File instance](https://developer.mozilla.org/en-US/docs/Web/API/File/File), but you probably only need a `Blob`.

![Ekran Alıntısı](https://user-images.githubusercontent.com/47090177/79070761-87bc3b00-7ce0-11ea-99a4-3136c61878b2.JPG)
![Ekran Alıntısı1](https://user-images.githubusercontent.com/47090177/79070762-88ed6800-7ce0-11ea-9a23-c51b1b5bc552.JPG)
![Ekran Alıntısı2](https://user-images.githubusercontent.com/47090177/79070763-8985fe80-7ce0-11ea-9d81-d3ae9c224e89.JPG)

When i want to access to the filename of file, it's give me an undefined. If i console this file and await file , it comes both undefined.

**Comment by berkaycimsir** [comment]
> > Use `HTMLCanvasElement.toBlob()` instead:
> > https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob
> > `Blob` instances can be used in variables for file uploads.
> > You can [construct a File instance](https://developer.mozilla.org/en-US/docs/Web/API/File/File), but you probably only need a `Blob`.
> 
> ![Ekran Alıntısı](https://user-images.githubusercontent.com/47090177/79070761-87bc3b00-7ce0-11ea-99a4-3136c61878b2.JPG)
> ![Ekran Alıntısı1](https://user-images.githubusercontent.com/47090177/79070762-88ed6800-7ce0-11ea-9a23-c51b1b5bc552.JPG)
> ![Ekran Alıntısı2](https://user-images.githubusercontent.com/47090177/79070763-8985fe80-7ce0-11ea-9d81-d3ae9c224e89.JPG)
> 
> When i want to access to the filename of file, it's give me an undefined. If i console this file and await file , it comes both undefined.

![Ekran Alıntısı4](https://user-images.githubusercontent.com/47090177/79070889-1f218e00-7ce1-11ea-9963-ddd50f8b2709.JPG)
I also tried this but it gives me the same error

**Comment by berkaycimsir** [comment]
I am doing same things in other mutations but this mutations takes file from type="file" input, i think we can't convert a dataUrl to the same format that type="file" input has

**Comment by jaydenseric** [comment]
One of the main differences between a `File` and a `Blob` is that a `Blob` doesn't have a file name by default. You can add a file name to a `Blob`, like in [the readme example](https://github.com/jaydenseric/apollo-upload-client#blob):

```js
blob.name = 'something.png';
```

Or, if this feels hacky you can use the `Blob` to construct a `File`:

```js
const file = new File([blob], 'something.png', { 
  type: 'image/png'
})
```

You can learn more about constructing a `File` here:

https://developer.mozilla.org/en-US/docs/Web/API/File/File

**Comment by berkaycimsir** [comment]
I tried both of this but still gives me the same error.

**Comment by jaydenseric** [comment]
It sounds like you are having a problem on the server then, not the client. You can confirm it's a server issue by using the Chrome network inspector tab to check if the filename is in the GraphQL multipart request, it should look like this:

https://github.com/jaydenseric/graphql-multipart-request-spec#request-payload

**Comment by berkaycimsir** [comment]
![WhatsApp Image 2020-04-13 at 04 29 27 (1)](https://user-images.githubusercontent.com/47090177/79085031-9423b080-7d3f-11ea-9af0-ea98c1efb8fd.jpeg)

This is the payload which is working successfully on client and server.

![WhatsApp Image 2020-04-13 at 04 29 27](https://user-images.githubusercontent.com/47090177/79085047-a4d42680-7d3f-11ea-929f-1b713df470b4.jpeg)

And this is the payload which is not working correctly. 

`this.canvas.toBlob(async (blob) => {
      console.log(blob);

      const file = new File([blob], "signature.png", { type: "image/png" });

      this.props
        .setDocumentSignature({
          variables: {
            document_id: this.props.document_id,
            fileToSign: this.props.fileToSign,
            signedBy: this.props.fullName,
            file,
          },
        })
        .then(({ data }) => {
          console.log(data);
        });
    });`

and this is the code how i parse dataUrl for file.

**Comment by jaydenseric** [comment]
`apollo-upload-client` looks to be doing it's job correctly, so you need to do more debugging in your project to figure out what's going on.

Make sure your using the latest` graphql-upload` version on the server, you can check that by running `npm ls graphql-upload`.

Other than the `filename` being undefined on the resolved upload promise on the server, the upload works correctly?

**Comment by berkaycimsir** [comment]
i am not using graphql-upload on server ? But other uploads working correctly
