### ISSUE TITLE
Transform error

### ISSUE THREAD

**Issue by zackify** [jaydenseric/apollo-upload-client#19]
When importing this component, my app complains about stage-0 and the transform runtime babel plugin not being installed. This is due to the babel config being in the package.json, can we get this fixed?

**Comment by giautm** [comment]
Which platform are you use? Web or react-native?
On react-native, we need to install transformers, see it in [setup](https://github.com/jaydenseric/apollo-upload-client#setup)

**Comment by zackify** [comment]
Ah, my bad for doing this end of the day and skipping over that for RN. My bad!!

**Comment by zackify** [comment]
But why not add a .babelrc file and add it to .npmignore. That will fix the problem?

**Comment by jaydenseric** [comment]
@zackify I think I will end up doing just that in the next version, that way we can remove the caveat and make setup a little easier for RN users.

**Comment by jaydenseric** [comment]
@zackify reopening so you can "fix" it via your pull request and reference it in the change log.
