### ISSUE TITLE
error after installing apollo-upload-client

### ISSUE THREAD

**Issue by andy-dev** [jaydenseric/apollo-upload-client#190]
Hello, 
After I installed the client I get an error running my react app. Removing the client removes the error. 

client file:
```
import { ApolloClient } from "apollo-client";
import { InMemoryCache } from "apollo-cache-inmemory";
import { HttpLink } from "apollo-link-http";
import { createUploadLink } from "apollo-upload-client";

const cache = new InMemoryCache();

const client = new ApolloClient({
  link: createUploadLink({ uri: "http://localhost:4000" }),
  cache
});

export default client;
```

Getting the following error

```
node_modules/extract-files/lib/index.mjs: Unknown browser Node
```

Looks to be regarding browserlist?

.babelrc
```
{
  "presets": [
    "@babel/preset-react",
    "@babel/preset-env",
    [
      "@emotion/babel-preset-css-prop",
      {
        "sourceMap": false
      }
    ]
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    [
      "@babel/plugin-transform-runtime",
      {
        "regenerator": true
      }
    ]
  ]
}
```

Node: v12.14.1
npm: 6.13.4
os: mac

Thanks

**Comment by jaydenseric** [comment]
That's a bit strange.

It probably relates somehow to here:

https://github.com/jaydenseric/extract-files/blob/v8.1.0/package.json#L45

Old browserslist versions don't support listing Node.js in the query. You can run `npm ls browserslist` to confirm the versions you have running. Updating your dependencies may solve the problem.

I don't know why your project has a tool running over `node_modules` though; perhaps you are transpiling your `node_modules` with `@babel/preset-env`?

**Comment by andy-dev** [comment]
Thanks for the response, I am using parcel. Pretty sure parcel running over the node modules might be wrong. 

I ran npm update and modified my browserlist to what you pointed out with no luck.
