### ISSUE TITLE
Somewhat irrelevant question: can I upload files without Apollo and React deps?

### ISSUE THREAD

**Issue by koresar** [jaydenseric/apollo-upload-client#191]
I was looking for a simple way to upload files to my GraphQL server but without involving Apollo toolchain. Also, I can't use https://github.com/jaydenseric/graphql-react because we don't use React.

I'm looking for a framework agnostic GraphQL upload client. Anyone knows if such exists?

**Comment by jaydenseric** [comment]
Often when I have the same need, I just make the [GraphQL multipart request](https://github.com/jaydenseric/graphql-multipart-request-spec) manually using vanilla [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData) and [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch):

https://github.com/jaydenseric/graphql-upload/blob/v10.0.0/test/lib/processRequest.test.js#L48

In a browser context, the `append` of the file will look a little different to the test linked above:

```diff
- body.append('1', 'a', { filename: 'a.txt' })
+ body.append('1', yourFileInstanceHere, optionalFileNameForBlobHere)
```

You can also see how [`graphql-react`](https://github.com/jaydenseric/graphql-react) itself puts together the fetch options for a multipart request:

https://github.com/jaydenseric/graphql-react/blob/v10.0.0/src/universal/graphqlFetchOptions.mjs#L24

Note that the [`GraphQL`](https://github.com/jaydenseric/graphql-react#class-graphql) client from [`graphql-react`](https://github.com/jaydenseric/graphql-react) is not React specific, there is no reason you couldn't import and use it as a lightweight (~1.5 KB?) client:

```js
import { GraphQL } from "graphql-react";

const file = _;
const graphql = new GraphQL();

const { cacheValuePromise } = graphql.operate({
  fetchOptionsOverride(options) {
    options.url = "https://api.example.com/graphql";
  },
  operation: {
    variables: { file },
    query: /* GraphQL */ `
      mutation($file: Upload!) {}
    `,
  },
});

cacheValuePromise.then(({ data }) => {});
```

If you prefer cURL over JavaScript, see the spec examples:

https://github.com/jaydenseric/graphql-multipart-request-spec#curl-request

**Comment by jaydenseric** [comment]
If there is demand, I can publish the [`GraphQL`](https://github.com/jaydenseric/graphql-react#class-graphql) client from [`graphql-react`](https://github.com/jaydenseric/graphql-react) separately, that way you don't have the extra React stuff in your `node_modules` or have to deal with missing React peer dependency warnings.

Maintaining two separate packages may increase the maintenance burden though, so I'll only consider it if people are interested.

**Comment by koresar** [comment]
This is awesome! I'll try using that `graphql.operate()` and see how I go.

There is literally zero vanilla GraphQL clients with file upload support. I had to bring the Apollo stack (which decreases SEO because too much JavaScript).

If you ever extract the client to a separate module consider adding it to this list: https://github.com/chentsulin/awesome-graphql#clients
(Btw, that list is missing `graphql-react` and `apollo-upload-client`.)

Thanks! And have a good day.
