### ISSUE TITLE
new ReactNativeFile Error: Network error: Network request failed

### ISSUE THREAD

**Issue by laugustol** [jaydenseric/apollo-upload-client#192]
I cannot upload images from the mobile application, I have integrated from the web and it works
![WhatsApp Image 2020-05-03 at 1 12 41 AM](https://user-images.githubusercontent.com/14079132/80894441-37cb0580-8cdb-11ea-907f-3a361014ba6c.jpeg)

**Comment by mrfsbDev** [comment]
@laugustol use version 12.1.0, is working with React Native, version 13.0.0 has a problem

**Comment by miriankakhidze** [comment]
@laugustol try to specify file type 
  const file = new ReactNativeFile({
          uri: uriFromCameraRoll,
          name: "picture.ext",
          type:"image/jpeg", // here, like this.
        });

**Comment by developerRojina** [comment]
I am still having this issue. Can anyone please clarify it

**Comment by miriankakhidze** [comment]
u must specify correctly file type. look around in wikipedia  . https://en.m.wikipedia.org/wiki/Media_type

**Comment by MCKmecik** [comment]
I am having same issue.  I have correctly defined uri,name and type in ReactNativeFile but always get "Network request failed" without reaching server.

**Comment by mkdas1001** [comment]
I am having the exact same issue. Has it been working before? I haven't tried earlier versions

**Comment by developerRojina** [comment]
@MCKmecik  @mkdas1001  Have a look at [this](https://github.com/facebook/react-native/issues/28551#issuecomment-611085378)
It solved my issue. The issue was with Flipper not with upload-client

**Comment by MCKmecik** [comment]
> @MCKmecik @mkdas1001 Have a look at [this](https://github.com/facebook/react-native/issues/28551#issuecomment-611085378)
> It solved my issue. The issue was with Flipper not with upload-client

Thank you so much. This solved the problem.

**Comment by jaydenseric** [comment]
It seems this problem has an answer, and updated documentation will make it easier for people to avoid such gotchas:

https://github.com/jaydenseric/apollo-upload-client/pull/193
