### ISSUE TITLE
ERR_CONNECTION_RESET from Chrome but files reach server

### ISSUE THREAD

**Issue by codelover2k** [jaydenseric/apollo-upload-client#195]
I am using **apollo-upload-client version 13.0.0**

When I upload more than 2 files I get no respond to my react app and after some seconds I get this in my Chrome console logged out:
`POST http://localhost:3003/graphql/ net::ERR_CONNECTION_RESET`

The behavior is very strange, because if I upload less than 3 files I get the successful response from the server.

It is not a server error because no matter how many files I pick, 2, 3, 15 or 20, all of the files reach the server and I can save them there.

Here some of my settings:
```javascript
const defaultOptions = {
  watchQuery: {
    fetchPolicy: 'no-cache',
  },
  query: {
    fetchPolicy: 'no-cache',
  },
};


const link = createUploadLink({
  uri: graphqlUrl,
  credentials: 'include',
});


const apolloClient = new ApolloClient({
  link,
  cache: new InMemoryCache(),
  defaultOptions,
});
```

**Comment by jaydenseric** [comment]
Promisify and await file upload streams in resolvers or the server will send a response to the client before uploads are complete, causing a disconnect.

**Comment by codelover2k** [comment]
Hi Jayden, thanks for quick respond!

I tested this on my server:
```javascript
// WHAT I HAD
const documentCreateResolver = async (parent, args, context, info) => {
  const { data } = args;
  console.log('CREATE DATA: ', data);

   return {
     message: "SUCCESS",
   };
});

// WHAT I TRIED
const documentCreateResolver = (parent, args, context, info) => {
  const { data } = args;
  console.log('CREATE DATA: ', data);

   return {
     message: "SUCCESS",
   };
});
```
As you can see there is no interaction with the model (that is promise heavy)
I still get the same error in both version :(

**Comment by jaydenseric** [comment]
Again, you need to promisify each upload stream and await the streams to finish, like in the examples:

https://github.com/jaydenseric/apollo-upload-examples/blob/c8ccfd2f49024873dab598aa8ac9c74ae17c3d34/api/server.js#L35

**Comment by codelover2k** [comment]
I am using apollo-server-express and I will try your solution today, but just for clarification:
My data looks like this:
```javascript
// documents
[ 
  { order: 0, fileBlob: [Promise] },
  { order: 1, fileBlob: [Promise] },
  { order: 2, fileBlob: [Promise] },
]
```
the fileBlobs contain a promise with the file stream and there is no problem consuming that.

What I do not understand is why I get this error, even if I just log the data and do not consume it at all ?

**Comment by jaydenseric** [comment]
You can promisify the streams and just waste them, but at the very least you need wait for them to all finish streaming into the server before returning your resolver. Otherwise, like I explained before, the server will rend a response back to the client before the client has finished streaming up it's request yet. At that point, you get network errors.

**Comment by codelover2k** [comment]
ohh now I get it!
so the client pushes the file streams to the server and the server gets that data and response right away, because there is nobody or nothing that tells the server to wait or when to response even if the client/browser is still streaming the files.

So the trick is to take these streams and promisify them.
Now we have promises that we can handle until they finish streaming and that is the moment where we tell the resolver that after the promisifyed streams are resolved and finished its allowed to answer the client. 

If we do not do that, the the stream from the client is still flowing to the server, but the resolver already returned a response that ends the connection that causes the CONNECTION error, because the client/browser is still streaming.

Thank you very much Jayden!
Now it makes sense and I learned something new 😁
