### ISSUE TITLE
Upload image from React Native to Apollo Server not working?

### ISSUE THREAD

**Issue by PritishSawant** [jaydenseric/apollo-upload-client#197]
This is not a bug with the library but a question from my side

I have created my backend with Nodejs and Apollo Server. I am trying to upload an image from my React Native client. Here is my backend code

```
Mutation: {
    async singleUpload(_, { fileInput: { file, fileName } }) {
      try {
        const { createReadStream, filename, mimetype } = await file;
        const stream = createReadStream();
        const path = `./upload/${filename}`;

        const tempFile = { id: 123, filename, mimetype, path };
        await new Promise((resolve, reject) => {
          const writeStream = createWriteStream(path);

          // When the upload is fully written, resolve the promise.
          writeStream.on("finish", resolve);

          // If there's an error writing the file, remove the partially written file
          // and reject the promise.
          writeStream.on("error", (error) => {
            unlink(path, () => {
              reject(error);
            });
          });

          // In node <= 13, errors are not automatically propagated between piped
          // streams. If there is an error receiving the upload, destroy the write
          // stream with the corresponding error.
          stream.on("error", (error) => writeStream.destroy(error));

          // Pipe the upload into the write stream.
          stream.pipe(writeStream);
        });
        ...then upload it to Firebase Storage
```

When I use Altair plugin for Firefox browser to upload image , it works fine.

Now for my React Native client, I am using apollo-upload-client lib. After a user picks image using the Image Picker plugin for React Native , I am creating a file

```
const file = new ReactNativeFile({
            uri: image.uri,
            type: image.type,
            name: 'Hi there',
          });
```

Now when I upload it I get an error saying from my backend saying TypeError: createReadStream is not a function which I understand as there is no createReadStream parameter in my ReactNativeFile

so I decided to change my backend code to something like this

```
const { name, type } = await file;
        console.log("Mime" + type);
        const stream = fs.createReadStream(name);
```

`fs module is from nodejs Now when I try uploading image from Altair or from React Native , I get an error saying`

`[Error: ENOENT: no such file or directory,`

Due to my lack of knowledge of backend I am not sure what is causing the issue. I think if I try uploading it from ReactJS instead of React Native, my code might work for the backend. But the image picker for browser and native mobile are very much different and I have not tried doing with ReactJS for now

I am following this article [moon highway](https://moonhighway.com/how-the-upload-scalar-works) for my backend code

**Comment by jaydenseric** [comment]
Sorry to hear you've been having a hard time with React Native; it is a real hassle to work with. I don't have time to answer usage questions about it, sorry.

The solution to your problems is most likely in one of the 28 issues mentioning "react native":

https://github.com/jaydenseric/apollo-upload-client/search?q=react+native&type=Issues

Please make not of this documented tip:

> Be aware that inspecting network requests with Chrome dev tools interferes with the React Native `FormData` implementation, causing network errors.

https://github.com/jaydenseric/apollo-upload-client#type-reactnativefilesubstitute

And have a read of this updated tip:

https://github.com/jaydenseric/apollo-upload-client/pull/193/files

Common gotchas a lot of React Native people have is not giving the right `name`, `uri`, or `type` when constructing a new `ReactNativeFile`.

**Comment by PritishSawant** [comment]
@jaydenseric  No issues. Thanks for the reply. May be for file upload I'll go with the rest api way for now till Graphql upload matures more in future

**Comment by jaydenseric** [comment]
@PritishSawant

> I'll go with the rest api way for now till Graphql upload matures more in future

You'll be waiting for React Native to fix their bugs and gotchas; nothing needs to change regarding this implementation of the [GraphQL multipart request spec](https://github.com/jaydenseric/graphql-multipart-request-spec), which uses web standard `FromData` and `fetch` requests. Some of their gotchas, like having dev tools open causing multipart requests to fail, will cause you problems regardless if you were uploading via GraphQL or REST.
