### ISSUE TITLE
question

### ISSUE THREAD

**Issue by smolleyes** [jaydenseric/apollo-upload-client#198]
hi

is it possible to get the v 5.1.1 (seems lastest with createNetworkInterface) client version of your package with apollo server 2.14 ?

don t have time to rewrite my app without redux cache so i stick to apollo v1.x...  :( and can t get apollo upload working, think i tried everything so is it just possible ? 

thanks

**Comment by smolleyes** [comment]
hi!

after 10 days i finally got everything working !!!!

i had a conflict on the web app server with my koabody parser (formidable/multipart) and the "map" field wasn t created on the upload client, i added it to your createNetworkInterface by comparing old and new code and made another server / endpoint specific to my mobile app with graphql-upload and koa middleware, no more conflicts :p

apollo is really boring for peoples like me who needs redux as state management (i love apollo, but i really don t like apollo local state...)

anyway, everything works perfect now with apollo-client 1.9 / redux  as client and v2 server side :)

thanks

**Comment by jaydenseric** [comment]
Thank for the update! Glad you got it working in the end :)
