### ISSUE TITLE
File ignored when Object of class

### ISSUE THREAD

**Issue by David-Wennemaring** [jaydenseric/apollo-upload-client#199]
I have a problem when uploading files when they are inside an object of a class.
I'm not sure if this is the correct location for this issue, or if it is related to vue-apollo.

When I do something like this in a mutation, the file is not sent in the request.
```ts
variables:{
  data: new FileWrapper(file)
}
```

When I do it like this, it is working as expected
```ts
variables: {
  data:{
    file
 }
}
```

Here is a stackblitz to reproduce the problem: https://stackblitz.com/edit/typescript-3j41bk
Checkout the content of the request in the network tab of the browser.

I hope you can help me.

**Comment by jaydenseric** [comment]
It's a pretty uncommon situation, to have a file wrapped like that. Probably the best option is to manually unwrap the file when constructing variables.

Another option is to specify the `isExtractableFile` option when using `createUploadLink`. Here is an example: 

https://github.com/jaydenseric/apollo-upload-client#type-extractablefilematcher

Note that once you get the file to extract ok, the global `FormData` implementation still needs to be able to append that type of file to the form. Try it out and see if it works, I'm not sure what will happen.

**Comment by jaydenseric** [comment]
After looking at your code demo, I think your best option is to manually unwrap:

```js
const wrappedFile = new FileWrapper(file)
const variables = {
  data: wrappedFile.file
};
```

**Comment by David-Wennemaring** [comment]
In this demo I agree, that it would be easy to unwrap the Object.
However in the application I'm building the Object is bigger and the file is nested deep in this Object.
Additionally I don't have the possibility to change the API and move the position of the file to the top.

I had a look at your suggestion. This did not work for me, but it made me look a little bit deeper into the sourcecode.
It seems like the `isExtractableFile` is not getting called for the nested attributes of my object. This is due to this piece of code in the "extract-files" repo. ([extractFiles.js](https://github.com/jaydenseric/extract-files/blob/master/src/lib/extractFiles.js) | line 93):
```ts
else if (value && value.constructor === Object) {
```
This statement returns false for all Objects which were created via `new AnyClass()`.
I think changing it to instanceof or similar would fix my problem:
```ts
else if (value && value instanceof Object) {
```

**Comment by jaydenseric** [comment]
> However in the application I'm building the Object is bigger and the file is nested deep in this Object.
> Additionally I don't have the possibility to change the API and move the position of the file to the top.

It doesn't really matter how nested the file is, you can write your own helper function that converts the object into something suitable for GraphQL variables. It could be recursive if the structure is not predictable.

One way:

```js
const foo = {
  a: 'whatever',
  b: {
    a: 'whatever',
    b: new Special({
       a: 'whatever',
       b: new FileWrapper(file)
    })
  }
}
const variables = {
  ...foo,
  b: {
    ...foo.b,
    b: {
       a: foo.b.b.a,
       b: foo.b.b.b.file
    }
  }
}
```

**Comment by David-Wennemaring** [comment]
This would be possible, but add more complexity to the source code in my opinion.
Is there a drawback in using `instanceof` that I'm missing?

**Comment by jaydenseric** [comment]
If you have a suggestion for `extract-files`, please raise an issue in that repo:

https://github.com/jaydenseric/extract-files

Keep in mind it is fairly battle tested, and quite a bit of thought went into a lot of the JavaScript gotchas that exist:

https://github.com/jaydenseric/extract-files/blob/79815bf37652b10607ad1e8c9d82a6c988d0d139/src/test/lib/extractFiles.test.mjs#L6-L19

Perhaps better than an issue is to try implementing your suggestions and if it tests ok, raise a PR for discussion.

**Comment by David-Wennemaring** [comment]
ok, thanks for your feedback. I will have a look and raise a PR if the tests succeed.
