### ISSUE TITLE
BatchingNetworkInterface support?

### ISSUE THREAD

**Issue by SPAHI4** [jaydenseric/apollo-upload-client#2]

**Comment by jaydenseric** [comment]
Sorry for the late reply, for some reason I was not watching my own repo – must be a new Github default.

Batching support is totally on the way, but it might take a while for me to get to it. Feel free to give it a shot and submit a pull request, you can see the class that needs extending [here](https://github.com/apollographql/apollo-client/blob/master/src/transport/batchedNetworkInterface.ts).

**Comment by jaydenseric** [comment]
In preparation for adding another batched network interface, `createNetworkInterface` is now a named and not default export: [#4393f45](https://github.com/jaydenseric/apollo-upload-client/commit/4393f45fac549f84d057db6af139e317700167c8).
