### ISSUE TITLE
I want to use createUploadLink and httpLink together.

### ISSUE THREAD

**Issue by 2ujin** [jaydenseric/apollo-upload-client#200]
This is my code. 

```javascript
import { createUploadLink } from 'apollo-upload-client';
import { HttpLink } from 'apollo-angular-link-http';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { ApolloLink } from 'apollo-link';

export function createApollo(httpLink: HttpLink) {
    
    const httpsLink = httpLink.create({uri: 'http://localhost:8080/graphql'});
    const uploadLink = new createUploadLink({ uri: 'http://localhost:8080/graphql' });

    return {
        // link: uploadLink.concat(httpsLink),
        link: ApolloLink.from([uploadLink, httpsLink]),
        cache: new InMemoryCache(),
        defaultOptions:{
          watchQuery:{
            fetchPolicy:'no-cache',
            errorPloicy:'all'
          },
          query:{
            fetchPolicy:'no-cache',
            errorPloicy:'all'
          }
        }
      };
}
```

As the title suggests, I want to use createUploadLink and httpLink together.

 I try it.
`link: uploadLink.concat(httpsLink),`
`link: ApolloLink.from([uploadLink, httpsLink]),`

In addition to the two methods, I have tried all of the methods listed, but only one of them works.
I have to use both of them in my project. What should i do to solve this? Thank you for your help ㅠㅠ

**Comment by jaydenseric** [comment]
In the [readme setup instructions](https://github.com/jaydenseric/apollo-upload-client#setup):

> [Apollo Client](https://apollographql.com/docs/link/#apollo-client) can only have 1 “terminating” [Apollo Link](https://apollographql.com/docs/link) that sends the GraphQL requests; if one such as [`apollo-link-http`](https://apollographql.com/docs/link/links/http) is already setup, remove it.

If you need to have some sort of conditionality to use one of several terminating links, you can use `ApolloLink.split`, e.g. https://github.com/jaydenseric/apollo-upload-client/issues/34#issuecomment-638901324 .

**Comment by 2ujin** [comment]
Thank you so much 😃  I solved it thanks to you!!
```javascript
  const link = ApolloLink.split(
    operation => operation.getContext().hasUpload,
    uploadLink,
    httpLink.create({ uri })
  )
```
I wrote the code like this, and I solved!! Thx :)

**Comment by jm-chong** [comment]
```
const link = ApolloLink.split(
    operation => operation.getContext().hasUpload,
    uploadLink,
    httpLink.create({ uri })
  )
```

in order to check 'hasUpload' flag in context, you may need to set context when you query / mutate
```
apolloClient
      .mutate({
        mutation: UploadProfileImageDocument,
        variables: {
          imageFile
        },
        context: { hasUpload: true }
      })
```
