### ISSUE TITLE
Upload value invalid.

### ISSUE THREAD

**Issue by cr1979** [jaydenseric/apollo-upload-client#203]
Hey,
I stuck on this problem. I'll get this error:

    [GraphQL error]: Message: Variable "$file" got invalid value { uri: "file:///data/user/0/com.service4cloud/cache/DocumentPicker/80292191-7940-482a-ac0b-3c1ba4a58493.jpg", name: "file_example_JPG_100kB.jpg", type: "image/jpeg" }; Upload value invalid., Location: [object Object], Path: undefined
    [Network error]: ServerError: Response not successful: Received status code 400

My Apollo Client:

    ....
    const uploadLink: ApolloLink = apolloUploadClient.createUploadLink({
      uri: `http://192.168.0.17:3000/graphql`,
      credentials: 'include'
    });

    export const createApolloClient = () => {
      return new ApolloClient({
        link:
          from([
            onErrorLink,
            authMiddleware,
            splitLink,
            uploadLink
          ]),
        cache: new InMemoryCache()
      });
    }

My GraphQL:

    const UPLOAD_FILE = gql`
        mutation uploadFile($comment: String! $file: Upload) {
            uploadFile(comment: $comment file: $file) {
                filename
                encoding
                mimetype
            }
        }
    `;

My ApolloClient Mutation:

    const fileData = new ReactNativeFile({
        uri: serviceRequest.attachments[0].uri,
        name: serviceRequest.attachments[0].name,
        type: serviceRequest.attachments[0].mimeType,
     });

    const { data, errors } = yield apolloClient.mutate({
        mutation: UPLOAD_FILE,
             variables: {
                 comment: "Test upload",
                 file: fileData
              }
     });
    
I'm now using @sapkra fork for Apollo Client V3. I got the same error while I'm used apollo-upload-client for V2 on V3
Any idea what I'm doing wrong? I you need more information, let me know.

It's so important to fix this issue.

Thanks a lot.

**Comment by jaydenseric** [comment]
Are you sure that `file:///` `uri` is right? And should you be using [`ReactNativeFile`](https://github.com/jaydenseric/apollo-upload-client#class-reactnativefile)?

**Comment by cr1979** [comment]
@jaydenseric I'm using ReactNativeFile as shown above. The URI ist coming from the expo DocumentPicker.DocumentResult.
I hope the uri is still valid when I try do send the image. 

ReactNativeFile is from:
   import { ReactNativeFile } from 'apollo-upload-client';

Maybe this is important:
   WARN     [Error: You are calling concat on a terminating link, which will have no effect]

I'll get this error with uploadLink:
    const uploadLink: ApolloLink = apolloUploadClient.createUploadLink({
      uri: `http://192.168.0.17:3000/graphql`,
      credentials: 'include'
    });

    export const createApolloClient = () => {
      return new ApolloClient({
        link:
          from([
            onErrorLink,
            authMiddleware,
            splitLink,
            uploadLink   <-------
          ]),
        cache: new InMemoryCache()
      });
    }

Is there a way to send date without to have a uri. When I already have the data? I tried Blob already, but it's not working.

You think the error comes from ReactNativeFile? Or is it from uploadLink in ApolloClient? It's hard to figure out where the problem comes from.

Thanks a lot.

**Comment by cr1979** [comment]
Hey,
I now got an upload. That's good. It is the uploadLink problem. If I comment out all other links, then it is working.

    import { ApolloClient, HttpLink, ApolloLink, from, InMemoryCache, split } from '@apollo/client';
    import { getMainDefinition } from '@apollo/client/utilities';
    import { rootStoreInstance } from 'App';
    import { WebSocketLink } from '@apollo/link-ws';
    import { SERVER_URL } from 'react-native-dotenv';
    import { onError } from "@apollo/link-error";
    import { SubscriptionClient } from "subscriptions-transport-ws";
    import Toast from 'react-native-root-toast';
    import { StyleProp, ViewStyle } from 'react-native';
    import { globalStyles } from '@/styles/GlobalStyles';
    import theme from '@/Theme';
    import apolloUploadClient from 'apollo-upload-client'

    const getAuthorizationHeader = () => {
      const token = rootStoreInstance?.userStore?.token ?? null;
      if (token) {
        return {
          authorization: `Bearer ${token}`
        }
      }
      return null;
    }

    const client = new SubscriptionClient(`ws://192.168.0.10:3000/graphql`, {
      reconnect: true,
      lazy: true,
      connectionParams: async () => {
        return getAuthorizationHeader();
      }
    });

    const wsLink = new WebSocketLink(client);

    const httpLink = new HttpLink({
        uri: `http://10.100.100.17:3000/graphql`
    });

    const onErrorLink = onError(({ graphQLErrors, networkError, response }) => {

    let toastMessage: string = undefined;

    if (graphQLErrors) {
      graphQLErrors.map(({ message, locations, path }) => {
        toastMessage = message;
        console.log(
          `[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`,
        );
      })
    }

    if (networkError) {
      toastMessage = networkError.message;
      console.log(`[Network error]: ${networkError}`)
    };

    if (toastMessage) {
      // Add a Toast on screen.
       let toast = Toast.show(toastMessage, {
        duration: Toast.durations.LONG,
        position: Toast.positions.CENTER,
        shadow: true,
        animation: true,
        hideOnPress: true,
        delay: 0,
        containerStyle: globalStyles.toastContainer,
        backgroundColor: theme.colors.error
       });
     }
   });



    // The split function takes three parameters:
    //
    // * A function that's called for each operation to execute
    // * The Link to use for an operation if the function returns a "truthy" value
    // * The Link to use for an operation if the function returns a "falsy" value
    const splitLink = split(
      ({ query }) => {
        const definition = getMainDefinition(query);
        return (
          definition.kind === 'OperationDefinition' &&
          definition.operation === 'subscription'
        );
      },
      wsLink,
      httpLink,
    );

    const authMiddleware = new ApolloLink((operation, forward) => {
      // add the authorization to the headers
      operation.setContext(({ headers = {} }) => {
        return {
          headers: {
            ...headers,
            ...getAuthorizationHeader()
          }
        }
      });

      return forward(operation);
    })

    const uploadLink: ApolloLink = apolloUploadClient.createUploadLink({
      uri: `http://192.168.0.17:3000/graphql`,
      credentials: 'include'
    });

    export const createApolloClient = () => {
      return new ApolloClient({
        link:
          from([
            //onErrorLink,   <----- have to commend out, that the upload works
            //authMiddleware,   <----- have to commend out, that the upload works
            //splitLink,   <----- have to commend out, that the upload works
            uploadLink
          ]),
        cache: new InMemoryCache()
      });
    }

Error:

    [Error: You are calling concat on a terminating link, which will have no effect]

So this error is not from apollo-upload-client I think, or? @jaydenseric

**Comment by jaydenseric** [comment]
In the [readme setup instructions](https://github.com/jaydenseric/apollo-upload-client#setup):

> [Apollo Client](https://apollographql.com/docs/link/#apollo-client) can only have 1 “terminating” [Apollo Link](https://apollographql.com/docs/link) that sends the GraphQL requests; if one such as [`apollo-link-http`](https://apollographql.com/docs/link/links/http) is already setup, remove it.

You can't try to use the upload link after the `HttpLink`.

**Comment by cr1979** [comment]
@jaydenseric I'll give it a try. I currently removed the HttpLink and it is still working. I'll have to test the whole app later this week,

But a big thank you @jaydenseric @sapkra for supporting me. I really appreciate it. You saved my live 👍

**Comment by cr1979** [comment]
Just a question. Is it possible to send a blob content via react native? Just got it work with ReactNativeFile only. But you'll need a uri for that.

Thank you.

**Comment by rafinskipg** [comment]
I don't understand how can you use upload link, if in the readme it says to remove all the headers and stuff. Normal applications have headers for authentication, i am getting something wrong?

**Comment by jaydenseric** [comment]
@rafinskipg you should customise the URL, headers, etc. by using the `createUploadLink` options:

https://github.com/jaydenseric/apollo-upload-client#function-createuploadlink

If you set `uri` via the `ApolloClient` constructor, `ApolloClient` will not share that configuration with the Apollo Links you setup. You can see backstory about this limitation here:

https://github.com/jaydenseric/apollo-upload-client/pull/175#discussion_r454779682

**Comment by rafinskipg** [comment]
OK; i just followed all the posts , issues, stuff etc. The problem: I had installed graphql-upload on the serverside, meanwhile i had installed apollo-server-express (that already includes another version of graphql-upload as a dependency) this had this stupid error that the upload was invalid. 

I was going crazy over the client side because the server looked good, but actually was this.. 

Thanks @jaydenseric
