### ISSUE TITLE
Typescript error with @apollo/client v3

### ISSUE THREAD

**Issue by jordanoverbye** [jaydenseric/apollo-upload-client#206]
Hello,

I'm getting the following Typescript error: `Type 'ApolloLink' is missing the following properties from type 'ApolloLink': onError, setOnError  TS2739`

Below is a snippet of code I am using:

```ts
import { ApolloClient, InMemoryCache } from '@apollo/client';
import { createUploadLink } from 'apollo-upload-client';

export const apolloClient = new ApolloClient({
  link: createUploadLink({
    uri: '/api',
    credentials: 'same-origin',
  }),
  cache: new InMemoryCache(),
});
```

and I'm using the following package versions

```json
// package.json

"@apollo/client": "^3.0.2",
"@types/apollo-upload-client": "^8.1.3",
```

You can fix with the following code, although this is not an ideal solution:

```ts
export const apolloClient = new ApolloClient({
  link: (createUploadLink({
    uri: '/api',
    credentials: 'same-origin',
  }) as unknown) as ApolloLink,
  cache: new InMemoryCache(),
});
```

I think the types are using the older version of apollo-link https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/apollo-upload-client/index.d.ts

**Comment by jaydenseric** [comment]
Types are outside of this repo, so nothing to action here I'm afraid.

**Comment by Titozzz** [comment]
@jaydenseric Would you be interested in a PR to add them here ? In-package types are easier to maintain than @types ones. :)

**Comment by JamesMcMahon** [comment]
There is a PR up at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46191. It's not yet merged, but that may be the place to offer help.
