### ISSUE TITLE
`react` has to be installed

### ISSUE THREAD

**Issue by tcastelly** [jaydenseric/apollo-upload-client#207]
Since I updated to the last version `14.0.0` I have this error:
```
react in ./node_modules/@apollo/client/react/context/ApolloContext.js, ./node_modules/@apollo/client/react/context/ApolloConsumer.js and 6 others

To install it, you can run: npm install --save react
```

**Comment by lassesteffen** [comment]
Same for me, using it with Vue.JS and getting this problem now

**Comment by jaydenseric** [comment]
Where do you see that error, in the terminal after running `npm install`?

**Comment by lassesteffen** [comment]
Running `npm run build` for vue

**Comment by lassesteffen** [comment]
```
-  Building for production...
Starting type checking service...
Using 1 worker with 2048MB memory limit
 ERROR  Failed to compile with 8 errors5:21:31 AM

This dependency was not found:

* react in ./node_modules/@apollo/client/react/context/ApolloContext.js, ./node_modules/@apollo/client/react/context/ApolloProvider.js and 6 others
```

**Comment by tcastelly** [comment]
I did not specify sorry, I use VueJS too.

**Comment by jaydenseric** [comment]
This is probably a problem with `@apollo/client`, can you please raise an issue there? We don't require React in any way here; it was Apollo's decision to import React in their main `@apollo/client` index.

**Comment by jaydenseric** [comment]
I'll leave it open actually until we're sure. There are other deeper entry points we can use to import the Apollo Link related stuff, but they are provided in separate bundles which is not good as it will result in code duplication in your project bundle (see https://github.com/jaydenseric/apollo-upload-client/pull/175#issuecomment-658521851).

**Comment by tcastelly** [comment]
I created an issue here:
https://github.com/apollographql/apollo-client/issues/6650

**Comment by jaydenseric** [comment]
I've published a fix in [v14.0.1](https://github.com/jaydenseric/apollo-upload-client/releases/tag/v14.0.1). It might cause some peoples bundles to grow a bit, but supporting non React projects is more important.

**Comment by tcastelly** [comment]
Maybe this work around "cost less"?
https://github.com/apollographql/apollo-client/issues/6650#issuecomment-661583049

**Comment by darleikroth** [comment]
I had this problem when using the `apollo-link-timeout@2.0.1`. So, I did the downgrade to `1.4.1` version and the problem gone.
