### ISSUE TITLE
Plans to support websockets?

### ISSUE THREAD

**Issue by zackify** [jaydenseric/apollo-upload-client#21]
I'm not super familiar with apollo just yet, but I've been using https://github.com/apollographql/subscriptions-transport-ws#full-websocket-transport which is moving towards doing all requests over a websocket vs regular http requests. This library utilizes fetch, so it's not going to work when all queries over websocket is added. Any ideas on how to support this? I'm up for helping if someone points me in the right direction.

**Comment by jaydenseric** [comment]
This is a great question, and I don't know yet. Apollo is working on a brand new transport layer, [`apollo-fetcher`](https://github.com/apollographql/apollo-fetcher).

We will adapt here to whatever best practices emerge. The only reason we would deprecate is if Apollo or GraphQL itself offers a native way to move files around (without using Base64 encode – that works now).

Anyone else able to shed some light?

**Comment by jaydenseric** [comment]
I don't have any plans to support websockets, and together with the Apollo team all focus is on standardising multipart GraphQL requests.

If anyone has any cool ideas about websockets, feel free to necro this issue.

**Comment by georgyfarniev** [comment]
@jaydenseric hello. I wanted to use only websocket as transport for my apps, but found that multipart uploads isn't possible via websocket, as I understand. Or something changed now, in 2019?

**Comment by jaydenseric** [comment]
@georgyfarniev sorry I don't have much to offer as I haven't really researched uploading files over websockets. If you figured out a way I don't think it would have much to do with the GraphQL multipart request spec anyway, as that is for HTTP multipart POST requests.

**Comment by georgyfarniev** [comment]
@jaydenseric ok, thank you. I will probably end up with both transports or create separate rest api for managing file uploads.
