### ISSUE TITLE
Showing "Type 'ApolloLink' is missing the following properties from type 'ApolloLink': onError, setOnError" in newly released @apollo/client@version3.1.1 in TypeScript React

### ISSUE THREAD

**Issue by KRTirtho** [jaydenseric/apollo-upload-client#213]
In ApolloClient() constructor the link property is giving the following type error of 
```sh
Type 'ApolloLink' is missing the following properties from type 'ApolloLink': onError, setOnError
```
I don't know why causing this error. But I found a solution to get rid of the type error from a github thread (don't know the thread link).
```ts
const client = new ApolloClient({link: auth_link.concat((link as unknown) as ApolloLink) , cache, typeDefs, resolvers})
``` 

It fixes the following error of typechecking but it doesn't seem to be ideal. I'm actually concating the `createUploadLink()` with another `ApolloLink()`. 
Here's the code of my `index.tsx`

```tsx
import  {ApolloProvider, ApolloClient, InMemoryCache } from '@apollo/client';
import { typeDefs, resolvers } from './state/typeDefs';
import {from, ApolloLink} from "@apollo/client/core"
import { LOGIN_LOCAL, SIGNED_UP } from './schema/local/Query';
const link = createUploadLink({uri: "http://localhost:4000"})

const cache = new InMemoryCache()
//Auth checking link
const auth_link = new ApolloLink((operation, forward)=>{
  const refresh_token = localStorage.getItem("refresh_token"")
  const auth_token = localStorage.getItem("auth_token")
  operation.setContext({
    headers: {
      "Authorization": `Bearer ${auth_token}`,
      "Refresh": `Bearer ${refresh_token}`}
    })
    return forward(operation)
  })
                                                            // ! Temporary Type Check Fix
const client = new ApolloClient({link: auth_link.concat((link as unknown) as ApolloLink) , cache, typeDefs, resolvers})
//Local State initializing
cache.writeQuery({query: LOGIN_LOCAL, data: {loggedIn: false}})
cache.writeQuery({query: SIGNED_UP, data: {signedUp: false}})

ReactDOM.render(
  <ApolloProvider client={client}>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </ApolloProvider>,
  document.getElementById('root')
);
```

But it seems to work fine if I use a regular `createHttpLink()` in my `ApolloClient()` constructor.
Don't know what's happening. But please give me better a solution. I'm in a urgent need.

Thanks❤ for making this great package. Saves a lot of time.....

**Comment by jaydenseric** [comment]
Is your issue with TypeScript types? If so, they are maintained and published outside of this repo by Definitely Typed:

https://www.npmjs.com/package/@types/apollo-upload-client

Please problem solve TypeScript related issues there.

If it comes to light that something is incorrect in the JavaScript code in this repo here, we can reopen.

**Comment by KRTirtho** [comment]
Thanks for the info, I'll try to find a solution in the @types repo. 
Thanks again for this great package...

**Comment by david-wb** [comment]
I'm facing this exact issue. @KRTirtho Any luck?

**Comment by KRTirtho** [comment]
@david-wb, not yet fixed. But this issue isn't with Apollo-Upload-Client, its with the @types/apollo-upload-client. Actually it uses an older version of the ApolloLink. So some features are missing. But u can temporarily use it by using the following fix & that's what I'm doing right now:
```tsx
const link = createUploadLink({uri: "http://localhost:4000"})

const client = new ApolloClient({link:(link as unknown) as ApolloLink , cache, typeDefs, resolvers})
```   

This isn't ideal and rather should not use this approache for any sort of type definitions. Try to avoid this. But until the next definitely typed version of apollo-upload-client releases we have to keep it  in work something alternative mentioned above.

**Comment by pkongara-mn** [comment]
I tried const client = new ApolloClient( { link: (link as any), cache }); and it worked for me.
