### ISSUE TITLE
Incorporate Typescript types directly into this repo

### ISSUE THREAD

**Issue by JoshRobertson** [jaydenseric/apollo-upload-client#215]
This has been mentioned a couple times without a direct answer that I can see.

Would it be possible to define Typescript definitions for this package directly in this repo rather than over in DefinitelyTyped? It makes managing types much easier going forward.

**Comment by jaydenseric** [comment]
Duplicates about 4 other issues, please don't open more.

**Comment by JoshRobertson** [comment]
@jaydenseric no it doesn't. This isn't about current type errors, this is a request to move types into this repository instead of maintaining the type definitions on DefinitelyTyped.

**Comment by jaydenseric** [comment]
That has been discussed in past issue and PRs. As a policy I don't maintain TypeScript types in any published packages - that is best left to TypeScript community at [Definitely Typed](https://github.com/DefinitelyTyped/DefinitelyTyped). Maintaining types significantly increases the surface area of the project, is maintenance burden, and affects the semver of releases resulting in more major releases that inconvenience non TypeScript users.

If I shipped types here, whenever TypeScript users have issues (which is all the time; look at the number of type related issues that come up in popular TypeScript projects) a fix would be blocked by how quickly I can understand the problem, review a PR, merge, and release. Fixes for issues with types at Definitly Typed are not blocked by my availability.

The vast majority of the millions of packages published to npm don't contain TypeScript types; the burden is really on the TypeScript community to solve problems of their own creation.
