### ISSUE TITLE
TypeError: Failed to execute 'append' on 'FormData': parameter 2 is not of type 'Blob'.

### ISSUE THREAD

**Issue by georgii-ivanov** [jaydenseric/apollo-upload-client#216]
I receive this error during using react-native, apollo/client and ImagePicker package from expo.
Everything is updated to latest version.
Same works with input type="file" on web but doesn't work with expo web setup.

```
const ImagePicker: React.FunctionComponent<ImagePickerProps> = ({ onChangeImage }) => {
  const handlePickImage = async () => {
    const result = await ExpoImagePicker.launchCameraAsync({
      allowsEditing: true,
      aspect: [4, 3],
    });
  
    if (result.cancelled) {
      return;
    }
  
    onChangeImage(new ReactNativeFile({ uri: result.uri, type: 'image/jpeg', name: 'image.jpg' }));
  };

  return (
    <Button onPress={handlePickImage}>
      Choose Image
    </Button>
  );
};
```

In never sends any request as it stays on FE part.

MIME type and filename is valid for the file I'm testing.
URI is valid base64

**Comment by jaydenseric** [comment]
> URI is valid base64

I'm not familiar with this; the URI should be a file path.

**Comment by georgii-ivanov** [comment]
Ugh.. file path... but I need also expo web support. How can I achieve it in this case?

**Comment by jaydenseric** [comment]
> expo web support

I don't know what that is exactly, but if you are building something for web/browsers, just use the standard web APIs - [`File`](https://developer.mozilla.org/en-US/docs/Web/API/File), [`Blob`](https://developer.mozilla.org/en-US/docs/Web/API/Blob), etc.

**Comment by georgii-ivanov** [comment]
So I guess I can convert base64 into either blob or file object.
I just googled couple articles and I think I can do that easily...

Anyways you can think about doing this stuff out-of-box using ReactNativeFile object and analyzing it's either base64 or file path.

Thanks for the support! I think in this case we can close the issue

**Comment by jaydenseric** [comment]
Glad to help :)

**Comment by loureirorg** [comment]
To anyone uploading images on expo web (or **react-native web**), here's a working solution:

```js
/** Load image from camera/roll. */
const result = await ImagePicker.launchImageLibraryAsync({
  mediaTypes: ImagePicker.MediaTypeOptions.All,
  allowsEditing: true,
  quality: 1,
});

if (result.cancelled) {
  return;
}

/** web platform: blob. */
const convertBase64ToBlob = async (base64) => {
  const response = await fetch(base64);
  const blob = await response.blob();
  return blob;
};

/** android/ios platform: ReactNativeFile.*/
const createReactNativeFile = (uri) => {
  const file = new ReactNativeFile({
    uri,
    type: mime.lookup(uri) || 'image',
    name: `file-${Date.now()}`,
  });
  return file;
};

/** Use blob for web, ReactNativeFile otherwise. */
const file = Platform.OS === 'web'
  ? await convertBase64ToBlob(result.uri)
  : createReactNativeFile(result.uri);

/** Upload image with apollo. */
mutate({ variables: { file } });
```

The problem, as pointed out in previous comments, is specific to the web platform of react-native. 

In the web platform, _ImagePicker_ returns a **base64** value instead of a file path. This problem doesn't happen if the platform is Android or iOS, as _ImagePicker_ returns a file path, which is expected by _apollo-upload-client_.

The solution, as mentioned before, is to detect if the URI is base64 (which happens when the platform is "web"), and convert it to a blob.
