### ISSUE TITLE
Ios: ReactNative: Missing request token for request NSURLRequest

### ISSUE THREAD

**Issue by Tjerk-Haaye-Henricus** [jaydenseric/apollo-upload-client#220]
Hey there, 

i'm currently facing th issue, that i cant upload any images with apollo-upload-client. 

![IMG_7232](https://user-images.githubusercontent.com/44015586/90811761-74bc1600-e325-11ea-9daf-cc35ee4001bd.png)

**Comment by jaydenseric** [comment]
What makes you think this error is a bug in `apollo-upload-client`?

**Comment by tamhv** [comment]
me too, react-native 0.63.0

**Comment by Tjerk-Haaye-Henricus** [comment]
This should be a problem by RN itself. Try this my friend it helped me a lot :)

https://github.com/facebook/react-native/issues/29364#issuecomment-663005914
