### ISSUE TITLE
Add Apollo Client 3.x support

### ISSUE THREAD

**Issue by nomcopter** [jaydenseric/apollo-upload-client#223]
Right now using Apollo Client 3.x's `ApolloLink.from()` with `createUploadLink` fails to compile with: `error TS2345: Argument of type 'ApolloLink' is not assignable to parameter of type 'ApolloLink | RequestHandler | undefined'.
  Type 'ApolloLink' is missing the following properties from type 'ApolloLink': onError, setOnError`

**Comment by jaydenseric** [comment]
Is your problem with the TypeScript types maintained at Definitly Typed?

**Comment by jaydenseric** [comment]
Closing because in answer to the issue title, Apollo Client v3 is definitely supported:

https://github.com/jaydenseric/apollo-upload-client/blob/4c72c995756c3cc6db4b523f9c8a3158a42e9970/package.json#L52

**Comment by nomcopter** [comment]
Derp - yes! Thank you
