### ISSUE TITLE
When I run a long term mutation I get Network error: Failed to fetch and it loads 2 times

### ISSUE THREAD

**Issue by wililam444** [jaydenseric/apollo-upload-client#225]
I am working on the file upload structure. apollo-upload-client, graphql-upload, express-graphql, express libraries. However, after the file size grows, the mutation runs 2 times and I get the error "Error: Network error: Failed to fetch". I need your help.

My Client :
``` javascript
const fetchAdress = serverIP + "admin";
  const client = new ApolloClient({
    link: createUploadLink({
      uri: fetchAdress,
      credentials: 'same-origin',
      mode: 'same-origin',
      headers: {
        "x-access-token": localStorage.getItem("userToken"),
      },
      //fetch: typeof window === 'undefined' ? global.fetch : customFetch
    }),
    cache: new InMemoryCache({
      addTypename: false
    })
  })
```

My express-api : 
``` javascript
const app = express();
app.use(cors());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

app.use('/admin', async (request, response, next) => {
	await adminJwtVerify(request).then((res) => {
		request.data = {
			userID: res.userID
		}
		next();
	}).catch((res) => {
		response.send({
			message: res.message,
			code: res.code
		})
	})
},
	graphqlUploadExpress({ maxFileSize: 10000000, maxFiles: 10 }),
	GraphHTTP((request, response, graphQLParams) => ({
		schema: adminSchema,
		context: request.data,
		graphiql: true
	}))
);

app.listen(port, () => {
	//createSecretToken(await r.uuid());
	console.log('Server start on localhost:' + port);
});

app.use(timeout(7200))
```

**Comment by jaydenseric** [comment]
Can you please format the code examples with syntax highlighting in fenced code blocks, to make them more readable:

https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting

You can edit your issue as much as you like without sending email notifications to anyone, don't worry :)

In your server code, `app.use(timeout(7200))` looks suspicious. Also, it's good to check what your Apache/NGINX timeout and request size config is - it should be a little bit looser than the `graphql-upload` `maxFileSize` options, to make sure that the user will get the meaningful error raised by `graphql-upload` if it's exceeded.

In case of a timeout/network error, if you have [`RetryLink`](https://www.apollographql.com/docs/link/links/retry) setup it could cause the multiple mutations.

**Comment by wililam444** [comment]
> Hiç kimseye e-posta bildirimi göndermeden sorununuzu istediğiniz kadar düzenleyebilirsiniz, endişelenmeyin :)

Thanks for your feedback Sorry, I've made the edits you requested. I reviewed all the topics previously opened. That's why I'm not using rety links. The size of the file I'm trying to upload is 6 mb, so it doesn't get stuck in maxFileSize either. I am using Nginx on my server but my api is not linked to nginx. Do you think it would be a problem even if there was no connection?

**Comment by wililam444** [comment]
![nginx conf](https://user-images.githubusercontent.com/46619747/93727149-7433cb00-fbc2-11ea-9f02-6b30af6092f8.JPG)
The content of my nginx.conf file is like this

**Comment by jaydenseric** [comment]
I'm not very familiar with NGINX config files, sorry! You'll have to double check the details yourself.

The first step to investigating GraphQL file upload problems to figure out if it's a client or server problem. Use the Chrome network inspector to check the client is sending a valid [GraphQL multipart request](https://github.com/jaydenseric/graphql-multipart-request-spec#multipart-form-field-structure). If it is, the problem is likely the server.

When you say the mutation happens twice, are there two separate requests being sent by the client? If so, that is weird and I suggest focusing on figuring out why the client would do that.

**Comment by wililam444** [comment]
No, the mutation is initiated once, but in a way I don't understand, the mutation is sent to the server again before one ends.

**Comment by wililam444** [comment]
When I want to upload a file that is less than 5 mb on average, I can upload the file without any problem and do what I want. But when I try to get to the top, it starts to load at first, then it cuts off at about 60% and 70% and starts a load again, which fails. All of these events take an average of 3.30 minutes.

**Comment by wililam444** [comment]
When someone with high internet speed works in this process, they can upload without any problems. I guess he is making such a mistake because it exceeds 2 minutes. but I raised the express's 2-minute limit by saying 
```app.use(timeout(7200))```

**Comment by jaydenseric** [comment]
I don't know where that `timeout` middleware comes from, but probably that's your issue. `7200` is a weird number, does that mean only 7.2 seconds?

**Comment by wililam444** [comment]
I'm using [connect-timeout](https://www.npmjs.com/package/connect-timeout) . Means 7200 seconds

**Comment by jaydenseric** [comment]
Pretty sure it's milliseconds:

https://www.npmjs.com/package/connect-timeout#timeouttime-options

Regardless, I think that timeout middleware needs to be first; the Node.js timeout defaults need to be modified before the upload middleware runs, not after.

**Comment by wililam444** [comment]
I'm sorry I'll try and come back right now

**Comment by wililam444** [comment]
Hello again my code
```javascript
const app = express();
app.use(timeout(7200000));
app.use(cors());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

app.listen(port, () => {
	//createSecretToken(await r.uuid());
	console.log('Server start on localhost:' + port);
});
```
I changed this to this state, but it still requests 2 times  :/

**Comment by wililam444** [comment]
When I tested from a different browser today:
![new errors](https://user-images.githubusercontent.com/46619747/93774339-d542b980-fc29-11ea-9691-044b53cfc54f.JPG)
I got these errors

**Comment by jaydenseric** [comment]
Those CORS errors probably relate to your server setup/middleware.

I'm sorry you've been having a tough time getting it all setup properly, but I'm not really in a good position to help from afar and these comments cause a lot of email notifications to go out to people watching this repo.

Feel free to share here any solutions you come up with for the problems raised so far for future googlers, and if you manage to discover a specific `apollo-upload-client` bug (with minimal reproduction instructions) we can reopen this issue :)
