### ISSUE TITLE
Build error "Module '"../extract-files"' has no exported member 'isExtractableFile'."

### ISSUE THREAD

**Issue by karladler** [jaydenseric/apollo-upload-client#226]
When building I always get this error:

```sh
PATH/node_modules/@types/apollo-upload-client/index.d.ts(13,10):
13:10 Module '"../extract-files"' has no exported member 'isExtractableFile'.
    11 | import { ApolloLink } from '@apollo/client/core';
    12 | import { HttpOptions } from '@apollo/client/link/http';
  > 13 | import { isExtractableFile, ExtractableFile } from 'extract-files';
```

apollo-upload-client: version: '14.1.2',

**Comment by karladler** [comment]
oh missed, that this is actually only an error in the type definitions. Anyways would be great if it will be fixed soon.

**Comment by baohouse** [comment]
I found out in my yarn.lock file that it was resolving @types/extract-files to version 3 (it's now at version 8.1.0 as of this writing). I had to set the resolutions in my package.json to force apollo-upload-client to use the latest version, even though it uses a wildcard semver *
