### ISSUE TITLE
error when upload >= 1mb

### ISSUE THREAD

**Issue by zsbahtiar** [jaydenseric/apollo-upload-client#229]
Hi, im using this package with my react app. when upload file < 1mb is great but when upload file >= 1mb

found: Error: Origin -
not allowed by Access-Control-Allow-Origin.

notes:

- cors set is allow control allow origin * all method

thanks

**Comment by zsbahtiar** [comment]
done thaks

**Comment by jaydenseric** [comment]
I'm guessing something like this was your problem:

https://stackoverflow.com/questions/52971336/cors-problem-if-content-type-multipart-form-data#comment110473993_62338841

**Comment by zsbahtiar** [comment]
hi @jaydenseric thanks for respond on my issue, nothing problem on my config limit upload nginx
