### ISSUE TITLE
Can't compile in Webpack 5

### ISSUE THREAD

**Issue by dylang** [jaydenseric/apollo-upload-client#231]
Hi! `apollo-upload-client` is making calls into `extract-files` without the file extensions, which is breaking builds in Webpack 5. 

```
Module not found: Error: Can't resolve 'extract-files/public/ReactNativeFile' 
in 'node_modules/apollo-upload-client/public'

Module not found: Error: Can't resolve 'extract-files/public/extractFiles' 
in 'reporting-renovate/node_modules/apollo-upload-client/public'

Module not found: Error: Can't resolve 'extract-files/public/isExtractableFile' 
in 'node_modules/apollo-upload-client/public'
```

The fix seems to be to just include `.js` for all three `require` statements.

**Comment by jaydenseric** [comment]
Duplicates https://github.com/jaydenseric/apollo-upload-client/issues/230#issuecomment-709654375 .

This is a webpack bug; please see https://github.com/jaydenseric/extract-files/issues/15#issuecomment-709684603 .

**Comment by chooban** [comment]
Just for those who may also come across this issue, I posted it on the [webpack issues list](https://github.com/webpack/webpack/issues/11467#issuecomment-712099964) and was pointed at [this open issue](https://github.com/webpack/enhanced-resolve/issues/256).

In the meantime, I ended up adding a couple of lines to the webpack config in `resolve.alias`:

```
'extract-files/public/extractFiles':      require.resolve('extract-files/public/extractFiles'),
'extract-files/public/isExtractableFile': require.resolve('extract-files/public/isExtractableFile'),
```

There are probably other, better ways to fix it, but while we're waiting for the webpack issue to be fixed, this might get you further with your upgrade.

**Comment by pegiadise** [comment]
> Just for those who may also come across this issue, I posted it on the [webpack issues list](https://github.com/webpack/webpack/issues/11467#issuecomment-712099964) and was pointed at [this open issue](https://github.com/webpack/enhanced-resolve/issues/256).
> 
> In the meantime, I ended up adding a couple of lines to the webpack config in `resolve.alias`:
> 
> ```
> 'extract-files/public/extractFiles':      require.resolve('extract-files/public/extractFiles'),
> 'extract-files/public/isExtractableFile': require.resolve('extract-files/public/isExtractableFile'),
> ```
> 
> There are probably other, better ways to fix it, but while we're waiting for the webpack issue to be fixed, this might get you further with your upgrade.

`'extract-files/public/ReactNativeFile': require.resolve('extract-files/public/ReactNativeFile'),` was needed as an extra line for this workaround.

**Comment by robsilva** [comment]
> Just for those who may also come across this issue, I posted it on the [webpack issues list](https://github.com/webpack/webpack/issues/11467#issuecomment-712099964) and was pointed at [this open issue](https://github.com/webpack/enhanced-resolve/issues/256).
> 
> In the meantime, I ended up adding a couple of lines to the webpack config in `resolve.alias`:
> 
> ```
> 'extract-files/public/extractFiles':      require.resolve('extract-files/public/extractFiles'),
> 'extract-files/public/isExtractableFile': require.resolve('extract-files/public/isExtractableFile'),
> ```
> 
> There are probably other, better ways to fix it, but while we're waiting for the webpack issue to be fixed, this might get you further with your upgrade.

This didn't work for me for some reason with webpack 5.11.1. Which version of apollo-upload-client and extract-files are you using in your project?
