### ISSUE TITLE
Wrong multipart map

### ISSUE THREAD

**Issue by HarrisonHenri** [jaydenseric/apollo-upload-client#237]
## Description:

When I call the mutation the apollo-upload-client is sending this **Form Data**:

`operations: {"operationName":"SavePictures","variables":{"files":[null,null]},"query":"mutation SavePictures($files: [Upload]!) {\n  saveProductPictures(files: $files) {\n    success\n    error\n    __typename\n  }\n}\n"}
map: {"1":["variables.files.0","variables.files.1"]}
1: (binary)`

The right thing would not be to send something like (it’s like that in the other mutations along the project):

`operations: {"operationName":"SavePictures","variables":{"files":[null,null]},"query":"mutation SavePictures($files: [Upload]!) {\n  saveProductPictures(files: $files) {\n    success\n    error\n    __typename\n  }\n}\n"}
map: {"1":["variables.files.0"],"2":["variables.files.1"]}
1: (binary)
2: (binary)`

Is there any workaround for it? Am I possibly doing something wrong? Thank you in advance !

## Systems Info:

` "@apollo/client": "^3.0.2",
  "apollo-upload-client": "^14.1.2"`

**Comment by jaydenseric** [comment]
Sorry, I'm not following what the problem is? It appears that you are using the same file twice in the variables (which is fine to do), and it's constructing the GraphQL multipart request accordingly.

**Comment by HarrisonHenri** [comment]
Sorry @jaydenseric . In summary, the problem is that the apollo is sending only one binary instead of two.

**Comment by jaydenseric** [comment]
That's because your using the same file twice in variables. If you use two different files, then two files will be uploaded.

**Comment by HarrisonHenri** [comment]
That's strange. Maybe this happen'ss because I'm using the same instance of the object `File`?

**Comment by jaydenseric** [comment]
That's exactly right :)

**Comment by jaydenseric** [comment]
It's a good thing you only uploading the file once; you’re saving bandwidth. In the resolvers that single upload will be available in all the places you expect. Well, assuming you are using a quality [server implementation of the GraphQL multipart request spec](https://github.com/jaydenseric/graphql-multipart-request-spec#server), such as [`graphql-upload`](https://github.com/jaydenseric/graphql-upload).

**Comment by HarrisonHenri** [comment]
Ok. I'm uploading the file once, but, as was pointed out, I'm sending the same instance of the `File` twice.
