### ISSUE TITLE
React Native & `babel-preset-env`

### ISSUE THREAD

**Issue by colinramsay** [jaydenseric/apollo-upload-client#24]
Trying this out with RN and got the error:

> Couldn't find preset "env" relative to directory

Installing `babel-preset-env` fixes it but it seems like this should have been installed as a dependency and shouldn't be necessary for RN anyway?

**Comment by jaydenseric** [comment]
In the current version there is an explanation and workaround [in the readme](https://github.com/jaydenseric/apollo-upload-client/tree/v4.1.1#setup).

The good news is that we will publish a new version very soon with [some changes](https://github.com/jaydenseric/apollo-upload-client/pull/23) that will make this easier.

**Comment by colinramsay** [comment]
Ah thanks, missed that 😉
