### ISSUE TITLE
Last version with Apollo client v3 make duplicated query

### ISSUE THREAD

**Issue by pronovaso** [jaydenseric/apollo-upload-client#241]
Hi.

I use last version of Apollo client and apollo-upload-client and have some trouble.

In app in some cases makes duplicate query on network.

I must downgrade apollo-upload-client to version 14.0.0 and use InMemoryCache from old package and not from @apollo/client

I thinking taht this issue must be in @apollo/client but maybe here? In apollo-upload-client?

Thanks

**Comment by jaydenseric** [comment]
I just updated the dependencies of the [example project](https://github.com/jaydenseric/apollo-upload-examples) and tested uploads, and could not reproduce this issue. If you can provide minimum steps it takes to create a project to demonstrate the issue, we can reopen and investigate.
