### ISSUE TITLE
upload not working

### ISSUE THREAD

**Issue by AmadeusDeadDmytro** [jaydenseric/apollo-upload-client#242]
I have error "params.Body is required" in react-native

`const fileName = photo.uri.replace('file://', '').split('/');

                const file = new ReactNativeFile({
                    name: photo.fileName ? photo.fileName : fileName[fileName.length-1],
                    type: photo.type,
                    uri: Platform.OS === "android" ? photo.uri : photo.uri.replace("file://", "")
                });

                const result = await uploadFile({variables: {file}});

                const {
                    data: {
                        uploadFile: {source, success}
                    }
                } = result;`

Where is core problem?

**Comment by jaydenseric** [comment]
> Where is core problem?

I don't know.
