### ISSUE TITLE
React Native ignores Non-Ascii characters on filename

### ISSUE THREAD

**Issue by darron1217** [jaydenseric/apollo-upload-client#244]
Uploading file using this package works well on Web.

But on React Native, it keep ignores Non-Ascii characters on filename.

How can I send filename properly?
I created `ReactNativeFile` object like below
```
  const nativeFile = new ReactNativeFile({
    uri: file.url,
    type: file.mime,
    name: file.name,
  });
```
And pass it like
```
    variables: {
      file: nativeFile,
      info: {
        caption: file.caption,
        alternativeText: file.alternativeText,
      },
    },
```

`console.log(filename)` before upload
```
이름변경-2.jpg
```

after upload
```
-2.jpg
```

(Edit)
Server Log (nodejs with Koa)
```
  {
    filename: '-2.jpg',
    mimetype: 'image/jpeg',
    encoding: '7bit',
    createReadStream: [Function: createReadStream]
  }
```

**Comment by darron1217** [comment]
After some investigation, I found that this package sends both `json` and `file` types as part of `FormData`
![image](https://user-images.githubusercontent.com/8064923/103334334-3cd39500-4ab4-11eb-8490-e2e7fff061c7.png)

This is why it emits error when I try to set `charset=utf8;` to `Content-Type` header.

But I found the stackoverflow answer about setting various content type on each `_parts` of FormData.
https://stackoverflow.com/a/24535293

How about setting content type as `multipart/form-data;charset=utf8;` only on `ReactNativeFile` field?

**Comment by jaydenseric** [comment]
This is most likely a problem with the React Native `FormData` implementation and not `apollo-upload-client`; React Native has had bugs with special characters in filenames in the past:

https://github.com/jaydenseric/apollo-upload-client/issues/78#issuecomment-404708759

Also, it sounds silly, but in the past (not sure if it's completely fixed yet, maybe it is?) having certain dev tools open while testing file uploads would cause network errors.

Hope that helps!
