### ISSUE TITLE
Update Readme: mention to replace `HttpLink` with `createUploadLink`

### ISSUE THREAD

**Issue by bruvers** [jaydenseric/apollo-upload-client#247]
The current Readme mentions that any `HttpLink` links should be removed from ApolloClient. This makes it sound like blocking requirement for some even though `createUploadLink` can be used to do a similar job that `HttpLink` did.

I suggest to update the Readme and mention that `createUploadLink` has similar features as `HttpLink` and can in many cases replace it.

**Comment by jaydenseric** [comment]
Agreed.

The repo about text and [package description](https://github.com/jaydenseric/apollo-upload-client/blob/6dec8edc2bb1c97514e1577b84530922a40608bc/package.json#L4) says:

> A terminating Apollo Link for Apollo Client that allows FileList, File, Blob or ReactNativeFile instances within query or mutation variables and sends GraphQL multipart requests.

That sounds like it _only_ sends multipart requests. In reality it either sends normal GET/POST requests, or multipart requests when files are used in variables.

I'm really busy on other OSS work, but next time I do some maintenance here I'll improve the wording :)

**Comment by kkarpeev** [comment]
> 
> 
> The current Readme mentions that any `HttpLink` links should be removed from ApolloClient. This makes it sound like blocking requirement for some even though `createUploadLink` can be used to do a similar job that `HttpLink` did.

Hello!
I see it uses ApolloLink inside. Except it doesn't support setOnError or request (and other) options that Apollo Link supports.
@jaydenseric, please, add them to `createUploadLink`.

**Comment by jaydenseric** [comment]
Thanks for the input; this should be much clearer now in [v15](https://github.com/jaydenseric/apollo-upload-client/releases/tag/v15.0.0) 🚀
