### ISSUE TITLE
uri must be a string

### ISSUE THREAD

**Issue by NZainchkovskiy** [jaydenseric/apollo-upload-client#25]
After upgrading to version 5.0 I got an runtime error: "uri must be a string".
I can see in debugger that apollo client got object with uri, opts and batchInterval (instead of just uri string). There was no such error in version 4.0.3.
What I did wrong?
Thank you!

**Comment by jaydenseric** [comment]
So Apollo Client updated with a breaking change in the batched network interface, see https://github.com/jaydenseric/apollo-upload-client/issues/20.

To fix things for the new version mean breaking things for the old. Are you sure you're using the latest version of React Apollo and Apollo Client?

**Comment by NZainchkovskiy** [comment]
Thank youfor quick response!
It's really was an issue. I don't know why, but after installing apollo-angular I got apollo-client 1.4.2 version. Updating to 1.7.0 solved a problem. 
Sorry for bothering you.

**Comment by jaydenseric** [comment]
Cool!
