### ISSUE TITLE
ApolloLink type conflicts

### ISSUE THREAD

**Issue by tcastelly** [jaydenseric/apollo-upload-client#250]
Hello,

Maybe there is a conflict of types between `ApolloLink` from 'apollo-link' and `ApolloLink` from `apollo-client` or maybe I did something wrong :)

![image](https://user-images.githubusercontent.com/37597737/112325139-b80fa600-8cb3-11eb-803d-2888d4670212.png)

**Comment by RvanderLaan** [comment]
I just encountered the same after updating apollo related dependencies. I managed to solve it by installing `@apollo/client` at the same version as `apollo-upload-client` is using locally, which was 3.3.12 for me:
`yarn add @apollo/client@3.3.12`

**Comment by jaydenseric** [comment]
There are no TypeScript types hosted in this package; the types are managed at [Definitely Typed](https://github.com/DefinitelyTyped/DefinitelyTyped).
