### ISSUE TITLE
Empty object being sent to server

### ISSUE THREAD

**Issue by alex-r89** [jaydenseric/apollo-upload-client#256]
Hi there,

Before I start, I have seen [this](https://github.com/jaydenseric/graphql-upload/issues/73) issue , which seems to be similar however the issue I am facing appears to be on the client - hence posting this here.

I have been using `apollo-upload-client` now since September 2020 when version `14.1.2` release. This has been working perfectly in my application along side the following related packages across my front and backend:

`"@apollo/client": "3.2.5"`
` "graphql": "15.4.0"`
`"graphql-upload": "11.0.0",`
`"apollo-server-express": "2.19",`

The implementation of that on the frontend was as follows, using formiks `setFieldValue` on the `onChange` for an `input` tag:

```js
onChange={(event) => { props.setFieldValue('userPhoto', event.currentTarget.files[0]) }}
``` 
For context, this is the related set up in my apollo client:

```js
import { createUploadLink } from 'apollo-upload-client'

// Using createUploadLink and not new HttpLink as its required for file uploads
const httpLink = createUploadLink({
  uri: process.env.NODE_ENV === 'production' ? 'https://api.mydomain.comt' : 'http://test.mydomain.com:4000',
  credentials: 'include',
  headers: {
    Origin: 'https://mydomain.com'
  }
})
```

As mentioned, this set up was working perfectly and files were uploading correctly - and have been for months. I therefore dont think the issue I am now facing is down to the implementation of any specific package (unless implementation has changed based on the following).

Today I decided to update packages, updating `apollo-upload-client` to `14.1.3` and updating the above related packages to the following:
`"@apollo/client": "3.3.15"`
`"graphql": "15.5.0"`
`"graphql-upload": "11.0.0"` (No change)
`apollo-server-express: "2.23.0"`

When I now go to upload a file, the upload fails with this error:

`Variable "$input" got invalid value {} at "input.userPhoto"; Upload value invalid.`

I am not too sure if some dependancy is known to be incompatible and I should rollback, or if there is something else I am missing, or if there is a bug in this latest version?

To note, I tried changing the upload `onChange` event to use `event.target.files[0]`, which also resulted in this same error.

Thanks

**Comment by alex-r89** [comment]
I've managed to fix this, it was related to [this](https://www.apollographql.com/docs/apollo-server/data/file-uploads/#uploads-in-node-14-and-later). I think it was because of changes that happened to `apollo-server-express` in  `v2.21.0`.

Adding `uploads: false` to my ApolloServer constructor, and then followed the steps listed [here](https://github.com/jaydenseric/graphql-upload#function-graphqluploadexpress) to manually setup graphql-upload fixed it.

**Comment by jaydenseric** [comment]
Glad you got it going :)
