### ISSUE TITLE
iOS: uploaded image bigger than the original 

### ISSUE THREAD

**Issue by riccardonucleare** [jaydenseric/apollo-upload-client#260]
Hi,
We are experiencing an issue when uploading an image JPG with iOS with `apollo-upload-client`.
The image is taken from the gallery (original size is around 2.4 MB) and we compress it to around 500 kB. We upload it to server with a mutation where we use `graphql-upload` with middleware `graphqlUploadExpress` using `ReactNativeFile`. However, when we check the image on S3, the image is 2 MB. We tried with several images and the result is similar: uploaded image is bigger than the compressed one.
We tried to upload the image without the middleware using a plain POST request and in this case, the image was uploaded with the expected size (500 kB).
Interesting that we do not have the same problem with Android using the same code. Any suggestion for debugging it?

cf. https://github.com/jaydenseric/graphql-upload/issues/82

**Comment by jaydenseric** [comment]
Closing because the `apollo-upload-client` approach uses standard web platform APIs like `File`, `FormData` and `fetch` so I don't think your issues could relate to this particular package. Of course, if you end up finding the source of the problem and it's a bug here we can reopen.

**Comment by riccardonucleare** [comment]
I found the problem and solved with this: https://github.com/facebook/react-native/pull/31457

Thanks.
