### ISSUE TITLE
Next JS error when using createUploadLink

### ISSUE THREAD

**Issue by trecho26** [jaydenseric/apollo-upload-client#261]
# Next JS Error

When I try to use `createUploadLink` into my Apollo Client configuration it pops up this error
![image](https://user-images.githubusercontent.com/54923993/119551668-1e1db580-bd57-11eb-9b1d-003f14a7f9b0.png)

This is my Apollo Client Configuration
![image](https://user-images.githubusercontent.com/54923993/119551979-72c13080-bd57-11eb-81af-1284901e7ba2.png)

**fetch is imported from node-fetch**
![image](https://user-images.githubusercontent.com/54923993/119552168-a734ec80-bd57-11eb-8e14-fafd283c40ca.png)

**Comment by jaydenseric** [comment]
You probably need to update your dependencies. In `extract-files` [v10](https://github.com/jaydenseric/extract-files/releases/tag/v10.0.0) the package `exports` field public [subpath folder mapping](https://nodejs.org/api/packages.html#packages_subpath_folder_mappings) (deprecated by Node.js, and over time bundlers might start to ignore ignore it) was replaced with a [subpath pattern](https://nodejs.org/api/packages.html#packages_subpath_patterns).

**Comment by trecho26** [comment]
Which dependencies? I think I got all dependencies with the last updated version

**Comment by jaydenseric** [comment]
The relevant dependencies to check are updated in your project are `next`, and `apollo-upload-client`. You should delete your `package-lock.json` file every time you update dependencies in `package.json`, and do a fresh `npm install` to rebuild it. That way all the dependencies of dependencies are optimally deduped and up-to-date.

You can run `npm ls extract-files` to make sure there is only one version in your `node_modules`, and that it's the latest version. It's an important dependency of `apollo-upload-client`.

I just updated all the dependencies in the example Next.js app and tested it out to make sure, and everything works fine:

https://github.com/jaydenseric/apollo-upload-examples/tree/master/app

**Comment by jaydenseric** [comment]
Another thing to make sure of, is that your Node.js version is compatible with the versions declared to be supported in the package `engines.node` field:

https://github.com/jaydenseric/apollo-upload-client/blob/0f0b032c95b085ade3d46574215ed174027bd858/package.json#L43-L45

You should have seen npm install warnings if the version of Node.js is too old to be compatible, but sometimes people ignore warnings like that.

**Comment by trecho26** [comment]
You're completely right!! I delete my `package-lock.json` and also upload `@apollo/client` to the `3.3.19` version and it works! Thanks a lot for your time

**Comment by Gherciu** [comment]
@jaydenseric I know that this issue is clossed but I still have that problem even if FRESH installed all packages by deleting node_modules and package-lock file....
The problem is that when I'm runing `npm ls extract-files` it still shows that I have 2 different versions...but I don't understand why....because all dependencies are at the latest version.....
```
│ │ └─┬ graphql-request@3.4.0
│ │   └── extract-files@9.0.0 
│ └─┬ @graphql-tools/url-loader@6.10.1
│   └── extract-files@9.0.0 
└─┬ apollo-upload-client@16.0.0
  └── extract-files@11.0.0 
```
If someone have this problem pls help with a workaround(

**Comment by Gherciu** [comment]
The only solution here as I can see is to open PR's to other repos to update their dependencies XDDD
Managed to fix that by downgrading the version to 14.1.3
but I have another issue now related to apoll
`Error: You are calling concat on a terminating link, which will have no effect` think that version are not compatible with latest apollo/client

**Comment by Gherciu** [comment]
@jaydenseric I deleted all package dependents on extract-files and now I have this graph
```─┬ apollo-upload-client@16.0.0
  └── extract-files@11.0.0 
```
which means I have only one version which is good.........but I still get this error for some reason(((.....
P.S. I have node 14.11.0 tried that with node 16 the result is same

**Comment by MatheusAnciloto** [comment]
> @jaydenseric I deleted all package dependents on extract-files and now I have this graph
> 
> ```
> apollo-upload-client@16.0.0
>        └── extract-files@11.0.0 
> ```
> 
> which means I have only one version which is good.........but I still get this error for some reason(((..... P.S. I have node 14.11.0 tried that with node 16 the result is same

Did you manage to solve it?
