### ISSUE TITLE
Type 'ApolloLink' is not assignable to type 'ApolloLink | RequestHandler'.

### ISSUE THREAD

**Issue by joepuzzo** [jaydenseric/apollo-upload-client#265]
Im in the process of upgrading to the new Apollo client and I see this error

```
Type 'ApolloLink' is not assignable to type 'ApolloLink | RequestHandler'.
```

Is this a type error I can ignore? or has the interface changed?

**Comment by joepuzzo** [comment]
```js
import { from } from '@apollo/client';

link: from([
    onError(({ graphQLErrors, networkError }) => {
        //....... error stuff
    }),
    // authLink,
    createUploadLink({
      // ...link stuff
    }),
  ]),
```

**Comment by jaydenseric** [comment]
TypeScript types are maintained externally by DefinitelyTyped; if you are having TypeScript problems please raise an issue there.

**Comment by joepuzzo** [comment]
Ok let me ask a better question. Does this library work with the latest version of apollo client? If so I could care less about the type error.

**Comment by jaydenseric** [comment]
@joepuzzo 

https://github.com/jaydenseric/apollo-upload-client/blob/0b29b0f7a01561e9008880584c63fd94d25cd713/package.json#L47-L48

**Comment by joepuzzo** [comment]
Word Thanks
