### ISSUE TITLE
logo got invalid value {}; Upload value invalid

### ISSUE THREAD

**Issue by edw19** [jaydenseric/apollo-upload-client#266]
Im using nextjs apollo-upload-client but i got this error
![image](https://user-images.githubusercontent.com/47750859/125863556-b9f27db4-cf80-47f9-a73b-eb5212892d9f.png)

my config link

![image](https://user-images.githubusercontent.com/47750859/125863658-68da4622-b71a-444f-bcb5-9fd223676246.png)

**Comment by jaydenseric** [comment]
You should use the browser network inspector to check the GraphQL request `body` and check that the client is sending a valid GraphQL multipart request:

https://github.com/jaydenseric/graphql-multipart-request-spec#multipart-form-field-structure

If it is (at first glance your client code looks ok to me), then your server hasn't been setup correctly. There are a lot of issues relating to [`graphql-upload`](https://github.com/jaydenseric/graphql-upload) setup in Apollo Server you can read in Apollo's repo, as you need to disable their outdated upload support and then follow the [`graphql-upload`](https://github.com/jaydenseric/graphql-upload) setup instructions. If you think you have already done this, perhaps you setup the middleware correctly but didn't setup the GraphQL upload scalar; this can cause the `Upload value invalid` you're seeing.
