### ISSUE TITLE
[QUESTION] Implement a progress bar ?

### ISSUE THREAD

**Issue by cristiandley** [jaydenseric/apollo-upload-client#27]
I know this is not the correct place to post it. But ... how would be the starting path to implement a progress Bar ?. XMLHttpRequest.upload seems not to capture any package. 
 
Thanks :+1:

**Comment by jaydenseric** [comment]
It is currently impossible, have a read of [this comment thread](https://github.com/apollographql/apollo-fetch/pull/8#issuecomment-315270358) for an explanation.

Lots of modern web apps show spinners instead of a percentage for uploads in progress.

**Comment by savovs** [comment]
I thought fetch was supposed to be a better standard than XHR :D

**Comment by tim-soft** [comment]
You could emit the progress of an upload via a graphql subscription back to the front end

**Comment by dlerman2** [comment]
FWIW, I posted an only-slightly-hacky workaround that uses Axios instead of fetch at https://github.com/jaydenseric/apollo-upload-client/issues/88#issuecomment-434907278
