### ISSUE TITLE
Got 400 Bad Request when sending image file

### ISSUE THREAD

**Issue by tienthegainz** [jaydenseric/apollo-upload-client#270]
Hello, I am trying to upload my image file to server using graphQL.
Here is my code
```js
const CREATE_POST = gql`
  mutation CreatePost($title: String!, $imageFile: Upload, $content: String!, $category: Int!){
    createPost(createPostInput: {
      title: $title
      imageFile: $imageFile
      content: $content
      category_id: $category
    }){
      id
    }
  }
`;
...
const onSubmit = async (values: CreatePostInterface) => {
    console.log(values);
    try {
      await createPost({
        variables: {
          title: values.title,
          imageFile: values.image,
          content: values.content,
          category: values.category
        }
      });
    } catch (error) {
      console.log(error);
    }
  }
```

My `values.image` is an image file got from `event.target.files[0]` as following:
![Screenshot from 2021-08-30 09-42-52](https://user-images.githubusercontent.com/34891363/131277867-f951983d-6e09-418e-943d-1624e956fa08.png)
As I take a look at POST request the `imageFile` param is `null` and I got `400 Bad Request` when submitting with 
```json
{
 "message": "Variable \"$imageFile\" got invalid value {}; Upload value invalid."
}
```

**Comment by jaydenseric** [comment]
Are you sure `apollo-upload-client` is setup correctly? Check the browser network inspector and make sure the request being sent is a [GraphQL multipart request](https://github.com/jaydenseric/graphql-multipart-request-spec).

**Comment by tienthegainz** [comment]
My request is a multipart request. However, I found out my problem is with `graphql-upload` on `NestJS`, not on FE itself. If anyone come across this problem, you may want to checkout this [issue](https://github.com/nestjs/graphql/issues/901). Anw thanks @jaydenseric

**Comment by tomashlavac** [comment]
I had the same problem.
Try change `$imageFile: Upload` to `$image: Upload`
![image](https://github.com/jaydenseric/apollo-upload-client/assets/104761043/45930417-0cb0-49fe-b177-db2508046fc1)
