### ISSUE TITLE
createUploadLink Appends uri to Apollo Client base uri

### ISSUE THREAD

**Issue by kharithomas** [jaydenseric/apollo-upload-client#277]
First, apologies if this isn't the correct forum. But this seems to be a rather simple issue which I can't fix.

I have Apollo Server 3 (Apollo Server Express v.3.5.0) and Apollo Upload Client (v.16.0.0) installed. 

After following the relatively simple Apollo upload [tutorial](https://www.apollographql.com/docs/apollo-server/data/file-uploads/), I am facing an issue where the Apollo Client uri is appending the client host to the server link uri.

![img](https://user-images.githubusercontent.com/55037984/142577168-320ed939-6a52-4f5a-8f7a-46aaac7157c4.png)

My Graphql server is hosted at -> http://localhost:8080/api
My React client is hosted at -> http://localhost:3000

Previously, others had this issue ([#114](https://github.com/jaydenseric/apollo-upload-client/issues/114)) when using Apollo Boost. 

My client setup is very basic:

`const client = new ApolloClient({
  link: createUploadLink({
    uri: "http:/localhost:8080/api",
    credentials: "include"
  }),
  cache: new InMemoryCache()
});`

Not sure what the issue is but any pointers or tips are appreciated!

**Comment by jaydenseric** [comment]
Perhaps this solves your problem?

```diff
- uri: "http:/localhost:8080/api"
+ uri: "http://localhost:8080/api"
```

**Comment by kharithomas** [comment]
Thank you - this is the result of late-night coding sessions.
