### ISSUE TITLE
Upload Link ignoring `uri` setting

### ISSUE THREAD

**Issue by jorgev259** [jaydenseric/apollo-upload-client#278]
Im using Apollo Client on an alraedy working project (without upload client) and when adding upload-client it does all requests to /graphql instead of the configured endpoint.

```
import { ApolloClient, InMemoryCache } from '@apollo/client'
import { createUploadLink } from 'apollo-upload-client'

const isSSR = typeof window === 'undefined'
const isDev = process.env.NODE_ENV === 'development'
const localPort = isDev ? '3000' : '58991'
const baseUrl = process.env.GITHUB_ACTIONS ? 'https://domain.com' : (isSSR ? `http://localhost:${localPort}` : window.location.origin)

const client = new ApolloClient({
  cache: new InMemoryCache(),
  link: createUploadLink({ uri: `${baseUrl}/api/graphql` }),
  credentials: 'include',
  ssrMode: isSSR
})

export default client
```

**Comment by jaydenseric** [comment]
Per the setup instructions in the readme:

> Remove any `uri`, `credentials`, or `headers` options from the [`ApolloClient` constructor](https://apollographql.com/docs/react/api/core/ApolloClient/#the-apolloclient-constructor).
> — https://github.com/jaydenseric/apollo-upload-client/tree/v16.0.0#setup

Those options need to go in the [`createUploadLink`](https://github.com/jaydenseric/apollo-upload-client/tree/v16.0.0#function-createuploadlink) options.

Does that help?

**Comment by jorgev259** [comment]
Dumb me, thanks for the help.
