### ISSUE TITLE
How to handle different upload scenarios

### ISSUE THREAD

**Issue by yazer79** [jaydenseric/apollo-upload-client#283]
This is not a problem, just help or explanation needed about how uploads are best handled in graphql.
I have upload client / singleUpload apolloserver resolver, I feel lost after this basic step. I do not feel that uploading all files just in 1 directory is a good idea.
My question is, if I need multiple upload types in my app, how do I handle this? For example, uploading an avatar, a profile picture, ..etc
Do I do repeat a resolver (on server side) for each upload type? eg: avatarUpload resolver, pictureUpload resolver,... etc
Or there is some way to send more info about the "upload type or group / save directory" from client?
Or simply all uploads are saved in one directory?
Any ideas are welcome

**Comment by jaydenseric** [comment]
Treat user uploaded files in a similar way to user database content. They should be stored somewhere other than the GraphQL API server, which you want to be able to redeploy/discard/upgrade/etc. without worrying about losing user data.

You might be interested in this old comment on the topic: https://github.com/jaydenseric/graphql-upload/issues/251#issuecomment-862135269 .

I don't suggest having mutations named something like `uploadSingleFile` for uploaded every file for multiple uses; instead it should be `userCreate` and one of the arguments is `avatar` of `Upload` scalar type, etc.

Here is a realistic example from a real API to add an artwork that can have images, and later, to add, reorder, and delete artwork images:

<img width="429" alt="Screen Shot 2021-12-13 at 1 05 47 pm" src="https://user-images.githubusercontent.com/1754873/145741540-cf083ad5-b7d0-4d33-b7cc-ae9d81fcdade.png">
<img width="467" alt="Screen Shot 2021-12-13 at 1 05 32 pm" src="https://user-images.githubusercontent.com/1754873/145741550-e9177d79-f526-42b3-aa34-45e81af69119.png">

Notice how the naming convention allows mutations relating to the same things to sort together.

I make a few generic helpers like `storeS3Image` and `getImgixImageMeta` to make resolver code more DRY.
