### ISSUE TITLE
Not generating multi-part form data?

### ISSUE THREAD

**Issue by Xenovore** [jaydenseric/apollo-upload-client#284]
Hi, I'm trying to get apollo-upload-client to work with HotChocolate on the back-end. [HotChocolate](https://chillicream.com/docs/hotchocolate/server/files) expects the query to come in a multi-part form, but apollo-upload-client seems to only use JSON. Hope you can point to what I'm doing wrong here!

I create the Apollo client:
```
...
import { createUploadLink } from "apollo-upload-client";

const httpLink = createHttpLink( { uri: environment.SERVER_API_URL } );
const authLink = setContext(
	( _, { headers } ) =>
	{
		const user = localStorage.getItem( "user" );
		return addAuthToHeaders( user, headers );
	} );

const uploadLink = createUploadLink( { uri: environment.SERVER_API_URL } );

export const qdojoGqlClient = new ApolloClient(
	{
		link: ApolloLink.from( [authLink, httpLink, uploadLink] ),
		cache: new InMemoryCache(),
	});
```

Then in my input change handler:
```
const file: File = event.target.files[0];
const gqlUploadCsvFile = gql`
	mutation uploadCsvFileForImport( $file: Upload )
	{
		uploadCsvFileForImport( file: $file )
	}`;

const response = await gqlClient.mutate(
{
	mutation: gqlUploadCsvFile,
	variables: { "file": file }
} );
```

But checking in Fiddler shows that the request is just JSON, not multi-part form. (And yeah, server throws a 500 error.)

In Insomnia this multi-part request works with HotChocolate:
```
"operations": { "query": "mutation UploadCsvFileForImport( $file: Upload! ) { uploadCsvFileForImport( file: $file ) }", "variables": { "file": null }  }
"map": { "theFile": ["variables.file"] }
"theFile":  <the file to upload>
```

**Comment by jaydenseric** [comment]
> [Apollo Client](https://apollographql.com/docs/react) can only have 1 [terminating Apollo Link](https://apollographql.com/docs/react/api/link/introduction/#the-terminating-link) that sends the GraphQL requests; if one such as [`HttpLink`](https://apollographql.com/docs/react/api/link/apollo-link-http) is already setup, remove it.
> 
> Initialize the client with a [terminating Apollo Link](https://apollographql.com/docs/react/api/link/introduction/#the-terminating-link) using [`createUploadLink`](#function-createuploadlink).
>
> — https://github.com/jaydenseric/apollo-upload-client/tree/v17.0.0#installation

**Comment by Xenovore** [comment]
I've solved it with a different solution. Thanks though.
