### ISSUE TITLE
Type 'ApolloLink' is not assignable to type 'ApolloLink | RequestHandler'.

### ISSUE THREAD

**Issue by alexpuertasr** [jaydenseric/apollo-upload-client#285]
Updating to the version 3.5.8 of @apollo/client the ApolloLink generated with `createUploadLink` doesn't match the expected ApolloLink type used on `from`

Example: 

```
const httpLink = createUploadLink({
  uri: `${process.env.NEXT_PUBLIC_API}/graphql`,
  credentials: 'include',
});

const client = new ApolloClient({
  cache: new InMemoryCache(),
  link: from([authLink, httpLink]),
});
```

Here httpLink will trigger the following type error:
`Type 'ApolloLink' is not assignable to type 'ApolloLink | RequestHandler'`

**Comment by jaydenseric** [comment]
Did you install [`@types/apollo-upload-client`](https://www.npmjs.com/package/@types/apollo-upload-client)?

I've updated the vast majority of my packages to have built-in typescript types via JSDoc comments, and will eventually do so here too. I'm holding off on the last couple because it also involves a switch to pure ESM, and Apollo packages as well as `graphql` don't have a good story for that yet.

**Comment by alexpuertasr** [comment]
Yes I have installed the `@types/apollo-upload-client` v17.0.0

**Comment by franz-geiser** [comment]
Same for me, solved with
`const httpLink = createUploadLink({
  uri: `${process.env.NEXT_PUBLIC_API}/graphql`,
  credentials: 'include',
}) as unknown as ApolloLink`

**Comment by adrianescat** [comment]
Ok, the library is not working at all. I hate seeing very simple examples, as soon as you want to do a real app scenario nothing works. 
So I need to do multiple queries and mutations from multiple endpoints, so I need to use `split`, right?

```javascript
  const withToken = setContext((_, { headers }) => {
    const token = Auth.getToken()
    return {
      headers: {
        ...headers,
        auth: token ? `Bearer ${token}` : '',
      },
    }
  })

  const resetToken = onError(res => {
    if (res.graphQLErrors) {
      const [networkError] = res.graphQLErrors
      if (networkError && networkError.message === 'Unauthenticated!') {
        Auth.clearToken()
      }
    }
    if (res.networkError) console.warn(`Error: Cannot connect to API`)
  })

  const uploadLink = createUploadLink({ uri: `${publicRuntimeConfig ? publicRuntimeConfig.UPLOADER_API_URL : 
     ''}/graphql`, fetch })

  const client = new ApolloClient({
    link: from([authLink, errorLink, splitter, uploadLink]),
    cache: new InMemoryCache(),
    name: 'my-app',
    version: '1.0',
    queryDeduplication: false,
    connectToDevTools: process.env.NODE_ENV === 'development',
    defaultOptions: {
      watchQuery: {
        fetchPolicy: 'cache-and-network',
      },
    },
  })
```

So the `uploadLink` inside the `from()` is giving me an error:
`Type 'ApolloLink' is not assignable to type 'ApolloLink | RequestHandler'.`

If I change the `uploadLink` to this (@franz-geiser "solution"):
```javascript
const uploadLink = createUploadLink({
    uri: `${publicRuntimeConfig ? publicRuntimeConfig.UPLOADER_API_URL : ''}/graphql`,
    fetch,
  }) as unknown as ApolloLink
```

The error disappears, BUT I soon as I run the app, I get this in the console:

```bash
Error: You are calling concat on a terminating link, which will have no effect
    at new LinkError (.../node_modules/@apollo/client/link/core/core.cjs.js:22:28)
    at Function.ApolloLink.concat (.../node_modules/@apollo/client/link/core/core.cjs.js:65:47)
    at ApolloLink.concat (.../node_modules/@apollo/client/link/core/core.cjs.js:86:27)
    at .../node_modules/@apollo/client/link/core/core.cjs.js:39:68
    at Array.reduce (<anonymous>)
    at ApolloLink.from (.../node_modules/@apollo/client/link/core/core.cjs.js:39:34)
    at createApolloClient (webpack-internal:///./src/graphql/ClientGraphql.ts:123:28)
    at App (webpack-internal:///./pages/_app.tsx:32:56)
    at processChild (.../node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (.../node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5) {
  link: ApolloLink { request: [Function (anonymous)] }
```

**Comment by productdevbook** [comment]
some problem

**Comment by brettgrigsby** [comment]
Same. Looking at my lock file, it seems that the typing dependency points to an older version of `@apollo/client`, maybe that's the issue.

```
"@types/apollo-upload-client@17.0.0":
  version "17.0.0"
  resolved "https://registry.yarnpkg.com/@types/apollo-upload-client/-/apollo-upload-client-17.0.0.tgz#e9ae78c3c3f1a70b5724616c83f5af2ad902f1d0"
  integrity sha512-S1HUj9g+wn0fM29vLsnD87hTW2h2k/ELlTTJ+mUHTnF6oxmm46KkqxrzFPR7u2rQBjjSiKQEaXLqBn76s8bzBg==
  dependencies:
    "@apollo/client" "^3.0.0"
    "@types/extract-files" "*"
    graphql "14 - 16"
```

**Comment by abumalick** [comment]
It seems that these two types are not compatibles for some reason
```js
import {ApolloLink} from 'apollo-link'
import {ApolloLink} from "@apollo/client";
```

It is what is triggering the error for me.

I am using last version of all packages

```
"@apollo/client": "^3.6.2",
"apollo-upload-client": "^17.0.0",
"@types/apollo-upload-client": "^17.0.0",
```

**Comment by abumalick** [comment]
ok the issue is that I was using these two packages

```js
"apollo-link-context": "^1.0.20",
    "apollo-link-error": "^1.1.13",
```

setContext and onError are now part of @apollo/client package

```js
import {setContext} from "@apollo/client/link/context";
import {onError} from "@apollo/client/link/error";
```

Now I don't have typescript error, it is working without any hack

**Comment by zo-ly** [comment]
Same type error.

In my case, work well to the v3.5.10 of @apollo/client, but incompatible to the v3.6.5 of @apollo/client

**Comment by alexpuertasr** [comment]
I've made [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60639) to update the dependency of `@apollo/client` in `@types/apollo-upload-client` so the types will be sync

**Comment by jaydenseric** [comment]
@alexpuertasr if this change is all that is necessary to fix the problem, then it seems there isn't really an issue:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60639/files#diff-0d0b1d4f9d8da9e7246d2115ee91690b7804f3d3679c06d620469b448336b93aR4

All people need to do is generate a package lock file in their projects that installs fresher versions of all these related packages. One way is to delete `node_modules` and `package-lock.json`, then do a fresh `npm install`.

**Comment by wand2016** [comment]
use peerDependencies
