### ISSUE TITLE
POST body missing, invalid Content-Type, or JSON object has no keys.

### ISSUE THREAD

**Issue by felixlucien** [jaydenseric/apollo-upload-client#287]
Hi all,

we are having the issue that:

When sending our mutation request to our server (using apollo-server and graphql-upload)
we are getting the response:

`POST body missing, invalid Content-Type, or JSON object has no keys.`

The raw payload of the request is:
```
------WebKitFormBoundarykBlHimUE7rideFr1
Content-Disposition: form-data; name="operations"

{"variables":{"location_id":"PfYDAgUg6dvCfN45zsui","evse":{"capabilities":[],"connectors":[],"status":"UNKNOWN","images":null}},"query":"mutation ($location_id: String!, $evse: OCPIEVSEInput!) {\n  updateOfflineDevices(location_id: $location_id, evse: $evse)\n}\n"}
------WebKitFormBoundarykBlHimUE7rideFr1
Content-Disposition: form-data; name="map"

{"1":["variables.evse.images"]}
------WebKitFormBoundarykBlHimUE7rideFr1
Content-Disposition: form-data; name="1"; filename="download.png"
Content-Type: image/png


------WebKitFormBoundarykBlHimUE7rideFr1--
```

I suspect it has something to do with `"images":null` in our raw request.

The content type of the request is:
`multipart/form-data; boundary=----WebKitFormBoundarykBlHimUE7rideFr1`

If anyone has encountered something like this, advice would be greatly appreciated!

Cheers all.

**Comment by jaydenseric** [comment]
It sounds like the `graphql-upload` middleware isn't processing the multipart request before Apollo Server middleware runs. Please double check you installed `graphql-upload` correctly.

**Comment by felixlucien** [comment]
Hi all,

the graphql server was misconfigured, this was able to be fixed by supplying the appropriate middleware `app.use(apolloServer.getMiddlware())` in conjunction with `app.use(graphqlUploadExpress({ maxFileSize: 10000000, maxFiles: 10 }))`,
and using `apollo-server-express` instead of `apollo-server`
