### ISSUE TITLE
Which type should I give to a json file ?

### ISSUE THREAD

**Issue by adscud** [jaydenseric/apollo-upload-client#288]
Hello, I am trying to upload a json file, I didn't know which type should I set to `new ReactNativeFile`.

I get the file path with `fs` like: 

```ts
const path = `${RNFS?.CachesDirectoryPath}/contacts.json`
await RNFS.writeFile(path, JSON.stringify(array))
return path
```

Then, I give the path to my `ReactNativeFile`:

```ts
new ReactNativeFile({
    name: 'foo',
    uri: path,
    type: 'multipart/form-data', // 'text/json', 'application/json'
})
```

I have tried to use theses threes types without success: `text/json`, `application/json`, `multipart/form-data`

There is a specific type for JSON file, or it simply not possible ?

**Comment by jaydenseric** [comment]
I would imagine for a JSON file the right `type` is `application/json`, but the choice only matters to React Native; `apollo-upload-client` doesn't directly use the `type` for anything. React Native uses the "file" (their non-standard concept of a file expects those three properties) however it decides to. Maybe see if you can find a solution in the React Native docs or issues. If any React Native users can spot the problem feel free to drop tips here in a comment.
