### ISSUE TITLE
 ENOENT: no such file or directory, open 'apollo-upload-client/node_modules/extract-files/public/extractFiles'

### ISSUE THREAD

**Issue by gHashTag** [jaydenseric/apollo-upload-client#292]
**When trying to test the hook in a React Native mobile app, this error:**

Test suite failed to run

    ENOENT: no such file or directory, open 'node_modules/apollo-upload-client/node_modules/extract-files/public/extractFiles'

      at Runtime.readFile (node_modules/jest-runtime/build/index.js:2552:21)
      at Object.require (node_modules/apollo-upload-client/public/createUploadLink.js:18:20)

**Dependencies:**
- `"react": "17.0.2",`
- `"react-native": "0.68.2",`

DevDepends:
 - `"jest": "28.0.3",`
 - `"jest-fetch-mock": "^3.0.3",`
-  `"jest-junit": "13.2.0",`
- `"@testing-library/jest-native": "4.0.4",`
- `"@testing-library/react-hooks": "8.0.0",`
- `"@testing-library/react-native": "9.1.0",`

- `"react-test-renderer": "17.0.2",`
- `node version: 16.15.1`
- `npm  version: 8.11.0`
- `yarn version: 1.22.18`

### Relevant code or config:

```js
import { renderHook } from '@testing-library/react-hooks' 

function useTest() {
  return { res: true }
}

describe('useTest', () => {
  it('should render', () => {
    const { result } = renderHook(() => useTest())
  })
})
```

**Comment by jaydenseric** [comment]
This looks like a problem with some of the tools you are using, and not this library. I suggest figuring out which of your tools is playing up and raising an issue there.

**Comment by Robert-Christopher** [comment]
@gHashTag Any pointers on how you traced and solved this issue ? I am currently facing the exact sam error
