### ISSUE TITLE
Uploading Files returns uncaught promise error

### ISSUE THREAD

**Issue by EduardoBDonovan** [jaydenseric/apollo-upload-client#294]
![image](https://user-images.githubusercontent.com/76187972/178315478-884be36f-1485-4fe8-a04f-169736a94642.png)

![image](https://user-images.githubusercontent.com/76187972/178315559-725e7784-543a-473e-8ca7-895218763ee2.png)

![image](https://user-images.githubusercontent.com/76187972/178315606-8179272b-e1fd-49df-b204-43472e8c4aa7.png)

Cannot find the issue. I'm assuming its some syntax that I haven't found to be updated... or a bigger problem? Please advise

**Comment by jaydenseric** [comment]
The first thing to do is to see what the GraphQL response body contains; most likely it is an error message from the server that would be a good clue. You can use the browser network inspector to see.

**Comment by jaydenseric** [comment]
A week has passed; hopefully that means you were able to solve the problem in your project. If you are still having a problem, we can reopen this issue if you are able to provide minimal reproduction steps that indicates a bug in `apollo-upload-client`.
