### ISSUE TITLE
Escape character in the query

### ISSUE THREAD

**Issue by jith51** [jaydenseric/apollo-upload-client#300]
Hi,

When i use createUploadLink, apollo client send this request :
Parameters: {"operations"=>"{\\"operationName\\":\\"createOrUpdatePhysicalPackageClass\\",\\"variables\\":{\\"input\\":{\\"avatar\\":[{\\"file\\" .... **--> String**
Without or without file to upload :
Parameters: {"operationName"=>"createOrUpdatePhysicalPackageClass", "variables"=>{"input"=>{"avatar"=> **--> JSON**

The second one is ok for my server, the first one not.
How can i remove the backslash character when i use createUploadLink and send a JSON Object

"apollo-upload-client": "^17.0.0",

Best regards.
jerome

**Comment by jaydenseric** [comment]
I can't reproduce this with the example app and API…

Multipart request:

<img width="1059" alt="Screenshot 2023-04-05 at 8 36 28 am" src="https://user-images.githubusercontent.com/1754873/229937698-d8f3a15b-5646-447f-b604-9344a9b28b8a.png">

<img width="1066" alt="Screenshot 2023-04-05 at 8 38 37 am" src="https://user-images.githubusercontent.com/1754873/229937834-3019c8e5-22c4-4d53-8aa5-48c2345aef9b.png">

Regular JSON request:

<img width="967" alt="Screenshot 2023-04-05 at 8 36 54 am" src="https://user-images.githubusercontent.com/1754873/229937915-e55cb052-c85b-4eaa-a551-9e4244bab707.png">

<img width="1061" alt="Screenshot 2023-04-05 at 8 38 27 am" src="https://user-images.githubusercontent.com/1754873/229937927-e7cf2414-e67e-46bc-8fcc-adaffbc844d6.png">
