### ISSUE TITLE
Upload request have all time status 'pending' in network tab

### ISSUE THREAD

**Issue by Juliaxddd** [jaydenseric/apollo-upload-client#303]
Hey, i try to implement upload feature to my app, i tested uploading files with Altair client - all working.
For now when i try to send request in network tab i see all time "(pending)". 

![image](https://user-images.githubusercontent.com/104300715/217334497-5df14141-a741-454d-8278-ffae66e9dd6d.png)

![image](https://user-images.githubusercontent.com/104300715/217334607-4a6c2533-7ff6-4e79-813f-4b2ff22eaebe.png)

![image](https://user-images.githubusercontent.com/104300715/217335139-01ccaa37-b1b4-4e1b-9228-aa091d07cb2f.png)

![image](https://user-images.githubusercontent.com/104300715/217335174-08db8451-1c8d-46f2-a622-06e6beac7e66.png)

**Comment by jaydenseric** [comment]
In the GraphQL API resolvers, are you using the file upload streams?

**Comment by kengres** [comment]
@Juliaxddd 
This is happening on the server. I didn't understand the issue myself 🤔 , but I think it has all to do with the `file` sent to the server being a Promise with a `createReadStream` function.

I worked around it by simulating a stream in NodeJs and it worked. Another alternative is to upload the file to a server somewhere, but if you're like me, you want to test the file before that. 

Hence 🚀 :

```js
async function logChunks(readable) {
  for await (const chunk of readable) {
    console.log(chunk);
  }
}

// And in your mutation:

resolve: async (_, { file }, ctxt) => {
  try {
    const { createReadStream } = await file;
    await logChunks(createReadStream());
    return 'success'; // or whatever you want to return
  } catch (error: any) {
    throw error.message;
  }
}

**Comment by jaydenseric** [comment]
Closing due a lack of response; given other people don't seem to have the the same issue it's likely not due to something being wrong with `apollo-upload-client`. If that assumption is incorrect we can reopen and investigate further.
