### ISSUE TITLE
Create Update link does not work with Keystone next js 6 in storage local mode 

### ISSUE THREAD

**Issue by Eliya13h** [jaydenseric/apollo-upload-client#304]
Hi man,
at first thanks to you for create and solve the update problem in gql.
I use Keystonejs6 and @apollo/client3.7.9 
I config the apollo-upload-client as the mentioned in the doc and its work for Cloudinary Images.
but
when I use Keystone local storage 
I see this error:
GraphQLError: Variable "$image" of type "Upload" used in position expecting type "ImageFieldInput".
I hope Help me!!!!

**Comment by jaydenseric** [comment]
Hi @Eliya13h , thanks for the thanks :)

Sorry for the late response. I don't use Keystone so I can't offer you advice about how to use it; perhaps you will have better luck asking the Keystone community for help. If you find the answer (maybe you already have?) feel free to comment what the solution was in this issue in case it helps future googlers.
