### ISSUE TITLE
Request doesn't add multipart/form-data

### ISSUE THREAD

**Issue by Aranir** [jaydenseric/apollo-upload-client#31]
I tried to follow the example given in the readme.

The apollo mutation arrives at the server with the correct output, but the `apolloUploadExpress` method just passe on the request to the next middleware without processing it as the follwoing is always `true`:

```
!request.is('multipart/form-data')
```

I believe the client middleware `createNetworkInterface`, imported from 
```
import { createNetworkInterface } from 'apollo-upload-client
```

Doesn't seem to add the required `multipart/form-data` to the request.

Anything I might have missed?

Here is my code, I add a custom header for authentication. Might that be the issue?

```
const networkInterface = createNetworkInterface({
  uri: '/graphql',
});
networkInterface.use([{
  applyMiddleware(req, next) {
    if (!req.options.headers) {
      req.options.headers = {};  // Create the header object if needed.
    }
    // get the authentication token from local storage if it exists
    const token = localStorage.getItem('token');
    req.options.headers.authorization = Auth.getToken() ? `Bearer ${token}` : null;
    next();
  }
}]);




const client = new ApolloClient({
  networkInterface,
  dataIdFromObject: (o: any) => {
      return o.id
  }
});
```

**Comment by jaydenseric** [comment]
Hmmm, you should definitely be able to add custom headers. Do you know what `fetch` implementation is running?

**Comment by Aranir** [comment]
Ok I dug a little deeper.

The main problem was that the `file` which I receive from the `input` had no path.

I think it was due to my configuration setup and the hot reloading (not really sure). After completely restarting all is working.

Sorry for the trouble!

**Comment by jaydenseric** [comment]
Glad you could get it working in the end 🙂
