### ISSUE TITLE
Any plan on adding preflight ?

### ISSUE THREAD

**Issue by erwan-joly** [jaydenseric/apollo-upload-client#310]
Some servers started enforcing preflight for multipart request and that make this lib fail example:

https://github.com/ChilliCream/graphql-platform/blob/aaa0c432712b5c44dda45fd3b509ce068a03e4bb/src/HotChocolate/AspNetCore/src/AspNetCore/HttpMultipartMiddleware.cs#L45

I disabled the new option at the moment but I believe for security it would be a nice addition

**Comment by jaydenseric** [comment]
See this previous comment:

https://github.com/jaydenseric/apollo-upload-client/issues/293#issuecomment-1157161164

Apollo links can be used to set any headers based on the GraphQL operation that your particular GraphQL server requires.

See:

- https://www.apollographql.com/docs/react/networking/advanced-http-networking/#customizing-request-logic
- https://www.apollographql.com/docs/react/api/link/apollo-link-context

If your GraphQL server just needs a hard-codable header to be present on the request, and you are happy for all requests to get the same header, you could set that header in the [`createUploadLink`](https://github.com/jaydenseric/apollo-upload-client/tree/v17.0.0#function-createuploadlink) options, either using `options.headers` or `options.fetchOptions.headers`. You can see that being done in the example app:

https://github.com/jaydenseric/apollo-upload-examples/blob/a5da903448e31abaf718be6a21d13d253fc3983b/app/pages/_app.mjs#L35

I don't have plans to make this package by default automatically send headers specific to particular GraphQL servers; this GraphQL client can be used with any GraphQL server. It's up to users to configure their GraphQL client in the way their chosen GraphQL server requires.
