### ISSUE TITLE
Type of createUploadLink options.uri is incorrect

### ISSUE THREAD

**Issue by floriancargoet** [jaydenseric/apollo-upload-client#316]
The latest version of this package declares `options.uri` as a `string` but it previously accepted a function.
Since `createUploadLink()` simply passes `uri` to Apollo's `selectURI()`, I think the type should be as before: `string | UriFunction`.

**Comment by jaydenseric** [comment]
Working on the fix…

**Comment by jaydenseric** [comment]
Thanks @floriancargoet for the report; the fix has been published in [v18.0.1](https://github.com/jaydenseric/apollo-upload-client/releases/tag/v18.0.1) 🚀

**Comment by floriancargoet** [comment]
Great! Thanks
