### ISSUE TITLE
How to use client in node js test suite

### ISSUE THREAD

**Issue by dirkmc** [jaydenseric/apollo-upload-client#32]
I'd like to use this library from my node js test suite to test file uploading against my apollo server. I tried using `fs.createReadStream(...)` but extract-files expects `File` or `ReactNativeFile`. Is there something I can use in node js that is equivalent to `File` or `ReactNativeFile`?

**Comment by jaydenseric** [comment]
Short answer; it is untestable. The `File` API only exists in browsers and no suitable polyfill exists for the Node.js environment. Believe me I tried when making tests for [`apollo-fetch-upload`](https://www.npmjs.com/package/apollo-fetch-upload).

**Comment by Fonz001** [comment]
It's been a while, is there already a suitable polyfill available? Did you try it with: https://github.com/node-file-api/file-api ?

**Comment by schickling** [comment]
Yeah, I feel this topic should definitely be revisited. Testing this part of an API is super important.

**Comment by jaydenseric** [comment]
@schickling part of the challenge of testing browser functionality in Node.js is that `Blob`, `File`, `FileList`, `FormData`, and `fetch` global polyfills all need to be cross compatible. Detecting a `File` instance in variables for extraction is one thing, being able to [`FormData.append()` a `File` instance](https://developer.mozilla.org/en-US/docs/Web/API/FormData/append#append()_Parameters) is another.

It would be awesome if someone were to create a family of cross-compatible polyfills for these browser globals; then `apollo-upload-client` could be used on the server the same as the browser making tests easy.

**Comment by jure** [comment]
In case anyone stumbles upon this issue trying to test upload from Node.js, I'm happy with the workaround that `apollo-upload-server` itself is using, which is to use `form-data`: https://github.com/jaydenseric/apollo-upload-server/blob/master/src/test.mjs#L73-L83.

I know it's not the same as testing with `apollo-upload-client` itself, but it does the job for us and might do it for you too.

**Comment by jaydenseric** [comment]
It depends what you want to test. If you are testing your client handles uploads provided from the user on the front end, then you are in a pickle. But if you want to test your GraphQL API can handle uploads properly, then testing that in Node.js is easy! @jure is right, the `apollo-upload-server` tests are the best resource to look at for this. You just have to follow the [GraphQL multipart request spec](https://github.com/jaydenseric/graphql-multipart-request-spec); [you can even use cURL](https://github.com/jaydenseric/graphql-multipart-request-spec#curl-request).

**Comment by Fonz001** [comment]
We actually just finished implementing 10 tests all inspired by: https://github.com/jaydenseric/apollo-upload-server/blob/master/src/test.mjs#L73-L83

We are big fans of using `graphql-bindings` based of `apollo-upload-client` for testing our api, so we were a little disappointed that, that's not working just yet (neither did we have the time to make it work). However, writing the first succesful test only took about 2 hours, which is fine by us.

**Comment by ragnarkurmwunder** [comment]
Any update on how to test file upload with `apollo-upload-client`?

**Comment by Fonz001** [comment]
This works for us - 

`file` is a `Buffer`
`fileName` is a `string`
`uri` is a `string`

You'll be needing `node-fetch` and `form-data` (`npm`)

And this is TypeScript... So feel free to ignore the typings.

```
  const body = new FormData()
  body.append(
    'operations',
    JSON.stringify({
      variables: {
        file: null,
      },
      query: `mutation($file:Upload!){
        uploadFile(file:$file) {
          id
          createdAt
          updatedAt
          deletedAt
          notes
          originalName
          mimeType
          contentType
          location
        }
      }`,
    }),
  )
  body.append('map', JSON.stringify({ 0: ['variables.file'] }))
  body.append('0', file.toString(), { filename: fileName })

  // Upload the file
  const result = await fetch(uri, {
    method: 'POST',
    body: body
  })

  const jsonData = await result.json()

  return jsonData.data.uploadFile as File
```
