### ISSUE TITLE
latest version of the package failed to compile

### ISSUE THREAD

**Issue by Cavdy** [jaydenseric/apollo-upload-client#323]
Hello,
I installed the latest version of the package(18.0.1) but my project failed to compile, so I had to revert back to version(17.0.0)

the error message below
`Android Bundling failed 2616ms
Unable to resolve "apollo-upload-client" from "services/client.ts"
`

![MicrosoftTeams-image](https://github.com/jaydenseric/apollo-upload-client/assets/37126612/9e412824-0d07-4391-8b58-a1be4d829f3d)

**Comment by jaydenseric** [comment]
Hello, most likely you need to update your imports from `apollo-upload-client` to me deep imports, as per the v18 changelog entry major changes:

https://github.com/jaydenseric/apollo-upload-client/releases/tag/v18.0.0

> - Removed the package main index module; deep imports must be used. To migrate:
> 
>   ```diff
>   - import {
>   -   createUploadLink,
>   -   formDataAppendFile,
>   -   isExtractableFile
>   - } from "apollo-upload-client";
>   + import createUploadLink from "apollo-upload-client/createUploadLink.mjs";
>   + import formDataAppendFile from "apollo-upload-client/formDataAppendFile.mjs";
>   + import isExtractableFile from "apollo-upload-client/isExtractableFile.mjs";
>   ```

**Comment by Cavdy** [comment]
Thanks

**Comment by Cavdy** [comment]
In order for the new import to work for me, I had to add the below code to my `metro.config.js`

`defaultConfig.resolver.sourceExts.push('mjs');`
