### ISSUE TITLE
how to use version 18.0.0 with webpack and typescript

### ISSUE THREAD

**Issue by devkral** [jaydenseric/apollo-upload-client#325]
Can you please update the examples (in readme) and especially provide an upgrade guide for typescript and webpack users?

The way you propose in your release file doesn't work.

**Comment by devkral** [comment]
where do I find in the examples repo the uploadlink?

**Comment by jaydenseric** [comment]
> Can you please update the examples (in readme) and especially provide an upgrade guide for typescript and webpack users?

The readme already has a link to the examples project. The app has TypeScript type check script that runs just fine, and it's a Next.js/webpack project so we know for a fact the package builds just fine and the types are usable.

https://github.com/jaydenseric/apollo-upload-examples/blob/1ed805d97907c5de6bb13a6abfb52377ab0177ff/app/package.json#L59

There are migration instructions in the v18 changelog entry:

https://github.com/jaydenseric/apollo-upload-client/releases/tag/v18.0.0

The things you need to do to upgrade are universal no matter if you are using esbuild or webpack or vanilla ESM without a build step. I won't be making a special migration guide for your project.

> doesn't work

You need to specify the error message, etc. when raising a GitHub issue. Saying "doesn't work" isn't actionable. Regardless, I can't help everyone debug their projects or help them figure out problems with their project webpack config. I can only work on actionable bug reports about the code in this repo, or feature requests about the API I maintain here.

> where do I find in the examples repo the uploadlink?

https://github.com/jaydenseric/apollo-upload-examples/blob/1ed805d97907c5de6bb13a6abfb52377ab0177ff/app/pages/_app.mjs#L34-L39

Next time, please use GitHub's repo search functionality to find the code you are interested in.

**Comment by devkral** [comment]
Thanks first. I overlooked _app.mjs

 It is not a bug but a documentation request. The README completely lacks a section how to really set up the FileUploadLink and what parameters can be specified. You have to go to the examples and find the _app.mjs.
