### ISSUE TITLE
documentation update

### ISSUE THREAD

**Issue by devkral** [jaydenseric/apollo-upload-client#326]
Is there interest in a PR improving the README
especially documenting the parameters of your project, how to set it up and the 18 upgrade?

Note: I am not a native speaker.

**Comment by jaydenseric** [comment]
Hi, thanks for your interest in contributing to this project :)

Generally for documentation I prefer to word it myself, but it's good to have issues like https://github.com/jaydenseric/apollo-upload-client/issues/330 raised to consider.
