### ISSUE TITLE
Problem with Typescript

### ISSUE THREAD

**Issue by Redskinsjo** [jaydenseric/apollo-upload-client#329]
Hi , I get this error on build: 
```
Error: Debug Failure. Expected [object Object] === [object Object]. Parameter symbol already has a cached type which differs from newly assigned type
```

when i set the maxNodeModuleJsDepth: 10 as recommended to use the library

**Comment by jaydenseric** [comment]
Where is that error coming from? Is it a TypeScript type error, or a runtime error? It looks like a runtime error. What is the trace of the error? Is it coming from a module in this package?

**Comment by Redskinsjo** [comment]
Hi, thank you for your response.
It was a type error. I managed to use the createUploadLink by importing ‘apollo-upload-client/createUploadClient.js’.
