### ISSUE TITLE
How do you use ReactNativeFile in the latest version

### ISSUE THREAD

**Issue by Cavdy** [jaydenseric/apollo-upload-client#331]
Previously I used ReactNativeFile to create a new file but in the latest release, this method does not exist. What do you suggest?

`const file = new ReactNativeFile({
    uri: newImage,
    name: fileName,
    type: mime.lookup(newImage) || 'image',
  });`

**Comment by jaydenseric** [comment]
You can use the function `createUploadLink` option `isExtractableFile` to match values that represent files in React Native; you could try to sniff if it's an object with `uri`, `name`, `type` fields, or you could recreate the pattern I used to suggest with a custom class `ReactNativeFile` (perhaps copy the old code from here for that into your project) so you can just do an `instanceof` check.

https://github.com/jaydenseric/apollo-upload-client/blob/5e6d5c17861fbd9e2d84c8517fc29d5321be4cfc/createUploadLink.mjs#L41-L43

I want to forget about supporting React Native and focus only on environments that support standard web APIs, so while you should be able to get it going in React Native I'm not keen to figure it all out. Feel free though to share any code or patterns that worked for you here if you would like to help out other React Native users.

Facebook/Meta pushing open source package maintainers to figure out workarounds for the lack of support for web standard APIs like `File`, `Blob`, `FormData` was the wrong approach; once we work hard (for free) to maintain viable hacks and workarounds, it removes the incentive for Meta to be bothered to add support for these standard APIs to the benefit of the whole ecosystem and users.

**Comment by spyle23** [comment]
I got an issues with react native. When I upload files I still having error => ApolloError: Response not successful: Received status code 400

This is my apollo client instance:

function customIsExtractableFile(
  value: unknown
): value is ReactNativeFile {
  return value instanceof ReactNativeFile;
}

export const apolloClient = async (
  token?: string
): Promise<ApolloClient<NormalizedCacheObject>> => {
  const API_URI = process.env.EXPO_PUBLIC_API_URI;
  const API_URI_WS = process.env.EXPO_PUBLIC_URI_WS;

  const user = token ? token : (await AuthStorage.isAuth())?.token;
  const httpLink: HttpLink = new HttpLink({
    uri: API_URI,
    fetch,
    headers: {
      authorization: `Bearer ${user}`,
    },
  });

  const wsLink: GraphQLWsLink = new GraphQLWsLink(
    createClient({
      url: API_URI_WS as string,
      lazy: true,
      connectionParams: {
        authentication: `Bearer ${user}`,
      },
    })
  );

  const uploadLink = createUploadLink({
    uri: API_URI,
    fetch,
    headers: {
      authorization: `Bearer ${user}`,
    },
    isExtractableFile: customIsExtractableFile,
  });

  const splitLink = split(
    ({ query }) => {
      const definition = getMainDefinition(query);
      return (
        definition.kind === "OperationDefinition" &&
        definition.operation === "subscription"
      );
    },
    wsLink,
    httpLink
  );

  const link = ApolloLink.split(
    (operation) => {
      const definition = getMainDefinition(operation.query);
      return (
        definition.kind === "OperationDefinition" &&
        definition.operation === "mutation" &&
        !!definition.selectionSet?.selections.find(
          (selection) =>
            selection.kind === "Field" && selection.name.value === "upload"
        )
      );
    },
    uploadLink as any,
    splitLink
  );

  const client = new ApolloClient({
    link: link,
    cache: new InMemoryCache(),
  });

  return client;
};

**Comment by sashrika** [comment]
Here is a working code.

const httpOptions = {
        timeout: 15000,
        uri: GRAPHQL_SERVER_V1,
    };

    const authMiddleware = setContext((operation, { headers }) => {
        return getCredentials().then(data => {
          return {
            headers: {
              ...headers,
              authorization: `Bearer ${data?.accessToken}` || null,
            }
          };
        });
      });
      

    const singleLink = split(
        ({ query }) => {
            const definition = getMainDefinition(query);
            return (
                definition.kind === "OperationDefinition" &&
                definition.operation === "subscription"
            );
        },
        wssLink,
        split(
            operation => operation.getContext().hasUpload,
            from([authMiddleware, createUploadLink({ ...httpOptions, isExtractableFile: customIsExtractableFile })]),
            from([authMiddleware, httpLink])
        )
    );

function customIsExtractableFile(
    value: unknown
): value is ReactNativeFile {
    return value instanceof ReactNativeFile;
}

export class ReactNativeFile {
  uri: string;
  name: string;
  type: string;
  constructor({ uri, name, type }: { uri: string, name: string, type: string }) {
    this.uri = uri;
    this.name = name;
    this.type = type;
  }
}

**Comment by Silon** [comment]
https://github.com/jaydenseric/apollo-upload-client/issues/335#issuecomment-2161077901

**Comment by Tushant** [comment]
Can anyone help me what I am missing here because I am getting Received status code 400?

```javascript
import { ReactNativeFile } from "./utils";

function customIsExtractableFile(
  value
){
  console.log('instanceOfCheck##############', value instanceof ReactNativeFile)
  return value instanceof ReactNativeFile
}

const apiEndPoint = ExpoConstants.expoConfig?.hostUri
  ? ExpoConstants.expoConfig.hostUri.split(`:`).shift().concat(`:8000`)
  : "http://localhost:8000/graphql";

const wsClient = createClient({
  uri: `ws://${apiEndPoint}/graphql/`,
  connectionParams: async () => {
    const token = await getToken();
    return {
      Authorization: token ? `Bearer ${token}` : "",
      authToken: token ? `Bearer ${token}` : "",
    };
  },
});

const enhancedFetch = async (url, init) => {
  const token = await getToken();
  const userAgent = await ExpoConstants.getWebViewUserAgentAsync();
  return fetch(url, {
    ...init,
    headers: {
      ...init.headers,
      Authorization: token ? `Bearer ${token}` : "",
      "user-agent": userAgent,
    },
  }).then((response) => response);
};

const uploadLink = createUploadLink({
  uri: `http://${apiEndPoint}/graphql/`,
  fetch: enhancedFetch,
  isExtractableFile: customIsExtractableFile,
});

const hasSubscriptionOperation = ({ query }) => {
  const definition = getMainDefinition(query);
  return (
    definition.kind === "OperationDefinition" &&
    definition.operation === "subscription"
  );
};

const splitLink = typeof window !== 'undefined' && wsLink != null ? split(
  hasSubscriptionOperation,
  wsLink,
  uploadLink
  // authLink.concat(httpLink),
) : uploadLink;

const links = from([errorLink, splitLink]);

const client = new ApolloClient({
  link: links,
  cache,
});

export default client;
```

lib/utils.js

```javascript
export class ReactNativeFile {
  name;
  uri;
  type;
  constructor({ uri, name, type }) {
    this.uri = uri;
    this.name = name;
    this.type = type;
  }
}
```

```javascript
const handleBrandingSubmit = async () => {
    try {
     
      const brandId = await getToken("brandId");
      if (logoImage && brandId) {
        const file = await uriToFile(logoImage?.uri);
        const fileInstance = new ReactNativeFile({
          name: file.name,
          type: file.type,
          uri: logoImage?.uri
        })
        debugger
        const response = await uploadCompanyAvatar({
          variables: {
            companyId: decodeRelayGlobalID(brandId)?.id,
            image: fileInstance,
          },
        });
      }
      return true;
    } catch (error) {
      console.error("Error uploading avatar:", error);
      return false;
    }
  };
```
I get Error uploading avatar: [ApolloError: Response not successful: Received status code 400]
