### ISSUE TITLE
Failed to resolve entry for package "apollo-upload-client".

### ISSUE THREAD

**Issue by raja-OX** [jaydenseric/apollo-upload-client#333]
```ts
Failed to resolve entry for package "apollo-upload-client". The package may have incorrect main/module/exports specified in its package.json: Missing "." specifier in "apollo-upload-client" package
```

I am using vite react typescript when i use this package  i got above error from vite.

**Comment by dfalgout** [comment]
Same error but I'm using vite vue typescript project

**Comment by jaydenseric** [comment]
This is not something wrong with the `apollo-upload-client` package, which is in a valid and standard Node.js format.

I can think of two possibilities for you to investigate in your tooling/project:

1. Maybe you are not importing things from `apollo-upload-client` using the correct deep import paths.
2. Maybe something in your tooling is incorrectly expecting a package to have a main module, relating to the error message `Missing "." specifier in "apollo-upload-client" package`. Node.js/npm packages are not required to have a `.` main export in the package `exports` field, in fact for [optimal module design](https://jaydenseric.com/blog/optimal-javascript-module-design) it's an anti pattern to have a main entry point.
