### ISSUE TITLE
Broken compatibility with HotChocolate 13.2 ->

### ISSUE THREAD

**Issue by msironen** [jaydenseric/apollo-upload-client#337]
So this isn't your fault but ChilliCreams, but someone over there thought this was a good idea:

> Note 2: HTTP Header GraphQL-preflight: 1 is required since version 13.2 due to security reasons.

(https://chillicream.com/docs/hotchocolate/v13/server/files)

While still specifically naming apollo-upload-client as one of the clients that support this "spec" (which I guess doesn't include that teensy weensy header requirement they just came up with).

The fix/current workaround is to add:

             context: {
                    headers: {
                        "GraphQL-preflight" : "1"
                    }
                }

upload mutations.

**Comment by jaydenseric** [comment]
This package doesn't assume the type of GraphQL server it might be paired with, so out of the box it doesn't set any special headers specific to a particular server. It is up to the user to configure the headers for their given server; in the Apollo upload examples the header `Apollo-Require-Preflight` is used:

https://github.com/jaydenseric/apollo-upload-examples/blob/1ed805d97907c5de6bb13a6abfb52377ab0177ff/app/pages/_app.mjs#L37
