### ISSUE TITLE
Support with @habx/apollo-multi-endpoint-link

### ISSUE THREAD

**Issue by antonykovalenko** [jaydenseric/apollo-upload-client#340]
Hello there!

I'm having problem getting to work `apollo-upload-client` with `@habx/apollo-multi-endpoint-link`'s `multiApiLink`

My code look like this: 

```
const multiApiLink = new MultiAPILink({
  endpoints: {
    public: GQL_PUBLIC_URL,
    private: GQL_PRIVATE_URL,
  },
  createHttpLink: () => createHttpLink(),
  httpSuffix: '',
});

const link = from([
  errorLink,
  createUploadLink(),
  multiApiLink,
]);

const client = new ApolloClient({
  cache: new InMemoryCache(),
  link,
});
```

I tried various config parameters of `createUploadLink()` and `createHttpLink()` but nothing was successfull. Am I missing something here? Any ideas would help. Thank you in advance!

**Comment by jaydenseric** [comment]
Hi! The problem is because the upload link is intended to replace the normal HTTP link, but you have tried setting up both at once. In that situation whichever one comes first in the configured links "wins". As per the readme installation instructions:

> [Apollo Client](https://www.apollographql.com/docs/react) can only have 1 [terminating Apollo Link](https://www.apollographql.com/docs/react/api/link/introduction/#the-terminating-link) that sends the GraphQL requests; if one such as [`HttpLink`](https://www.apollographql.com/docs/react/api/link/apollo-link-http) is already setup, remove it.
> — https://github.com/jaydenseric/apollo-upload-client/blob/v18.0.1/readme.md#installation

I've never setup `MultiAPILink`, but maybe try this:

```diff
  const multiApiLink = new MultiAPILink({
    endpoints: {
      public: GQL_PUBLIC_URL,
      private: GQL_PRIVATE_URL,
    },
-   createHttpLink: () => createHttpLink(),
+   createHttpLink: () => createUploadLink(),
    httpSuffix: '',
  });
  
  const link = from([
    errorLink,
-   createUploadLink(),
    multiApiLink,
  ]);
  
  const client = new ApolloClient({
    cache: new InMemoryCache(),
    link,
  });
```

**Comment by antonykovalenko** [comment]
@jaydenseric thank you so much for explanation and solution. I tried it and it work perfectly!
