### ISSUE TITLE
Pending requests issue

### ISSUE THREAD

**Issue by moroale93** [jaydenseric/apollo-upload-client#342]
There is something not working on the upload link.
The requests are pending forever. 
<img width="394" alt="Screenshot 2024-02-21 at 09 12 54" src="https://github.com/jaydenseric/apollo-upload-client/assets/9401948/092e0737-e9aa-487d-b885-ca6dedc87997">
<img width="890" alt="Screenshot 2024-02-21 at 09 13 00" src="https://github.com/jaydenseric/apollo-upload-client/assets/9401948/cc3f3d96-e455-4b92-b496-4399fdb31912">
but if you copy the exact same cURL request from the network tab and paste it on e.g. PostMan (selecting the same file), the request it's working.
<img width="1108" alt="Screenshot 2024-02-21 at 09 13 20" src="https://github.com/jaydenseric/apollo-upload-client/assets/9401948/5806d2a5-fe69-4bf1-b8bf-a4800d2e8851">

I've added the example here:
https://github.com/moroale93/upload-gql

**Comment by jaydenseric** [comment]
In the past, there have been some issues with different dev tools, particularly for React Native conflicting with the Chrome network inspector. Just having the tools running or the inspector open could cause multipart requests to display as pending.

It's good that you have a reproduction in https://github.com/moroale93/upload-gql , but it's not minimal with a lock file close to 32k lines of code long:

https://github.com/moroale93/upload-gql/blob/main/package-lock.json

It's a security risk for me to install a project like that on my local machine without auditing all the dependencies.

I'll leave this issue open for a bit to give you a chance to isolate a specific problem with the `apollo-upload-client` code that I maintain in this repo, but as you can understand I don't have the availability to help people debug projects to figure out what is a bug or not, I can only action issues here that report specific bugs that have already been found. 9/10 times someone has something weird happening in their project it's a bug in their project code, not this library.

**Comment by jaydenseric** [comment]
As commented above, closing in the absence of a more minimal reproduction. In particular, it would be good if you are able to figure out how to reproduce your issue using a fork of the Apollo upload examples:

https://github.com/jaydenseric/apollo-upload-examples
