### ISSUE TITLE
Must provide query string

### ISSUE THREAD

**Issue by dChunikhin** [jaydenseric/apollo-upload-client#345]
my mutation is

```
mutation courseUpdate($input: CourseUpdateInput!) {
    courseUpdate(input: $input) {
        success
        errors
    }
}
```
CourseUpdateInput is ```{ courseId: String!, logo: Upload }```

When I send field it sets correct Content-Type: "multipart/form-data; boundary=----WebKitFormBoundaryybVbO8fQManknA6H"

And payload looks good:

```
operations: {"operationName":"courseUpdate","variables":{"input":{"courseId":"Q291cnNlVHlwZToxNQ==","logo":null}},"query":"mutation courseUpdate($input: CourseUpdateInput!) {\n  courseUpdate(input: $input) {\n    success\n    errors\n    __typename\n  }\n}"}
map: {"1":["variables.input.logo"]}
1: (binary)
```

but I got response: 
```
{"errors":[{"message":"Must provide query string."}]}
```

Please, help me. Everything is set up absolutely OK, but no one met this issue except me.

**Comment by dChunikhin** [comment]
@jaydenseric

**Comment by jaydenseric** [comment]
Perhaps your GraphQL server isn't processing multipart GraphQL requests properly. Maybe there is some kind of middleware that is converting the upload stream into an in memory object before passing that on to the next middleware as the request body, and it doesn't have a query field like the GraphQL middleware later is expecting.

**Comment by jaydenseric** [comment]
Closing because it seems `apollo-upload-client` is functioning properly and is sending a GraphQL multipart request; something else, perhaps on the GraphQL server side, is not setup correctly.
