### ISSUE TITLE
Can this lib provider `typings` 

### ISSUE THREAD

**Issue by tyc15129** [jaydenseric/apollo-upload-client#346]
can this lib provider `typings`

**Comment by jaydenseric** [comment]
This package has TypeScript types baked into the exported modules via TypeScript style JSDoc comments, please see the TS config requirements to get the types working correctly in your project:

https://github.com/jaydenseric/apollo-upload-client/tree/v18.0.1?tab=readme-ov-file#requirements

You can see an explanation why it's done this way here:

https://github.com/jaydenseric/apollo-upload-client/issues/338#issuecomment-2041348730

**Comment by tyc15129** [comment]
yes i see we have @types/apollo-upload-client but it has `depenedices` @appllo/client

    "dependencies": {
        "@apollo/client": "^3.8.0",
        "@types/extract-files": "*",
        "graphql": "14 - 16"
    },

**Comment by tyc15129** [comment]
for now `@apollo/client` is 3.9.5, can we need to update the range of dependency

**Comment by jaydenseric** [comment]
`@types/apollo-upload-client` shouldn't be used; nowadays the package `apollo-upload-client` contains it's own types, baked into the exported modules as TypeScript flavour JSDoc comments.

> for now @apollo/client is 3.9.5, can we need to update the range of dependency

Perhaps you're confused. `"@apollo/client": "^3.8.0",` matches `@apollo/client` v3.9.5, because of the `^`.
