### ISSUE TITLE
This package itself specifies a 'main' module field that could not be resolved

### ISSUE THREAD

**Issue by khryshan** [jaydenseric/apollo-upload-client#350]
Hi, I've updated from 17.0.0 to 18.0.1 this package on my current react-native project and faced an issue:

`Error: While trying to resolve module 'apollo-upload-client' from file 'my-path-to-file', the package 'path/node_modules/apollo-upload-client/package.json' was successfully found. However, this package itself specifies a 'main' module field that could not be resolved ('path/node_modules/apollo-upload-client/index'. Indeed, none of these files 'exist:'`

Do you have any idea how to fix it? I really appreciate any help you can provide.

**Comment by jaydenseric** [comment]
You need to deep import a specific module. See:

https://github.com/jaydenseric/apollo-upload-client/tree/v18.0.1?tab=readme-ov-file#exports

The changelog has a migration guide in the v18 major changes section:

https://github.com/jaydenseric/apollo-upload-client/blob/v18.0.1/changelog.md#1800

**Comment by khryshan** [comment]
@jaydenseric Thanks for the quick response. I've read the changelog and tried to use deep import `import create Upload Link from "apollo-upload-client/createUploadLink.mjs".` But I'm still getting the issue.
Besides that, I removed node_modules, and package-lock and reinstalled everything again. It didn't help as well.
