### ISSUE TITLE
Getting net::ERR_CONNECTION_RESET on uploading 7mb audio file using Apollo Upload Client

### ISSUE THREAD

**Issue by luizlevindiniz** [jaydenseric/apollo-upload-client#353]
Hi @jaydenseric, nice to meet you. 

I have a nextjs app router frontend and a nestjs backend. The front utilizes apollo client to make requests and the back uses nest/graphql and graphql-upload-minimal to handle it. 

The frontend is responsible for sending a mp3 audio file to the backend, but I have been receiving an ERR_CONNECTION_RESET while using apollo-upload-client. Curiously, this only occurs for large files. When I upload a file of some kBs, I don't get the error. 

I will provide the main parts of my code below, along with an image and my dependencies. Any idea on how to fix it? I've done some research but wasn't successful

![image](https://github.com/user-attachments/assets/1f015748-2fdb-4e23-ad8e-015076d92339)

**Front Packages**
"next": "14.2.4",
"@apollo/client": "^3.10.8",
"apollo-upload-client": "^18.0.1",

**Back Packages**
 "@apollo/server": "^4.10.4",
"@nestjs/apollo": "^12.1.0",
"@nestjs/graphql": "^12.1.1",
"graphql": "^16.9.0",
"graphql-upload-minimal": "^1.6.1",

**FRONTEND**

**apolloClient.ts**
```
import { ApolloClient, type ApolloLink, InMemoryCache } from "@apollo/client";
import createUploadLink from "apollo-upload-client/createUploadLink.mjs";

const nodeEnv = process.env.NODE_ENV;
const backendUri =
  nodeEnv === "development"
    ? process.env.NEXT_PUBLIC_LOCAL_BACKEND_URI
    : process.env.NEXT_PUBLIC_BACKEND_URI;

export const apolloClient = new ApolloClient({
  ssrMode: typeof window === "undefined",
  cache: new InMemoryCache(),
  link: createUploadLink({
    uri: backendUri,
  }) as unknown as ApolloLink,
  headers: {
    "Apollo-Require-Preflight": "true",
  },
});
```

**uploadAudio**

```
export async function uploadAudio(file: File) {
  const accessToken = await validateSession();

  try {
    const { data } = await apolloClient.mutate({
      mutation: gql`
        mutation UploadAudio($file: Upload!) {
          uploadAudio(file: $file) {
            success
            message
            audioUrl
          }
        }
      `,
      variables: { file },
      context: {
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "Content-Type": "audio/mpeg",
          "Apollo-Require-Preflight": "true",
        },
      },
      fetchPolicy: "no-cache",
    });

    return data;
  } catch (error) {
    console.error("Error uploading audio", error);
    return null;
  }
}
```

**BACKEND**

**audio.resolver.ts**
```
import { Args, Mutation, Resolver } from "@nestjs/graphql";
import { UseGuards } from "@nestjs/common";
import {GraphQLUpload, FileUpload } from "graphql-upload-minimal";
import { SupabaseAuthGuard } from "src/guards/supabase-auth-guard";
import { AudioService } from "./youtube.service";
import { AudioUploadResponseDto } from "./dto/audio-upload.dto";
import { IsAdminGuard } from "src/guards/supabase-admin-guard";

@UseGuards(SupabaseAuthGuard)
@Resolver()
export class AudioResolver {
  constructor(private readonly audioService: AudioService) {}

  @UseGuards(IsAdminGuard)
  @Mutation(() => AudioUploadResponseDto, { name: 'uploadAudio' })
    async uploadAudio(
    @Args({ name: 'file', type: () => GraphQLUpload })
   file: FileUpload
  ){
    console.log('file', file, typeof file)
    return await this.audioService.uploadAudio(file);
  }
}
```

**nestjs main.ts file**
```
import { NestFactory } from "@nestjs/core";
import { AppModule } from "./app.module";
import { ValidationPipe } from "@nestjs/common";
import {graphqlUploadExpress} from "graphql-upload-minimal";

import helmet from "helmet";

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  app.useGlobalPipes(new ValidationPipe());
  app.enableShutdownHooks();
  app.use(graphqlUploadExpress({ maxFileSize: 10000000, maxFiles: 10 }));


  app.use(
    helmet({
      crossOriginEmbedderPolicy: false,
      contentSecurityPolicy: {
        directives: {
          imgSrc: [
            `'self'`,
            "data:",
            "apollo-server-landing-page.cdn.apollographql.com",
          ],
          scriptSrc: [`'self'`, `https: 'unsafe-inline'`],
          manifestSrc: [
            `'self'`,
            "apollo-server-landing-page.cdn.apollographql.com",
          ],
          frameSrc: [`'self'`, "sandbox.embed.apollographql.com"],
        },
      },
    })
  );

  app.enableCors();

  await app.listen(3001);
}
bootstrap();
```

**MORE INFO**

AudioService.uploadAudio is a function that just return {success : true}, I'm focused on solving this issue first.
The backend is printing the file appropriately, so it is receiving the file (or a chunk of it, idk).

Thanks for all

**Comment by luizlevindiniz** [comment]
Also, a small addition: 
- I've tried to make the request using Chrome and Edge, both result in the same error. 
- https://github.com/jaydenseric/apollo-upload-client/issues/60 appending a / at the end of my backend url also did not work.

**Comment by jaydenseric** [comment]
Make sure that your sever (i.e. Apache or NGINX) config has limits greater than those configured in the `graphql-upload` option `maxFileSize` (so that `graphql-upload` can respond with a nice error if your request goes over, instead of the connection dropping out), and make sure that you are promisifying and awaiting the end of the file upload streams in resolvers.

**Comment by jaydenseric** [comment]
Also, maybe take a look at https://github.com/jaydenseric/apollo-upload-client/issues/344#issuecomment-2041368669 .
