### ISSUE TITLE
Cannot find module on vite react typescript application

### ISSUE THREAD

**Issue by lovoj-app** [jaydenseric/apollo-upload-client#354]
packages
    "apollo-upload-client": "^18.0.1",
    "@types/apollo-upload-client": "^18.0.0",

Error Facing
     ├╴  Cannot find module 'apollo-upload-client' or its corresponding type declarations. typescript

**Comment by jaydenseric** [comment]
For the correct way to import modules, see the readme instructions:

https://github.com/jaydenseric/apollo-upload-client/tree/v18.0.1?tab=readme-ov-file#exports

```js
import createUploadLink from "apollo-upload-client/createUploadLink.mjs";
```

Uninstall `@types/apollo-upload-client`, this package has it's own types if you follow the TypeScript config requirements:

https://github.com/jaydenseric/apollo-upload-client/tree/v18.0.1?tab=readme-ov-file#requirements
