### ISSUE TITLE
Error in setting cookie while using apollo upload client

### ISSUE THREAD

**Issue by Notnobcoder** [jaydenseric/apollo-upload-client#355]
App.tsx

import { ApolloClient, InMemoryCache } from '@apollo/client';
import createUploadLink from 'apollo-upload-client/createUploadLink.mjs';

// Apollo Client setup
const client = new ApolloClient({

  // This line causes issues with cookie handling, so it's currently commented out.
  // link: createUploadLink({ uri: 'http://localhost:9000/graphql' }),
  
  uri: 'http://localhost:9000/graphql', // Fallback URI without file upload support
  cache: new InMemoryCache(), // Cache configuration
  credentials: 'include', // Ensures cookies are included in requests
  
  defaultOptions: {
    watchQuery: {
      nextFetchPolicy: 'cache-first', // Use cached data first for performance
    },
  },
});

**Comment by jaydenseric** [comment]
What exactly happens? Is there an error message? Does the server reject the request? You need more detail.

Note that you should be aware of some security things when making requests with cookies:

https://github.com/jaydenseric/graphql-multipart-request-spec?tab=readme-ov-file#security

If you are using Apollo Server, there are some special settings and headers you should use (i.e. `Apollo-Require-Preflight`):

https://www.apollographql.com/docs/apollo-server/security/cors/#preventing-cross-site-request-forgery-csrf

**Comment by Notnobcoder** [comment]
Backend Stack:

Apollo GraphQL
Express
TypeGraphQL

const client = new ApolloClient({
  // link: createUploadLink({ uri: 'http://localhost:9000/graphql' }),
  uri: 'http://localhost:9000/graphql',
  cache: new InMemoryCache(),
  credentials: 'include', // Ensures cookies are included in requests
  defaultOptions: {
    watchQuery: {
      nextFetchPolicy: 'cache-first',
    }
  },
});


I commented out this line, and surprisingly, everything works fine now with no errors.

**Comment by jaydenseric** [comment]
You didn't reply to my questions necessary for me to be able to offer any sort of advice:

> What exactly happens? Is there an error message? Does the server reject the request? You need more detail.

**Comment by DyazZz** [comment]
Faced the same issue, my solution was:

const httpLink = createUploadLink({ uri: `localhost:5000/graphql`, fetchOptions: { credentials: 'include' } });

const client = new ApolloClient({
  cache: new InMemoryCache(),
  link: httpLink,
});
