### ISSUE TITLE
Support setting headers and credentials from context

### ISSUE THREAD

**Issue by leethree** [jaydenseric/apollo-upload-client#36]
Currently `context.headers` are being ignored by `apollo-upload-client`, which is different from the behaviour of `apollo-link-http`.

 See https://github.com/apollographql/apollo-link/blob/9fa5b4dc9cd67577fd118e1f437b2138fe3cd8eb/packages/apollo-link-http/src/httpLink.ts#L114-L119 , `headers` and `credentials` from context should merge with `fetcherOptions`.

**Comment by jaydenseric** [comment]
That's a deliberate API divergence, you can set headers and credentials via context by using `fetchOptions`:

```js
const authLink = new ApolloLink((operation, forward) => {
    const viewerToken = getViewerToken()
    if (viewerToken)
      operation.setContext({
        fetchOptions: {
          headers: {
            authorization: `Bearer ${viewerToken}`
          }
        }
      })
    return forward(operation)
  })
```

**Comment by leethree** [comment]
OK! The workaround looks good to me. Would be great if this behaviour is documented. 

Thanks a lot!

**Comment by jaydenseric** [comment]
With `apollo-upload-client@6.0.0-beta.2` you should be able to set `credentials` and `headers` directly on the link and via context. Please test it out!

**Comment by leethree** [comment]
Just upgraded and it's working well. Thanks!
