### ISSUE TITLE
Network errors not caught correctly

### ISSUE THREAD

**Issue by jaydenseric** [jaydenseric/apollo-upload-client#38]
See https://github.com/jaydenseric/apollo-upload-client/issues/35#issuecomment-343007135.

Apparently `.catch(observer.error)` does not work the same as `.catch(error => observer.error(error))`.

**Comment by jaydenseric** [comment]
@adamdonahue the issues you were experiencing should be fixed in `apollo-upload-client@6.0.0-beta.3`.

**Comment by adamdonahue** [comment]
Fantastic. Thanks.  You're quick; I was planning to take a look today
myself.
