### ISSUE TITLE
Upload progress?

### ISSUE THREAD

**Issue by savovs** [jaydenseric/apollo-upload-client#4]
@jaydenseric I've been wondering how to track progress for uploads. Would love to implement it here. No idea where to start though

**Comment by jaydenseric** [comment]
I have no idea either to be honest. We talked about that, along with a few other ideas over here: https://github.com/jaydenseric/apollo-upload-client/issues/1.

To start with, `fetch` does not support upload progres. We would have to switch to using `XMLHttpRequest`. But once we have the means to track the progress, I can't think of the right way to make it available via the Apollo query/mutation APIs. The answer to this would probably be the answer to a better loading status in Apollo for all queries.

Open to ideas, but as yet I don't have any myself.

**Comment by jaydenseric** [comment]
Keep in mind too, that the actual uploading is only part of the turnaround time for a mutation response. There is also whatever processing you do to the uploads in the resolver (move file from temp to permanent storage, update DB, etc.). So I guess you would ideally show a loading progress for the upload, then a spinner for the processing wait?

**Comment by savovs** [comment]
Yeah, I showing a spinner would be easiest until [streams](https://jakearchibald.com/2016/streams-ftw/) get in.
