### ISSUE TITLE
createUploadLink : TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by capsule5** [jaydenseric/apollo-upload-client#43]
Hi,

With this setup:

`import { createUploadLink } from "apollo-upload-client"`
...
```
const client = new ApolloClient({
  link: createUploadLink({ uri: "http://localhost:3002/graphql" }),
  cache: new InMemoryCache(),
})
```

I got an error  : TypeError: Object(...) is not a function coming from __webpack_require__

But with:

`import { createHttpLink } from "apollo-link-http"`
...
```
const client = new ApolloClient({
  link: createHttpLink({ uri: "http://localhost:3002/graphql" }),
  cache: new InMemoryCache(),
})
```

It works

Do I miss something?

**Comment by jaydenseric** [comment]
Are you using native ESM in node (`.mjs`)?

**Comment by capsule5** [comment]
@jaydenseric no

**Comment by jaydenseric** [comment]
Strange. Does it work if you try:

```js
import apolloUploadClient from "apollo-upload-client"
```

And:

```js
const client = new ApolloClient({
  link: apolloUploadClient.createUploadLink({ uri: "http://localhost:3002/graphql" }),
  cache: new InMemoryCache(),
})
```

**Comment by capsule5** [comment]
Neither. no I got TypeError: __WEBPACK_IMPORTED_MODULE_6_apollo_upload_client___default.a.createUploadLink is not a function

**Comment by jaydenseric** [comment]
Oh, if it's create-react-app there is a bug that has been patched to do with webpack being misconfigured to treat .mjs files as assets instead of JS files. I'll dig up a link for you.

**Comment by jaydenseric** [comment]
See https://github.com/jaydenseric/apollo-upload-client/issues/35#issuecomment-343344452 🙂

**Comment by capsule5** [comment]
Thanks a lot

**Comment by hamza121star** [comment]
Hi, i was reading up this thread and upon following it works. Now, when i push the code to a live link, the error gives : "Error! Network error: Unexpected token < in JSON at position 0" which is occurring due to this the createUploadLink function. This happens when i change "http://localhost:3000/graphql" to the live link of "http://my-website/graphql"
