### ISSUE TITLE
In field "uri": Unknown field

### ISSUE THREAD

**Issue by gHashTag** [jaydenseric/apollo-upload-client#46]
How to fix this error in my react-native project?
I'm uses library `import ImagePicker from 'react-native-image-picker'`

```javascript
GraphQLError: Variable "$file" got invalid value {"uri":"file:///Users/xyz/Library/Developer/CoreSimulator/Devices/BF0FFACC-B049-403D-A27C-048B9BC54636/data/Containers/Data/Application/2AA8E51D-8BE7-4061-B187-82BF1953D9F8/Documents/images/FB720B3C-30A1-4BDF-875C-AAB16AFA35C8.jpg","type":"image/jpeg","name":"photo.jpg"}.
In field "uri": Unknown field.
In field "size": Expected "Int!", found null.
In field "path": Expected "String!", found null.
    at getVariableValues (/Users/xyz/graphql-upload-files-server/node_modules/graphql/execution/values.js:93:15)
    at buildExecutionContext (/Users/xyz/graphql-upload-files-server/node_modules/graphql/execution/execute.js:207:54)
    at executeImpl (/Users/xyz/graphql-upload-files-server/node_modules/graphql/execution/execute.js:121:15)
    at Object.execute (/Users/xyz/graphql-upload-files-server/node_modules/graphql/execution/execute.js:110:229)
    at doRunQuery (/Users/xyz/graphql-upload-files-server/node_modules/apollo-server-core/src/runQuery.ts:149:16)
    at /Users/xyz/graphql-upload-files-server/node_modules/apollo-server-core/src/runQuery.ts:70:39
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```
code
```javascript  
_onShowSignupPress = async () => {
    const { profilePhotoUri } = this.state
    const uploadUri = Platform.OS === 'ios' ? profilePhotoUri.replace('file://', '') : profilePhotoUri 
    const file = new ReactNativeFile({
      uri: uploadUri,
      type: 'image/jpeg',
      name: 'photo.jpg'
    })
    const response = await this.props.mutate({ variables: { file } })
    console.log(response)
  }
```

**Comment by jaydenseric** [comment]
Are both `apollo-upload-client` and `apollo-upload-server` at the latest alpha versions? In the new versions the [`Upload` is a scalar](https://github.com/jaydenseric/apollo-upload-server#upload-scalar), not an input type.

**Comment by gHashTag** [comment]
apollo-upload-server: ^2.0.4
apollo-client-preset: ^1.0.4

### before

schema
```javascript
input Upload {
  name: String!
  type: String!
  size: Int!
  path: String!
}

type Mutation {
  uploadFile(file: Upload!): Boolean!
}
```
resolver
```javascript
  Mutation: {
    uploadFile: (parent, { file }) => {
      return true;
    }
  }
```

### after
schema
```javascript
scalar Upload

type Mutation {
  uploadFile(file: Upload!): Boolean!
}

```
resolver
```javascript
import { GraphQLUpload  } from 'apollo-upload-server'

export default {
  Mutation: {
    uploadFile: GraphQLUpload
  }
}
```
but

> graphql-tools/dist/schemaGenerator.js:274
>                     throw new SchemaError("Resolver " + typeName + "." + fieldName + " must be object or function");
>                     ^
> 
> Error: Resolver Mutation.uploadFile must be object or function

Where is my mistake?

**Comment by export-mike** [comment]
@gHashTag 
are you sure the rest of the server is configured correctly? 
https://github.com/jaydenseric/apollo-upload-server#upload-scalar

**Comment by gHashTag** [comment]
@export-mike I apologize, I'm just learning and maybe do not see the obvious things. I'm studying now uploading photos on this **[video tutorial](https://www.youtube.com/watch?v=V95tULgGpLo&t=133s)**. 
And I can not understand where I have a mistake.
What's wrong with my configuration?

**Comment by gHashTag** [comment]
Now
![2017-12-02 14 24 16](https://user-images.githubusercontent.com/6774813/33514930-8b064f6a-d76c-11e7-954b-b391acb816ea.png)
but `file false` in 
```javascript
  Mutation: {
    uploadFile: async (parent, { file }) => {
      console.log('file', file)
      return true
    }
  }
```

**Comment by export-mike** [comment]
I'm not really sure what your trying to achieve by hard coding the return value. I'd keep to trying to run the example.

**Comment by gHashTag** [comment]
@export-mike I go consistently to steps in this [**video tuturial**](https://www.youtube.com/watch?v=V95tULgGpLo&t=133s)

**Comment by jaydenseric** [comment]
@gHashTag that tutorial is out of date with the current versions of the Apollo upload packages; the API has changed and is more powerful:

- https://github.com/jaydenseric/apollo-upload-client/releases/tag/v7.0.0-alpha.1
- https://github.com/jaydenseric/apollo-upload-server/releases/tag/v4.0.0-alpha.1

I find the best was to learn is by working examples, you can see the resolvers setup [here](https://github.com/jaydenseric/apollo-upload-examples/blob/master/api/resolvers.mjs#L48).

Note the `Upload` scalar resolver is setup [like this](https://github.com/jaydenseric/apollo-upload-examples/blob/master/api/resolvers.mjs#L43).

If you follow all the readme instructions for the latest server and client versions and still have issues, feel free to continue the discussion and we can investigate further 🕵️

**Comment by gHashTag** [comment]
@jaydenseric thank you for your speedy support! All update, client & server.
Now my ImagePicker 'react-native-image-picker' gives me the path  
**profilePhotoUri** : `file:///Users/xyz/Library/Developer/CoreSimulator/Devices/BF0FFACC-B049-403…D2C-B14A7E09D2CB/Documents/images/9238AC3D-9653-4DE2-92A8-07A454F738CE.jpg`
In Firebase I cut off excess
`const uploadUri = Platform.OS === 'ios' ? profilePhotoUri.replace('file:///', '') : profilePhotoUri `
Do I have to do something before I put it in **uri**?
```javascript
    const file = new ReactNativeFile({
      uri: uploadUri,
      type: 'image/jpeg',
      filename: 'photo.jpg'
    })
```

**Comment by jaydenseric** [comment]
I'm not really sure what you're trying to do on the client regarding the `uri`, I don't use React Native but I would imagine whatever `react-native-image-picker` provides is fine to use as-is.

**Comment by gHashTag** [comment]
It is unfortunate that there is no simple example with the express. As soon as I did not try, I could not make a nag with the new update.

I decided to work on the old and therefore the following question. What version apollo-upload-client and apollo-upload-server do you like downloading files like this  **[video tutorial](https://www.youtube.com/watch?v=V95tULgGpLo&t=133s)**?

**Comment by rafinskipg** [comment]
I am trying to understand how to set up the server and the client (using apolloServer,) and I don't really get how to declare the upload type. Quite confusing
