### ISSUE TITLE
How to use this package in combination with `createBatchingNetworkInterface`?

### ISSUE THREAD

**Issue by Eraldo** [jaydenseric/apollo-upload-client#48]
Right now, my setup looks like this:
```ts
const networkInterface = createBatchingNetworkInterface({ uri: `${environment.api}graphql/batch` });

networkInterface.use([{
  applyBatchMiddleware(req, next) {
    if (!req.options.headers) {
      req.options.headers = {};  // Create the header object if needed.
    }
    // some header processing
    ...
    next();
  }
}]);

const client = new ApolloClient({
  networkInterface,
});
```

I do not yet understand where to use `createUploadLink` given my setup.
Please help me understand what to do to get this package to work. :)

**Comment by giautm** [comment]
Please see: https://github.com/jaydenseric/apollo-upload-client/issues/34

**Comment by giautm** [comment]
Sr, if you use older version of `apollo-client` (version 1.x), you can still using apollo-upload-client@5.x for batching requests:
https://github.com/jaydenseric/apollo-upload-client/blob/v5.1.1/src/batched-network-interface.js#L41

**Comment by jaydenseric** [comment]
Thanks @giautm 🙂 

@Eraldo please see [my comment here](https://github.com/jaydenseric/apollo-upload-client/issues/34#issuecomment-350388776).
