### ISSUE TITLE
"Uncaught Error: Must contain a query definition" when apollo-client v2 + compose + client option 

### ISSUE THREAD

**Issue by github0013** [jaydenseric/apollo-upload-client#49]
![localhost](https://user-images.githubusercontent.com/809378/34375859-0c05dd42-eb2c-11e7-8056-81bfc873302f.png)

# environments
```
{
  "dependencies": {
    "@types/react": "^16.0.28",
    "@types/react-dom": "^16.0.3",
    "apollo-client-preset": "^1.0.5",
    "apollo-upload-client": "^7.0.0-alpha.1",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-1": "^6.24.1",
    "graphql": "^0.12.3",
    "graphql-tag": "^2.6.1",
    "parcel-bundler": "1.2.1",
    "react": "^16.2.0",
    "react-apollo": "^2.0.4",
    "react-dom": "^16.2.0",
    "typescript": "^2.6.2"
  }
}

```

When I was trying to have a query and a mutation on a component, I encountered this error.
Very simplified reproductive code is below.

```tsx
class YourComponent extends React.Component<ChildProps<{}, QueryResponse & MutationResponse>, {}> {
  render() {
    console.log(this.props)
    return <div>from YourComponent</div>
  }
}

export default compose(
  graphql<QueryResponse>(QUERY),
  graphql<MutationResponse>(MUTATION, {
    options: props => ({
      client: uploadClient
    })
  })
)(YourComponent)
```

1. you have `compose` to build your graphql
1. you have a query + a mutation
1. you set a client through the options variable on the mutation

If I remove `options` and use the client in ApolloProvider `<ApolloProvider client={uploadClient}>`, then it will remove the error.

```tsx
export default compose(
  graphql<QueryResponse>(QUERY),
  graphql<MutationResponse>(MUTATION)
)(QueryAndMutation)

```

Is it maybe how I build graphql is irregular?

**Comment by jaydenseric** [comment]
If you downgrade to `graphql@^0.11`, does the problem go away? The Apollo ecosystem is still ironing out bugs with the new v0.12.

**Comment by github0013** [comment]
tried `"graphql": "^0.11"` but then this time `parcel` gives build errors / runtime errors (tried 1.2.1 1.3.0 1.3.1), and I am sorry I am a webpack-phobic..

**Comment by jaydenseric** [comment]
What are the errors?

**Comment by github0013** [comment]
Based on this package.json, I just changed `parcel-bundler` version.


```json
{
  "dependencies": {
    "@types/react": "^16.0.28",
    "@types/react-dom": "^16.0.3",
    "apollo-client-preset": "^1.0.5",
    "apollo-upload-client": "^7.0.0-alpha.1",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-1": "^6.24.1",
    "graphql": "^0.11",
    "graphql-tag": "^2.6.1",
    "parcel-bundler": "1.3.1",
    "react": "^16.2.0",
    "react-apollo": "^2.0.4",
    "react-dom": "^16.2.0",
    "typescript": "^2.6.2"
  }
}

```

<img width="505" alt="1__yarn_run_parcel_src_index_html__node_" src="https://user-images.githubusercontent.com/809378/34428921-fa69deca-ec94-11e7-8c39-0e0c23cc5b46.png">

![localhost_1234](https://user-images.githubusercontent.com/809378/34428924-0071fa50-ec95-11e7-913e-c86e1f6324c4.png)


<img width="544" alt="1__yarn_run_parcel_src_index_html__node__and_aaa_and_listing_yahoo_shopping_store" src="https://user-images.githubusercontent.com/809378/34428945-3e80155c-ec95-11e7-9aa1-593bf14fafe6.png">

**Comment by jaydenseric** [comment]
Parcel is pretty new and still ironing out kinks; just recently they [added support for `.mjs` extension](https://github.com/parcel-bundler/parcel/issues/126) which may be important since we use it for our `module` entry.

There have been a few new releases of `apollo-upload-client` since this issue was filed too. If there is still an issue and you can determine a specific bug with `apollo-upload-client` we can re-open and investigate further 😊
