### ISSUE TITLE
Side Effects in extractRequestFiles

### ISSUE THREAD

**Issue by hauptbenutzer** [jaydenseric/apollo-upload-client#5]
Hi! 

When trying to get the lastest version of this client to work, I stumbled upon the following error. 

In https://github.com/jaydenseric/apollo-upload-client/blob/master/src/helpers.js#L47 the query object is overwritten with a string. For the fallback case (no files found) that means ApolloClient will throw an `Invalid AST` error, as the query is now a string. I suppose this is probably not the intended behaviour? 😄

**Comment by jaydenseric** [comment]
Sorry, I'm a little confused. What are the steps to reproduce?

**Comment by hauptbenutzer** [comment]
Right! Sorry for not being clearer on that. 

1. Setup apollo-upload-client like instructed 
2. Try running a standard query / mutation using `apolloClient.mutate/apolloClient.query` that does not contain any files. 

I threw together a quick MWE [here](https://github.com/hauptbenutzer/apollo-upload-client-bug/blob/master/src/index.js).

**Comment by jaydenseric** [comment]
Thanks for putting that together, looking into it now.

**Comment by cpunion** [comment]
Same as me. Every requests got "Error: Network error: Invalid AST Node:". When I downgrade to `3.0.1`, errors gone.

**Comment by jaydenseric** [comment]
Is everything ok working now in [v3.0.3](https://github.com/jaydenseric/apollo-upload-client/releases/tag/v3.0.3)?

**Comment by cpunion** [comment]
Fixed in v3.0.3! Thanks.
