### ISSUE TITLE
Files created with the window.File constructor upload empty in Safari

### ISSUE THREAD

**Issue by samcoenen** [jaydenseric/apollo-upload-client#54]
This is a fun issue! Mostly because I can't seem to pinpoint where the issue exactly lies! 😄 

### Scenario
I use the apollo-upload-client together with the apollo-upload-server in my React project to upload images to my server. I use some simple client-side image compression to reduce the size of the file to upload to speed up the upload process (greatly outweighs the time required to compress the image + lowers data usage).

In Chrome and Firefox the upload works like a charm with compressed images. 👍 

### Problem
In Safari my client doesn't correctly upload the compressed image: the Upload promise on the server resolves to a FileStream with a length of 0. 👎 My Request Headers **Content-Length** is way to small to include the image, so it's simply not being sent, though **no errors** are being thrown. I do get the metadata of the image (filename, mime type etc.) on the server so the request is correctly being sent, it just doesn't contain the image data.

### Expected behaviour
The image would correctly be sent OR an error would be thrown telling me if something's wrong.

### Root of problem
The obvious issue is that I'm breaking my image during compression. However, when I `console.log(URL.createObjectURL(myImage))` and copy/paste that string in an `<img>` tag on the page, it renders correctly and when logging the file itself to the console, I see nothing out of the ordinary either. I can even download and base64 the `File` and open it in an external service without any issues.

It seems to me that the `File` is, in fact, a valid `File`. Apollo-upload-client doesn't agree with me on this one though.

### Code
[The file compression can be seen here at CodeSandbox](https://codesandbox.io/embed/3xjn0oqvk6). It doesn't work for some reason inside CodeSandbox, but can be copy/pasted to local and runs without issues there.

It seems a bit overkill to re-create the rest of the project structure inside CodeSandbox because it's so big and unrelated (as proven by the small request content-length). The code is hosted on a private repo which I'm not allowed to share. FWIW, the server follows https://github.com/jaydenseric/apollo-upload-examples/tree/master/api (only difference is that I use express). After compressing the image, it's sent directly using the `mutate` prop passed by the GraphQL HoC, no further adjustments are made to it.

### Question
I'm not very familiar with the apollo-upload-client, but if someone could give me some pointers in how I can further debug this myself, I'd be glad to do so! Maybe the `File` needs to meet certain conditions I'm unaware of? It currently has a name, content, type and lastModified. IMO an error should at least be thrown when a File should, but couldn't, be uploaded.

**Comment by jaydenseric** [comment]
Hmm, interesting. Have you discovered anymore clues?

Are you using the very latest `apollo-upload-server` version? It detects malformed requests and has better error messages.

If you inspect the multipart POST request, is the file definitely sent as a form field with the right content? It would be useful to narrow down the exact point of failure in Safari.

**Comment by jaydenseric** [comment]
Also, what version of Safari? The `File` constructor is only [supported from v10](https://caniuse.com/#feat=fileapi).

**Comment by samcoenen** [comment]
Thanks for checking in on this @jaydenseric !

I have found one more, rather important, clue. When I take the original, unmodified `File` image and I wrap it into another `File`, which should be possible because `File` is just a `Blob`, like so:

```
// file comes directly from input.files[0]
const wrappedFile = new File([file], file.name, { type: file.type });
console.log(wrappedFile);
```

The file won't be uploaded, even though it's still a valid `File`. This means that I didn't break anything with my image compression logic: it looks like EVERY user generated file inside Safari won't be uploaded correctly.

My current software versions:

- Safari v11.0.2
- apollo-upload-client 7.0.0-alpha.2
- apollo-upload-server 4.0.0-alpha.3

The `File` constructor works in Safari, I can create files without any errors (and log them as well) but they're simply not being uploaded by the upload-client. I use `split` from apollo-link to differentiate my file upload requests and if I log my file to the console there, which is the final step in the chain before uploading, Safari correctly displays it as a proper `File`.
<img width="356" alt="screen shot 2018-01-15 at 09 52 40" src="https://user-images.githubusercontent.com/20949306/34934260-1d6db6ec-f9da-11e7-9ec8-b0a07b604ae6.png">

In the network tab of Safari I can see the request going out, but its' size is not nearly enough to contain the image.
<img width="480" alt="screen shot 2018-01-15 at 10 05 38" src="https://user-images.githubusercontent.com/20949306/34934712-c3c22888-f9db-11e7-8e91-82567c149f81.png">


And this is the actual payload which is sent (according to the Safari network tab).
```
------WebKitFormBoundaryKTP3wk37kCdAfDch
Content-Disposition: form-data; name="operations"

{"query":"mutation createMessageMutation($conversationId: ID!, $message: String!, $attachment: Upload, $isAgent: Boolean) {\n  createMessage(conversationId: $conversationId, message: $message, attachment: $attachment, isAgent: $isAgent) {\n    id\n    message\n    agent {\n      id\n      name\n      avatar\n      online\n      __typename\n    }\n    device\n    attachment\n    createdAt\n    __typename\n  }\n}\n","operationName":"createMessageMutation","variables":{"conversationId":"5a5b6ca78a8119d0eb7cb648","message":"","isAgent":false}}
------WebKitFormBoundaryKTP3wk37kCdAfDch
Content-Disposition: form-data; name="map"

{"0":["variables.attachment"]}
------WebKitFormBoundaryKTP3wk37kCdAfDch
Content-Disposition: form-data; name="0"; filename="IMG_0407.jpg"
Content-Type: image/jpeg


------WebKitFormBoundaryKTP3wk37kCdAfDch--
```

The server is not throwing any errors either, if I wait for the `Upload` Promise to resolve and then log it to the console I get:

```
FileStream {
  _readableState: 
   ReadableState {
     objectMode: false,
     highWaterMark: 16384,
     buffer: BufferList { head: null, tail: null, length: 0 },
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: null,
     ended: true,
     endEmitted: false,
     reading: false,
     sync: true,
     needReadable: false,
     emittedReadable: true,
     readableListening: false,
     resumeScheduled: false,
     destroyed: false,
     defaultEncoding: 'utf8',
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: true,
  domain: null,
  _events: 
   { end: [ [Function], [Function] ],
     limit: { [Function: bound onceWrapper] listener: [Function] } },
  _eventsCount: 2,
  _maxListeners: undefined,
  truncated: false,
  _read: [Function] }
```

Which has a length of 0 which should represent the actual image data so I'm pretty sure the image is not being send at all.

**Comment by jaydenseric** [comment]
The server is functioning correctly; the file being uploaded is simply empty.

Maybe Safari has a bug with appending a constructed `File` as a field to a `FormData` form instance. Maybe try something like this:

```js
const body = new FormData()
const file = new File(/* … */)

body.append('test', file)

fetch('http://localhost:3000', { body })
```

And see if that sends the file with no content.

**Comment by samcoenen** [comment]
I'm currently looking into [this StackOverflow question](https://stackoverflow.com/questions/46570227/safari-sending-empty-file-to-server-on-file-upload-via-formdata), the OP has exactly the same issue as I'm facing here. He managed to solve it by sending the edited `File` as a simple `Blob`, which Safari handles without issues.

I'll test a bit more and write my results here.

**Comment by jaydenseric** [comment]
Found [this bug in the WebKit Bugzilla](https://bugs.webkit.org/show_bug.cgi?id=165081).

**Comment by samcoenen** [comment]
Managed to confirm the linked bug, so it looks like the workaround is to send the `File` as a `Blob`.

However, apollo-upload-client uses your extract-files [which disables `Blob` support](https://github.com/jaydenseric/extract-files/blob/10236ac78548a3f9c64d148aa79e1444e8dff285/src/index.js#L33) because
```js
new Blob instanceof File // = False
```

So if I convert the `File` back to a `Blob` before handling it over to apollo-upload-client, the image data will be left out of the request and the `Upload` Promise on the server is just an empty `{}`.

So... Now what? 😄

**Comment by jaydenseric** [comment]
This is a browser bug, and not something we can fix here. Ultimately it will not change the situation for many people wishing to construct files, since it is well known to be unavailable in IE/Edge.

The best thing we can do is support `Blob` alongside `File` across `extract-files`, `apollo-upload-client`, `apollo-upload-server` and possibly `apollo-upload-examples`. This has been on the radar for a while, see [jaydenseric/extract-files#2](https://github.com/jaydenseric/extract-files/pull/2).

It is not something I will get to quickly, so if you would like to submit PRs and tests for the server and client packages that would be a big help to get the ball rolling. I will not merge a PR until all the packages have PRs have been tested to work together. I'm sure the changes will be only a few lines here or there, it is just the logistics of coordinating an update across all the packages.

If you come across any handy workarounds in the meantime, keep us posted here!

**Comment by samcoenen** [comment]
Thanks for linking that issue.

I will look into the PRs for the different packages when I have a bit of spare time!
