### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by hoodsy** [jaydenseric/apollo-upload-client#57]
When trying to import `createUploadLink`, throws the error: `TypeError: Object(...) is not a function` in `7.0.0-alpha.3`.

```js
import { createUploadLink } from 'apollo-upload-client'
```

**Comment by jaydenseric** [comment]
See https://github.com/jaydenseric/apollo-upload-client/issues/56#issuecomment-358619516, https://github.com/jaydenseric/apollo-upload-client/issues/43#issuecomment-345687397 and https://github.com/jaydenseric/apollo-upload-client/issues/35#issuecomment-343344452. Does updating create-react-app solve the issue?

**Comment by hoodsy** [comment]
Yes! sorry, didn't see those.

**Comment by jaydenseric** [comment]
Awesome, glad it was an easy fix 😊

**Comment by savovs** [comment]
This doesn't work with [react-create-app-typescript](https://github.com/wmonk/create-react-app-typescript). They've merged [.mjs support](https://github.com/facebook/create-react-app/pull/3239), still nada for me.

**Comment by jaydenseric** [comment]
@savovs are you sure the `.mjs` support has made its way into that TypeScript fork?

<img width="521" alt="screen shot 2018-02-17 at 2 34 47 pm" src="https://user-images.githubusercontent.com/1754873/36337674-c03c0048-13ef-11e8-9923-2073d8debbc9.png">

**Comment by savovs** [comment]
Whoops, looks like they might be behind. Sometimes I wish I stuck with JS... 😀

**Comment by saidelghamri** [comment]
check the version of @angular/cdk&material in your package.json if you see a version above 5.2.4 and you're using angular 5 try to downgrade it using those commandes
=> npm uninstall @angular/material --save
then 
=> npm install @angular/material@5.2.4 --save
and for CDK use :
=> npm uninstall @angular/cdk --save
then
=> npm install @angular/cdk@5.2.4 --save

hope it work for you :)

**Comment by papajo** [comment]
TypeError: Object(...) is not a function
What is the solution for this? I am getting the same error also. I am using pure ReactJS environment bootstrapped with create-react-app, none of the angularjs or apollo stuff.  tia.

**Comment by someoneinatree** [comment]
I got this issue. Was trying to use hooks on a non-hooky react version. All good now (npm install react{,-dom}@latest)
