### ISSUE TITLE
Cookie gets not sent

### ISSUE THREAD

**Issue by eigenmannmartin** [jaydenseric/apollo-upload-client#6]
Hi!

Using this config the cookie gets not sent to the server. (as [documented here](http://dev.apollodata.com/core/network.html#BatchingExample))
```JS
    const networkInterface = createBatchNetworkInterface({
        uri: '/graphql',
        batchInterval: 10,
        opts: {
            credentials: 'same-origin'
        }
    });
```

You have to use this to get it working
```JS
    const networkInterface = createBatchNetworkInterface({
        uri: '/graphql',
        batchInterval: 10,
        credentials: 'same-origin'
    });
```

I think this is not intuitive.

**Comment by jaydenseric** [comment]
Fixed in version 4.0.0 by @AdamYee with [#7](https://github.com/jaydenseric/apollo-upload-client/pull/7).
