### ISSUE TITLE
Persisted queries?

### ISSUE THREAD

**Issue by mxstbr** [jaydenseric/apollo-upload-client#61]
I just tried to use the [`apollo-link-persisted-queries`](https://github.com/apollographql/apollo-link-persisted-queries) together with `apollo-upload-client`, but I'm still seeing the full query body being sent over the wire for all queries.

Is there anything `apollo-upload-client` does that could prevent it from working with persisted queries?

**Comment by jaydenseric** [comment]
I'm not sure. Doesn't it just replace the query with a hash?

**Comment by mxstbr** [comment]
Yeah it should, but I'm still seeing the full query being sent over the wire all the time!

**Comment by mxstbr** [comment]
Here are the changes I've made:

1. Added a persisted query store to Engine:

```diff
new Engine({
   engineConfig: {
+    stores: [
+      {
+        name: 'pq',
+        inMemory: {
+          cacheSize: '5000000',
+        },
+      },
+    ],
+    persistedQueries: {
+      store: 'pq',
+    },
   },
 });
```

2. Added `apollo-link-persisted-queries`:

```diff
+import { createPersistedQueryLink } from 'apollo-link-persisted-queries';
 
-  const httpLink = createUploadLink({ /* ...  */ });
+  const httpLink = createPersistedQueryLink().concat(
+    createUploadLink({ /* ... */ })
+  );
```

Then I open my frontend and look in the dev tools, and what I see is this:

![screen shot 2018-02-07 at 11 48 21](https://user-images.githubusercontent.com/7525670/35912417-d1283cdc-0bfc-11e8-9697-bcf824c8049f.png)

Every single API request still sends the entire query text to the server :confused:

**Comment by jbaxleyiii** [comment]
@mxstbr @jaydenseric ah yes! Here is the solution that will need to be implemented in the upload client:

The persisted query link sets a couple items on the context (https://github.com/apollographql/apollo-link-persisted-queries/blob/master/src/index.ts#L128-L131). These are used to tell downstream network (ws, upload, http) that we want to not send the operation, but instead send the extensions.

Network links can then read them and do [this](https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-http/src/httpLink.ts#L200) and [this](https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-http/src/httpLink.ts#L196-L197) to attach the payload correctly.

Happy to help with any questions!

**Comment by jbaxleyiii** [comment]
@jaydenseric also, I'm wondering if you could implement the upload portion of this library as a custom fetcher for http-link that way you don't have to keep things in sync?

https://www.apollographql.com/docs/link/links/http.html#custom

**Comment by jaydenseric** [comment]
@jbaxleyiii I think that might not work, because the `File` and `FileList` instances in `variables` would have been lost when the request body was JSON encoded.

**Comment by mxstbr** [comment]
@jaydenseric can we add support for persisted queries anyways by adding those options to the context, even if it can't be a custom fetcher?

**Comment by jaydenseric** [comment]
The way forward is to use [`apollo-link-utilities`](https://www.npmjs.com/package/apollo-link-utilities) once it has stabilised in [this PR](https://github.com/apollographql/apollo-link/pull/364).

**Comment by mxstbr** [comment]
Is that a yes or a no? 😆

**Comment by jaydenseric** [comment]
Sorry thats a yes! Instead of reinventing the wheel here and across all the other http link packages, we will have an Apollo maintained package of helpers to use for most of the implementation.

**Comment by mxstbr** [comment]
Oh I see, thanks! Can't wait ✨

**Comment by jaydenseric** [comment]
@mxstbr would you like to verify this works as expected with [`apollo-upload-client@7.1.0-alpha.1`](https://github.com/jaydenseric/apollo-upload-client/releases/tag/v7.1.0-alpha.1)?
