### ISSUE TITLE
Apollo + Ionic 3 (angular 4) we have not access to filesystem but we have DATA_URL image. How to correctly Upload it?

### ISSUE THREAD

**Issue by wuilliam321** [jaydenseric/apollo-upload-client#62]
```javascript
      // dataURI is the result of:  this.camera.getPicture(this.options)
      /**
       * this.options = {
       *       quality: 100,
       *       destinationType: this.camera.DestinationType.DATA_URL,
       *       sourceType: this.camera.PictureSourceType.PHOTOLIBRARY,
       *       encodingType: this.camera.EncodingType.JPEG,
       *       mediaType: this.camera.MediaType.PICTURE
       *     };
       **/
      let myFile = this.dataURLtoBlob('data:image/jpeg;base64,' + dataUri);

      let xhr = new XMLHttpRequest();
      xhr.responseType = 'json';
      xhr.open("POST", "/graphql");
      xhr.setRequestHeader("Content-Type", "application/json");
      xhr.setRequestHeader("Accept", "application/json");
      xhr.onload = function () {
        console.log('data returned:', xhr.response);
      };
      let query = `mutation upload ($file: Upload!) {
        singleUpload(file: $file) {
          id
        }
      }`;

      xhr.send(JSON.stringify({
        query: query,
        variables: {
          file: myFile
        }
      }));
```

My main question is: I don't have access to the filesystem, that's the reason why i'm asking for the content of the image. Is this the right way to call the mutation?

This is a simple script of what we are trying. We are using apollo-upload-server too.

**Comment by wuilliam321** [comment]
This is our on-production implementation:
```
  runMutation(dataUri: any): Observable<any> {
    const myFile = {
      filename: 'documentProof',
      stream: dataUri, // Same dataUrl from this.camera.getPicture(this.options)
      mimetype: 'image/png',
      encoding: 'utf8'
    };

    const variables = {file: myFile};
    return this.apolloProvider.mutation(this.mutation, variables)
  }
```

And it works but it is not a multipart request, it is not reading the file from filesystem, as you see, filename mimetype and encoding are hardcoded. It works, but we are not sure if it is the right way.

**Comment by jaydenseric** [comment]
It seems you are not using `apollo-upload-client` at all? I can follow what you are attempting in the first example, but I don't follow the second.

If you want to make a manual request on the client you need to follow the [GraphQL multipart request spec single file example](https://github.com/jaydenseric/graphql-multipart-request-spec#single-file).

You can create a `Blob` from the Base64 file (looks like you have already worked out how to do that), and add it to a `FormData` form as the `body` of a `fetch` request. Although it's a bit different for Node.js, you can get an idea how that might work by looking at the [single file test upload](https://github.com/jaydenseric/apollo-upload-server/blob/master/src/test.mjs#L43) for `upollo-upload-server`.

**Comment by jaydenseric** [comment]
Feel free to discuss this further in the [`#uploads` chanel of the Apollo Slack](https://apollographql.slack.com/messages/uploads).

**Comment by smithaitufe** [comment]
@jaydenseric I am using `apollo-upload-client` in my case but lost as to how to go about it.

It was working fine when I used Expo. But I dropped Expo when I noticed some constraints and switched back to React Native. In Expo, I got something like this in place of the uri: `file://`

But using `ImagePicker.showImagePicker` from `'react-native-image-picker'`  gives me this response when an Image is selected.

```
{ uri: 'content://media/external/images/media/133658',name: 'IMG_20180208_103713.jpg',type: 'image/jpeg',data: '/9j/4SqnRXhpZgAASUkqAAgAAAARAA4BAgAgAAAA2gAAAA8BAgAgAAAA+gAAABABAgAgAAAAGgEAABIBAwABAAAAAQAAABoBBQABAAAAOgEAABsBBQABAAAAQgEAACgBAwABAAAAAgAAADEBAgAgAAAASgEAADIBAgAUAAAAagEAABMCAwABAAAAAgAAACACBAABAAAAAAAAACECBAABAAAAAAAAACICBAABAAAAAAAAACMCBAABAAAAAAAAACQCBAABAAAAAQAAACUCAgAgAAAAfgEAAGmHBAABAAAAngEAACADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFRFQ05PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUGhhbnRvbTYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIAAAAAQAAAEgAAAABAAAATWVkaWFUZWsgQ2FtZXJhIEFwcGxpY2F0aW9uCgAAAAAyMDE4OjAyOjA4IDEwOjM3OjE0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGQCaggUAAQAAANACAACdggUAAQAAANgCAAAiiAMAAQAAAAAAAAAniAMAAQAAAOcCAAAAkAcABAAAADAyMjADkAIAFAAAAOACAAAEkAIAFAAAAPQCAAABkQcABAAAAAECAwAEkgoAAQAAAAgDAAAHkgMAAQAAAAIAAAAIkgMAAQAAAP8AAAAJkgMAAQAAAAAAAAAKkgUAAQAAABADAACQkgIAAgA'
}
```
This is making me to think that I will need to upload the Blob in the data property. But how do I proceed? Will the card at the backend remain the same?

**Comment by jaydenseric** [comment]
@smithaitufe I think for that example you just need to do this:

```
import { ReactNativeFile } from 'apollo-upload-client'

const file = new ReactNativeFile({
  uri: 'content://media/external/images/media/133658',
  type: 'image/jpeg',
  name: 'MG_20180208_103713.jpg'
})
```

And use the `file` somewhere in your mutation variables.

**Comment by smithaitufe** [comment]
@jaydenseric  But that is not working for me.

**Comment by jaydenseric** [comment]
@smithaitufe could you please raise a separate issue, detailing minimum reproduction steps to get that error? It appears unrelated to either of the two issues it has been discussed in.

**Comment by smithaitufe** [comment]
@jaydenseric Alright. Thanks for your help thus far.
