### ISSUE TITLE
TypeScript type declarations

### ISSUE THREAD

**Issue by savovs** [jaydenseric/apollo-upload-client#66]
Is anyone using this repo with TypeScript? I'm getting this error when I try to compile my project:
` TS7016: Could not find a declaration file for module 'apollo-upload-client'.`

**Comment by jaydenseric** [comment]
I don't know why, there is nothing to do with TypeScript in this repo. The `apollo-link-http-common` dependency is written in TypeScript, could there be something wrong with it?

**Comment by savovs** [comment]
Fixed the error by adding `declare module 'apollo-upload-client';` to a `types.d.ts` type declaration file.

**Comment by PatrLind** [comment]
This seems to do the trick for me:
```
import { HttpLink, FetchOptions } from "apollo-link-http/lib/httpLink";

declare module 'apollo-upload-client';

export function createUploadLink(options?: FetchOptions): HttpLink;
```

**Comment by Slessi** [comment]
If using `react-native` you also probably need the `extract-files` definitions (not sure if `createUploadLink` returns an `ApolloLink` or `HttpLink`

```ts
declare module "apollo-upload-client" {
    import { ApolloLink } from "apollo-link";
    import { FetchOptions } from "apollo-link-http";

    export function createUploadLink(linkOptions?: FetchOptions): ApolloLink;

    export * from "extract-files";
}

declare module "extract-files" {
    export type ReactNativeFileOptions = {
        uri: string;
        type: string;
        name: string;
    };

    export class ReactNativeFile {
        constructor(options: ReactNativeFileOptions);

        public static list(files: ReactNativeFileOptions[]): ReactNativeFile[];
    }
}
```
