### ISSUE TITLE
VueJS example

### ISSUE THREAD

**Issue by maarteNNNN** [jaydenseric/apollo-upload-client#73]
I'm really stuck on how to handle this in VueJS. I created my mutation:

```graphql
const CREATE_FILE_MUTATION = gql`
  mutation($picture: Upload!) {
    createFile(file: $picture) {
      id
      url
    }
  }
`
```

and my method:

```javascript
onUpload () {
      const formData = new FormData()
      formData.append('myFile', this.picture, this.picture.name)
      console.log(JSON.stringify(formData))

      return this.$apollo.mutate({
        mutation: CREATE_FILE_MUTATION,
        variables: {
          picture: formData
        }
      })
        .then((data) => {
          console.log(data)
          })
        })
        .catch((err) => {
          console.log(err)
          })
        })
```

Logging the formData variable shows an empty object.

Logging the picture object:
`File(65321) {name: "example.png", lastModified: 1519675567655, lastModifiedDate: Mon Feb 26 2018 17:06:07 GMT-0300 (-03), webkitRelativePath: "", size: 65321, …}`
I've been stuck trying things for a couple of days. PS. I never did image uploads.

**Comment by jaydenseric** [comment]
`apollo-upload-client` will make the `FormData` and fetch request for you. So, without knowing the context of what `this.picture` (let's assume it is a `window.File` instance, perhaps from a file input value) you code could be:

```js
this.onUpload = () =>
  this.$apollo
    .mutate({
      mutation: CREATE_FILE_MUTATION,
      variables: { picture: this.picture }
    })
    .then(data => {
      console.log(data)
    })
    .catch(err => {
      console.log(err)
    })
```

**Comment by razorabhu1995** [comment]
@jaydenseric can you tell me how to use apollo-upload-client in nuxtjs

**Comment by jaydenseric** [comment]
@razorabhu1995 no sorry; I'm not familiar with it. However you are currently integrating the standard Apollo HTTP link, replace it with the one from here.

**Comment by razorabhu1995** [comment]
@jaydenseric Can you give me the query example to upload image in Vuejs.

**Comment by jaydenseric** [comment]
@razorabhu1995 No.

> @razorabhu1995 no sorry; I'm not familiar with it. However you are currently integrating the standard Apollo HTTP link, replace it with the one from here.

**Comment by razorabhu1995** [comment]
@maarteNNNN  Did you get it to work>??

**Comment by maarteNNNN** [comment]
I did not get it to work unfortunately. I used express to handle file
upload. Using this have me a bunch of headaches 😅.

**Comment by yazer79** [comment]
Does this package support VueJS or not? I can't find any VueJS example and this post is closed from 2 years

**Comment by jaydenseric** [comment]
@yazer79 a quick Google reveals quite a few tutorials confirming it does. For example:

- https://blog.logrocket.com/demonstration-on-how-to-use-graphql-with-node-and-vue-in-bits-8981f0d65f94
- https://scotch.io/tutorials/handling-file-uploads-in-graphql-and-vue

**Comment by ivanvorona** [comment]
@yazer79  - did you find solution for this?   @jaydenseric  from your list - second solution didn't work for me ( it doesn't look like it wraps into formData by default) and first solution is incomplete from what i can tell.

**Comment by ivanvorona** [comment]
@jaydenseric - please ignore my statement - apollo-boost VS apollo-client was my issue. i learned it hard way. it works great, thx!

**Comment by DNature** [comment]
I've been trying to figure this out.
I tried to display images from my Apollo-server but couldn't get it to work because it's returning `text/html` for images in vuejs but  it worked fine in react though i was having same issues in the production build of react. 
I don't want to use any third party API like `cloudinary` or `cloudflare` for storing uploads and i also don't want to return a CDN like url because the image path are gotten from a markdown file. Please i need help :)
