### ISSUE TITLE
mail spring not found mailsync.tar.gz file

### ISSUE THREAD

**Issue by datamail321** [jaydenseric/apollo-upload-client#77]
Mailspring could find the mailsync process. If you're building Mailspring from source, make sure mailsync.tar.gz has been downloaded and unpacked in your working copy.
![centosdata-2018-03-16-10-07-33](https://user-images.githubusercontent.com/37430863/37504124-68abc476-2902-11e8-9103-11d720a82679.png)

**Comment by jaydenseric** [comment]
I'm confused; this does not seem to relate to `apollo-upload-client` at all. Did you accidentally raise this issue in the wrong repo?

**Comment by datamail321** [comment]
Actually We need to use your mailsping to build a mailclient please suggest us step by step process how we can install and customize it for our purpose. We also ready to provide fees/ buy paid version to get your support.
