### ISSUE TITLE
Special filename chars crash React Native

### ISSUE THREAD

**Issue by frederic-lavrut** [jaydenseric/apollo-upload-client#78]
Hi,

Just tryed to upload a PDF downloaded from Linkedin and this error keep showing.

It seem to come from the name/filename in formData which does not support char like "éàè...", maybe ReactNativeFile should have an update to support/escape this type of char in name.

Issue solved for me by setting name in ReactNativeFile with 'test' or '' (empty string).

![screenshot_20180316-165716](https://user-images.githubusercontent.com/7000664/37531229-d50349b2-293b-11e8-9e20-1dfdce73e04a.png)

Here is a sample of my code to replicate the crash
```
const file = new ReactNativeFile({
  uri: res.uri,
  type: 'application/pdf',
  name: "é",
  //name: res.fileName,
});

this.props.mutate({
  variables: {
    file,
  },
}).then(() =>....
```

**Comment by giautm** [comment]
@frederic-lavrut Did you try to escape with `encodeURIComponent`?

**Comment by frederic-lavrut** [comment]
@giautm I did not try, but it should solve the issue, would just need to decode to restore file name.

**Comment by jaydenseric** [comment]
Looked into this back when it was filed and figured it was a bug, but then wasn't so sure a few months later. I think it's an issue with the [React Native `FormData` implementation](https://github.com/facebook/react-native/blob/master/Libraries/Network/FormData.js): https://github.com/facebook/react-native/issues/18486.

**Comment by jaydenseric** [comment]
Closing as the bug is best solved in RN.
