### ISSUE TITLE
premission denied problem in installtion time. please revert me how to solve this problem.

### ISSUE THREAD

**Issue by datamail321** [jaydenseric/apollo-upload-client#80]
[root@localhost Mailspring-master]# npm install babel-core/package.json
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/babel-core/package.json.git
npm ERR! 
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-19T08_12_41_581Z-debug.log
[root@localhost Mailspring-master]#

**Comment by jaydenseric** [comment]
See https://github.com/jaydenseric/apollo-upload-client/issues/77#issuecomment-373602946.
