### ISSUE TITLE
need mail spring full support

### ISSUE THREAD

**Issue by datamail321** [jaydenseric/apollo-upload-client#84]
Actually We need to use your mailsping to build a mailclient please suggest us step by step process how we can install and customize it for our purpose. We also ready to provide fees/ buy paid version to get your support.

**Comment by jaydenseric** [comment]
I've given @datamail321 opportunity to explain how the issues they are raising relate to `apollo-upload-client`, but at this point I'm pretty sure they're some sort of very strange spam bot.
