### ISSUE TITLE
Apollo-boost

### ISSUE THREAD

**Issue by gHashTag** [jaydenseric/apollo-upload-client#86]
### How to connect correctly Apollo-boost and `createUploadLink`?

```javascript
import ApolloClient from 'apollo-boost'
import { createUploadLink } from 'apollo-upload-client'
const client = new ApolloClient({
    createUploadLink({ uri: 'https://ecommerce-etpyjkgsfgzj.now.sh/' })
})

**Comment by jaydenseric** [comment]
I don't think you can, `apollo-boost` is meant to be a low config preset:

> If you’d like to use subscriptions, swap out the Apollo cache, **or add an existing Apollo Link to your network stack that isn’t already included**, you will have to set Apollo Client up manually.
> — https://www.apollographql.com/docs/react/advanced/boost-migration.html

You can manually eject from `apollo-boost` by following [this example](https://www.apollographql.com/docs/react/advanced/boost-migration.html#after). From there you can follow the regular installation instructions documented in this project; basically replace `new HttpLink` with `createUploadLink`.
