### ISSUE TITLE
Misordered multipart fields

### ISSUE THREAD

**Issue by DMP2-Tech** [jaydenseric/apollo-upload-client#87]
Hello,

With the last version i have an error :

FilesBeforeMapUploadError: Misordered multipart fields; files should follow “map” (https://github.com/jaydenseric/graphql-multipart-request-spec).

With the version 2.0.4 i haven't error.

Can you help me ?

Thank's

**Comment by jaydenseric** [comment]
> With the version 2.0.4 i haven't error.

We're up to v8.0.0 😅

Are you sure you are using the latest versions of both the client and server? They work with v2 of the [GraphQL multipart request spec](https://github.com/jaydenseric/graphql-multipart-request-spec/releases).

**Comment by jaydenseric** [comment]
I suspect if you update webpack to the latest version you won't get errors like that. If you discover a specific bug, and are able to provide reproduction steps please raise a new issue 🙏

**Comment by ozanmanav** [comment]
Same error :/
