### ISSUE TITLE
Given example does not work

### ISSUE THREAD

**Issue by Nahasean94** [jaydenseric/apollo-upload-client#91]
I don't know what am missing here but the example in the ReadMe and the File category (only one I have tested) does not seem to work. I have added a bit of my custom code but the code to make the mutation is copy pasted from the example. Here is my code:

    ` import gql from 'graphql-tag'
      import {graphql} from 'react-apollo'
      import React from 'react'
      import {Button, Modal, ModalHeader, ModalBody, ModalFooter} from 'reactstrap'

      export default graphql(gql`
      mutation($file: Upload!) {
      singleUpload(file: $file) 
      }
    )(({show, onClose, mutate}) => {
        if (show) {
            return (
                <Modal isOpen={show} toggle={onClose} size="lg">
                    <ModalHeader toggle={onClose}>Upload a picture</ModalHeader>
                    <ModalBody>
                        < input
                            type="file"
                            required
                            onChange={({target: {validity, files: [file]}}) =>{
                                console.log(file)
                                validity.valid && mutate({variables: {file}})
                            }
                            }
                        />
                    </ModalBody>
                    <ModalFooter>
                        <Button color="secondary" onClick={onClose}>Close</Button>{' '}
                        {/*<Button color="primary" onClick={onUpload}>Upload</Button>{' '}*/}
                    </ModalFooter>
                </Modal>
            )
        }
        else
            return null
    }
     )`

In my code I added the modal because I have a button that when the user clicks, it launches the modal to select a file. Also my mutation is called `singleUpload` as opposed to `uploadFile` in the example.
I have added the line to print details of the selected file in the browser console, and it works. When you select a file, I see the details, but when the request is made to the server, the `file` argument comes as an empty object. 
Below is code for my backend mutation:

       singleUpload: {

            type:GraphQLUpload ,
            args: {
                file: {type: GraphQLUpload},
             },
            async resolve(parent, args, ctx,...rest) {
                console.log(args.file)
               return processUpload(args.file)
            }
        },
    }

FYI. the backend mutation is copied from the [apollo-upload-examples](https://github.com/jaydenseric/apollo-upload-examples/blob/master/api/resolvers.mjs) repository. And it works with the client code attached to the front end code in that repository. I tried editing code from that repository to suit my needs but being a beginner in the realm of graphql, it ended up being too complicated.( ie the front end code to upload the file). So I opted to come to this repository and copy paste the given example as it seems simpler. Unfortunately it does not work.
What am I doing wrong?

**Comment by jaydenseric** [comment]
This is really a usage question and not a specific `apollo-upload-client` issue. The `#uploads` channel of the Apollo Slack team is a friendly place to ask general usage questions :)

If your question was more succinct I might be more inclined to help you debug; for example all the `reactstrap` stuff is superfluous and if the backend code is known to work with another client it doesn't need to be shared.

As a tip, a great first troubleshooting step is the look at the request body payload going to the API using the Chrome dev tools network activity tab. If it is a multipart form that matches the GraphQL multipart request spec ok, then it means the problem is on the server. And vica versa.
