### ISSUE TITLE
How to use dotnet-graphql and apollo-upload-client with file upload?

### ISSUE THREAD

**Issue by tcetin** [jaydenseric/apollo-upload-client#93]
I am trying on file upload dotnet-graphql using Apollo client. But they don't handle file upload multipart data.
So I need to upload a file from Apollo to dotnet-graphql.
Also I asked at [stackoverflow](https://stackoverflow.com/questions/50671937/asp-net-core-file-upload-with-graphql-dotnet)
Is there any implementation of file upload with dotnet-graphql?

Thanks

**Comment by jaydenseric** [comment]
There is none in the [list of known implementations of the GraphQL multipart request spec](https://github.com/jaydenseric/graphql-multipart-request-spec#implementations), but it would not be surprising if something exists. If you find the answer, raise a PR and we'll update the list!
