### ISSUE TITLE
Not valid type for argument "file" in query "fileUpload"

### ISSUE THREAD

**Issue by stephenrichard** [jaydenseric/apollo-upload-client#94]
Hey 👋 

Thanks for making this repo. 

I'm trying to upload a file with a react front-end with Apollo to a Graphql / drupal back-end and keep having the error below:
![](https://puu.sh/AFeYU/393dde30d0.png)

Our back-end dev followed your GraphQL multipart request specification and I followed the initialization for the front-end too. As you can see, what I log is a File object right before the mutation runs but the back-end doesn't receive anything. I have the error after some time so I assume the mutation is send.

I'm using **Apollo: ^1.9.3** and **apollo-upload-client: ^8.0.0**. 
```javascript 
import { createUploadLink } from 'apollo-upload-client'

const client = new ApolloClient({
  networkInterface,
  dataIdFromObject: (o) => o.id,
  link: createUploadLink({ uri: GRAPHQL_API_URL })
})
```

```graphql
const MutationLinkFileToProduct = gql`
  mutation ($file:Upload!) {
    fileUpload(file:$file) {
      entity {
        entityId
        entityType
      }
    }
  }
`
```
I can't figure out if the error comes from my implementation or because of an outdated package ?

**Do I need to upgrade to the new Apollo v2 for this to work ? Or does someone see why it doesn't work?**

Thanks in advance 😇

**Comment by jaydenseric** [comment]
> Do I need to upgrade to the new Apollo v2 for this to work?

Yes, the current implementation is an Apollo Link, which is an Apollo v2 feature. Hope that helps :)

**Comment by stephenrichard** [comment]
Haha, I knew it ! 
Thank you for confirming. 🙂
(I ended up sending the base64 encoded file to a text field).
Next step, upgrading apollo.
