### ISSUE TITLE
File implementation in NativeScript

### ISSUE THREAD

**Issue by kilroy05** [jaydenseric/apollo-upload-client#95]
Hi,

Thanks for making this. I tried to use it but found that there is no 'File' implemented in NativeScript.
Is there a way to work around that?

Cheers

**Comment by jaydenseric** [comment]
I don't know! I'm not motivated to work on it, but happy to keep this open for a while if you would like to investigate 🙏

**Comment by kilroy05** [comment]
Hi,

Alright, I'll see what I can do. Perhaps I can find a way to make it work and share with the community.
👍

**Comment by jaydenseric** [comment]
It's been a while, but if you do work it out feel free to report back here!

**Comment by kilroy05** [comment]
Hi,

Yeah, will do. Haven't done any coding outside of work in the last week and
this was for a personal project.

Thanks

**Comment by hoatructhanhlam** [comment]
@kilroy05 Do you have any solution yet?

**Comment by kilroy05** [comment]
@hoatructhanhlam I'm afraid I never got around to doing it as I wasn't happy enough with nativescript-vue, where I was trying it. Sorry to disappoint

**Comment by PhilippS93** [comment]
bump: Now, the new NativeScript 7 is out now. Are there any plans to support this plugin?

**Comment by jaydenseric** [comment]
@PhilippS93 I personally have no reason to work on it, but welcome someone invested in a solution to take a look.

This project is built using standard APIs such as `File`, `FormData`, `fetch`, etc. The burden should really fall on the creators of new JavaScript environments to support standards like this so we don't have to read their docs and implement hacks for each environment, which are pretty hard to test in an npm package repo’s GitHub Actions CI.
