### ISSUE TITLE
Possible unnecessary dependency to @babel/runtime

### ISSUE THREAD

**Issue by HackedByChinese** [jaydenseric/apollo-upload-client#98]
The package.json declares that it has a dependency on @babel/runtime. Is that actually necessary, or is that a mistake and should be in devDependencies?

**Comment by jaydenseric** [comment]
It's necessary, although practices are [likely to change soon](https://github.com/babel/babel/pull/8266).

The [runtime transform](https://github.com/jaydenseric/apollo-upload-client/blob/v8.1.0/package.json#L45) (configured [here](https://github.com/jaydenseric/apollo-upload-client/blob/v8.1.0/babel.config.js#L22)) needs the [runtime dependency](https://github.com/jaydenseric/apollo-upload-client/blob/v8.1.0/package.json#L38) to be preset at, well, runtime.
